-- Restauration de l etat du 2026-08-25T13:30:59.868Z
-- A executer seulement pour ANNULER les modifications de la phase 2 etape 1.

-- races (nom, taille, bonus, deplacement)
UPDATE races SET nom='Elfe', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=2, bonus_con=-2, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=true WHERE id=1;
UPDATE races SET nom='Humain', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=2;
UPDATE races SET nom='Demi-Elfe', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=true WHERE id=3;
UPDATE races SET nom='Nain', taille='Petite', deplacement_base=6, bonus_for=0, bonus_dex=0, bonus_con=2, bonus_int=0, bonus_sag=0, bonus_cha=-2, vision_nocturne=true WHERE id=4;
UPDATE races SET nom='Halfelin', taille='Petite', deplacement_base=6, bonus_for=-2, bonus_dex=2, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=5;
UPDATE races SET nom='Gnome', taille='Petite', deplacement_base=6, bonus_for=-2, bonus_dex=0, bonus_con=2, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=true WHERE id=6;
UPDATE races SET nom='Demi-Orque', taille='Moyenne', deplacement_base=9, bonus_for=2, bonus_dex=0, bonus_con=0, bonus_int=-2, bonus_sag=0, bonus_cha=-2, vision_nocturne=true WHERE id=7;
UPDATE races SET nom='Illithid', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=8;
UPDATE races SET nom='Demi-Orc', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=9;
UPDATE races SET nom='Demi-Elf', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=10;
UPDATE races SET nom='Petite-gens', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=11;
UPDATE races SET nom='Bariaure', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=12;

-- classes (nom, de_vie, progressions)
UPDATE classes SET nom='Guerrier', de_vie='d12', bba_progression='Plein', vigueur_progression='Bon', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=1;
UPDATE classes SET nom='Magicien', de_vie='d4', bba_progression='faible', vigueur_progression='faible', reflexes_progression='faible', volonte_progression='bon', competences_par_niveau=2 WHERE id=2;
UPDATE classes SET nom='Rôdeur', de_vie='d8', bba_progression='elevee', vigueur_progression='bon', reflexes_progression='bon', volonte_progression='faible', competences_par_niveau=6 WHERE id=3;
UPDATE classes SET nom='Roublard', de_vie='d6', bba_progression='moyenne', vigueur_progression='faible', reflexes_progression='bon', volonte_progression='faible', competences_par_niveau=8 WHERE id=4;
UPDATE classes SET nom='Prêtre', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=5;
UPDATE classes SET nom='Moine', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=6;
UPDATE classes SET nom='Paladin', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=7;
UPDATE classes SET nom='Ensorcelleur', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=8;
UPDATE classes SET nom='Dracologist', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=9;
UPDATE classes SET nom='Battle-mage', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=10;
UPDATE classes SET nom='Blackguard', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=11;
UPDATE classes SET nom='Druide', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=12;
UPDATE classes SET nom='Cryptomancière', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=13;
UPDATE classes SET nom='Noble', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=14;
UPDATE classes SET nom='Assassin', de_vie='d8', bba_progression='Moyen', vigueur_progression='Mauvais', reflexes_progression='Mauvais', volonte_progression='Mauvais', competences_par_niveau=2 WHERE id=15;
UPDATE classes SET nom='Barbare', de_vie='d12', bba_progression='elevee', vigueur_progression='bon', reflexes_progression='faible', volonte_progression='faible', competences_par_niveau=4 WHERE id=16;

-- characters.race_id
UPDATE characters SET race_id=1 WHERE id=1;
UPDATE characters SET race_id=1 WHERE id=3;
UPDATE characters SET race_id=2 WHERE id=4;
UPDATE characters SET race_id=3 WHERE id=5;
UPDATE characters SET race_id=5 WHERE id=6;
UPDATE characters SET race_id=2 WHERE id=20;
UPDATE characters SET race_id=1 WHERE id=21;
UPDATE characters SET race_id=2 WHERE id=22;
UPDATE characters SET race_id=2 WHERE id=23;
UPDATE characters SET race_id=2 WHERE id=24;
UPDATE characters SET race_id=2 WHERE id=25;
UPDATE characters SET race_id=2 WHERE id=26;
UPDATE characters SET race_id=1 WHERE id=27;
UPDATE characters SET race_id=1 WHERE id=28;
UPDATE characters SET race_id=2 WHERE id=30;
UPDATE characters SET race_id=2 WHERE id=31;
UPDATE characters SET race_id=2 WHERE id=32;
UPDATE characters SET race_id=1 WHERE id=33;
UPDATE characters SET race_id=1 WHERE id=34;
UPDATE characters SET race_id=2 WHERE id=35;
UPDATE characters SET race_id=2 WHERE id=36;
UPDATE characters SET race_id=2 WHERE id=37;
UPDATE characters SET race_id=1 WHERE id=38;
UPDATE characters SET race_id=8 WHERE id=39;
UPDATE characters SET race_id=9 WHERE id=40;
UPDATE characters SET race_id=2 WHERE id=41;
UPDATE characters SET race_id=10 WHERE id=42;
UPDATE characters SET race_id=10 WHERE id=43;
UPDATE characters SET race_id=NULL WHERE id=44;
UPDATE characters SET race_id=2 WHERE id=45;
UPDATE characters SET race_id=11 WHERE id=46;
UPDATE characters SET race_id=12 WHERE id=47;
UPDATE characters SET race_id=2 WHERE id=48;
UPDATE characters SET race_id=1 WHERE id=49;
UPDATE characters SET race_id=10 WHERE id=50;
UPDATE characters SET race_id=2 WHERE id=51;
UPDATE characters SET race_id=2 WHERE id=52;
UPDATE characters SET race_id=2 WHERE id=53;
UPDATE characters SET race_id=1 WHERE id=54;
UPDATE characters SET race_id=4 WHERE id=55;
UPDATE characters SET race_id=11 WHERE id=56;
UPDATE characters SET race_id=9 WHERE id=57;
UPDATE characters SET race_id=2 WHERE id=58;
UPDATE characters SET race_id=1 WHERE id=59;
UPDATE characters SET race_id=1 WHERE id=60;
UPDATE characters SET race_id=1 WHERE id=61;
UPDATE characters SET race_id=NULL WHERE id=62;
UPDATE characters SET race_id=NULL WHERE id=63;
UPDATE characters SET race_id=2 WHERE id=64;
UPDATE characters SET race_id=2 WHERE id=65;
UPDATE characters SET race_id=10 WHERE id=66;
UPDATE characters SET race_id=1 WHERE id=67;
UPDATE characters SET race_id=1 WHERE id=68;
UPDATE characters SET race_id=10 WHERE id=69;
UPDATE characters SET race_id=2 WHERE id=70;
UPDATE characters SET race_id=2 WHERE id=71;
UPDATE characters SET race_id=2 WHERE id=72;
UPDATE characters SET race_id=4 WHERE id=73;
UPDATE characters SET race_id=2 WHERE id=74;
UPDATE characters SET race_id=2 WHERE id=75;
UPDATE characters SET race_id=1 WHERE id=76;
UPDATE characters SET race_id=11 WHERE id=77;
UPDATE characters SET race_id=1 WHERE id=78;
UPDATE characters SET race_id=10 WHERE id=79;
UPDATE characters SET race_id=2 WHERE id=80;
UPDATE characters SET race_id=4 WHERE id=81;
UPDATE characters SET race_id=9 WHERE id=82;
UPDATE characters SET race_id=2 WHERE id=83;
UPDATE characters SET race_id=2 WHERE id=84;
UPDATE characters SET race_id=3 WHERE id=85;

-- character_classes
UPDATE character_classes SET personnage_id=5, classe_id=3, niveau=7 WHERE id=21;
UPDATE character_classes SET personnage_id=3, classe_id=2, niveau=6 WHERE id=23;
UPDATE character_classes SET personnage_id=6, classe_id=4, niveau=4 WHERE id=42;
UPDATE character_classes SET personnage_id=6, classe_id=2, niveau=1 WHERE id=43;
UPDATE character_classes SET personnage_id=23, classe_id=5, niveau=4 WHERE id=63;
UPDATE character_classes SET personnage_id=24, classe_id=7, niveau=12 WHERE id=64;
UPDATE character_classes SET personnage_id=25, classe_id=2, niveau=4 WHERE id=65;
UPDATE character_classes SET personnage_id=26, classe_id=3, niveau=4 WHERE id=66;
UPDATE character_classes SET personnage_id=27, classe_id=1, niveau=10 WHERE id=67;
UPDATE character_classes SET personnage_id=28, classe_id=8, niveau=12 WHERE id=68;
UPDATE character_classes SET personnage_id=30, classe_id=4, niveau=15 WHERE id=71;
UPDATE character_classes SET personnage_id=31, classe_id=7, niveau=17 WHERE id=72;
UPDATE character_classes SET personnage_id=32, classe_id=5, niveau=14 WHERE id=73;
UPDATE character_classes SET personnage_id=34, classe_id=1, niveau=10 WHERE id=76;
UPDATE character_classes SET personnage_id=35, classe_id=7, niveau=11 WHERE id=77;
UPDATE character_classes SET personnage_id=35, classe_id=11, niveau=8 WHERE id=78;
UPDATE character_classes SET personnage_id=36, classe_id=5, niveau=8 WHERE id=79;
UPDATE character_classes SET personnage_id=37, classe_id=5, niveau=16 WHERE id=80;
UPDATE character_classes SET personnage_id=38, classe_id=8, niveau=16 WHERE id=81;
UPDATE character_classes SET personnage_id=39, classe_id=4, niveau=12 WHERE id=82;
UPDATE character_classes SET personnage_id=39, classe_id=2, niveau=8 WHERE id=83;
UPDATE character_classes SET personnage_id=40, classe_id=6, niveau=13 WHERE id=84;
UPDATE character_classes SET personnage_id=41, classe_id=4, niveau=11 WHERE id=85;
UPDATE character_classes SET personnage_id=42, classe_id=5, niveau=17 WHERE id=86;
UPDATE character_classes SET personnage_id=46, classe_id=4, niveau=13 WHERE id=90;
UPDATE character_classes SET personnage_id=46, classe_id=2, niveau=6 WHERE id=91;
UPDATE character_classes SET personnage_id=48, classe_id=7, niveau=12 WHERE id=93;
UPDATE character_classes SET personnage_id=51, classe_id=2, niveau=14 WHERE id=96;
UPDATE character_classes SET personnage_id=52, classe_id=1, niveau=6 WHERE id=97;
UPDATE character_classes SET personnage_id=52, classe_id=4, niveau=4 WHERE id=98;
UPDATE character_classes SET personnage_id=53, classe_id=8, niveau=14 WHERE id=99;
UPDATE character_classes SET personnage_id=53, classe_id=14, niveau=6 WHERE id=100;
UPDATE character_classes SET personnage_id=54, classe_id=8, niveau=9 WHERE id=101;
UPDATE character_classes SET personnage_id=55, classe_id=1, niveau=12 WHERE id=102;
UPDATE character_classes SET personnage_id=56, classe_id=4, niveau=10 WHERE id=103;
UPDATE character_classes SET personnage_id=57, classe_id=1, niveau=6 WHERE id=104;
UPDATE character_classes SET personnage_id=58, classe_id=2, niveau=14 WHERE id=105;
UPDATE character_classes SET personnage_id=59, classe_id=3, niveau=13 WHERE id=106;
UPDATE character_classes SET personnage_id=60, classe_id=8, niveau=16 WHERE id=107;
UPDATE character_classes SET personnage_id=61, classe_id=12, niveau=20 WHERE id=108;
UPDATE character_classes SET personnage_id=62, classe_id=8, niveau=3 WHERE id=109;
UPDATE character_classes SET personnage_id=63, classe_id=1, niveau=3 WHERE id=110;
UPDATE character_classes SET personnage_id=64, classe_id=2, niveau=5 WHERE id=111;
UPDATE character_classes SET personnage_id=65, classe_id=1, niveau=12 WHERE id=112;
UPDATE character_classes SET personnage_id=66, classe_id=5, niveau=12 WHERE id=113;
UPDATE character_classes SET personnage_id=67, classe_id=12, niveau=5 WHERE id=114;
UPDATE character_classes SET personnage_id=68, classe_id=4, niveau=5 WHERE id=115;
UPDATE character_classes SET personnage_id=69, classe_id=12, niveau=10 WHERE id=116;
UPDATE character_classes SET personnage_id=71, classe_id=3, niveau=8 WHERE id=118;
UPDATE character_classes SET personnage_id=72, classe_id=4, niveau=5 WHERE id=119;
UPDATE character_classes SET personnage_id=72, classe_id=15, niveau=7 WHERE id=120;
UPDATE character_classes SET personnage_id=74, classe_id=1, niveau=4 WHERE id=121;
UPDATE character_classes SET personnage_id=75, classe_id=5, niveau=3 WHERE id=122;
UPDATE character_classes SET personnage_id=76, classe_id=2, niveau=3 WHERE id=123;
UPDATE character_classes SET personnage_id=76, classe_id=1, niveau=1 WHERE id=124;
UPDATE character_classes SET personnage_id=77, classe_id=8, niveau=4 WHERE id=125;
UPDATE character_classes SET personnage_id=78, classe_id=1, niveau=5 WHERE id=126;
UPDATE character_classes SET personnage_id=79, classe_id=8, niveau=2 WHERE id=127;
UPDATE character_classes SET personnage_id=80, classe_id=6, niveau=2 WHERE id=128;
UPDATE character_classes SET personnage_id=81, classe_id=1, niveau=2 WHERE id=129;
UPDATE character_classes SET personnage_id=82, classe_id=5, niveau=6 WHERE id=130;
UPDATE character_classes SET personnage_id=70, classe_id=2, niveau=14 WHERE id=133;
UPDATE character_classes SET personnage_id=47, classe_id=3, niveau=18 WHERE id=134;
UPDATE character_classes SET personnage_id=49, classe_id=4, niveau=15 WHERE id=148;
UPDATE character_classes SET personnage_id=45, classe_id=2, niveau=16 WHERE id=149;
UPDATE character_classes SET personnage_id=45, classe_id=13, niveau=8 WHERE id=150;
UPDATE character_classes SET personnage_id=33, classe_id=8, niveau=10 WHERE id=154;
UPDATE character_classes SET personnage_id=33, classe_id=10, niveau=7 WHERE id=155;
UPDATE character_classes SET personnage_id=83, classe_id=2, niveau=6 WHERE id=167;
UPDATE character_classes SET personnage_id=22, classe_id=5, niveau=8 WHERE id=169;
UPDATE character_classes SET personnage_id=22, classe_id=6, niveau=16 WHERE id=170;
UPDATE character_classes SET personnage_id=43, classe_id=12, niveau=8 WHERE id=185;
UPDATE character_classes SET personnage_id=20, classe_id=5, niveau=11 WHERE id=199;
UPDATE character_classes SET personnage_id=1, classe_id=1, niveau=6 WHERE id=202;
UPDATE character_classes SET personnage_id=1, classe_id=2, niveau=1 WHERE id=203;
UPDATE character_classes SET personnage_id=84, classe_id=16, niveau=1 WHERE id=204;
UPDATE character_classes SET personnage_id=85, classe_id=2, niveau=6 WHERE id=206;
UPDATE character_classes SET personnage_id=50, classe_id=2, niveau=17 WHERE id=208;
UPDATE character_classes SET personnage_id=4, classe_id=2, niveau=16 WHERE id=211;
UPDATE character_classes SET personnage_id=21, classe_id=4, niveau=10 WHERE id=212;

-- races supprimees : a recreer si besoin (voir export-avant.json)
-- INSERT INTO races (id,nom,bonus_for,bonus_dex,bonus_con,bonus_int,bonus_sag,bonus_cha,taille,deplacement_base,vision_nocturne) VALUES (9,'Demi-Orc',0,0,0,0,0,0,'Moyenne',9,false);
-- INSERT INTO races (id,nom,bonus_for,bonus_dex,bonus_con,bonus_int,bonus_sag,bonus_cha,taille,deplacement_base,vision_nocturne) VALUES (10,'Demi-Elf',0,0,0,0,0,0,'Moyenne',9,false);