-- Restauration de l etat du 2026-08-25T13:50:21.987Z (avant le lot sur)
-- Remet skills, character_skills, races et racial_features exactement dans leur etat d avant.
-- Les entrees supprimees sont recreees avec leur id d origine.

-- 1. recreer les entrees skills supprimees (ignore si elles existent encore)
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (1,'Connaissance des nains','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (2,'Détection','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (3,'Diplomatie','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (4,'Équitation','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (5,'Escalade','FOR',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (6,'Perception auditive','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (7,'Recherche','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (8,'Saut','FOR',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (9,'Survie','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (10,'Connaissance (arcanes)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (11,'Connaissance (plans)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (12,'Connaissance (histoire)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (13,'Magie divine','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (14,'Déchiffrage','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (15,'Concentration','CON',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (16,'Vue','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (17,'Alchimie','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (18,'Artisanat','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (19,'Connaissance Dragons','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (20,'Connaissance de la magie','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (21,'Connaissance des Plans','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (22,'Connaissance des sorts','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (23,'Connaissance Monstres','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (24,'Équitation Dragon','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (25,'Natation','FOR',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (26,'Profession Apoticaire','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (27,'Scrutation','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (28,'Variante de sort','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (29,'Volonté','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (30,'Connaissance (nature)','INT',true,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (31,'Discrétion','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (32,'Ouïe','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (33,'Déplacement silencieux','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (34,'Fouille','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (35,'Acrobaties','DEX',true,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (36,'Artisanat (pièges)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (37,'Bluff','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (38,'Sabotage','INT',true,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (39,'Crochetage','DEX',true,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (40,'Conn. des sorts','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (41,'Premier secours','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (42,'Alchemy','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (43,'Knowledge-arcana','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (44,'Knowledge-monsters','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (45,'Knowledge-planes','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (46,'Listen','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (47,'Search','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (48,'Spellcraft','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (49,'Spot','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (50,'Connaiss. DRAGONS','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (51,'Artisanat (armes)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (52,'Contrefaçon','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (53,'Décryptage','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (54,'Déguisement','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (55,'Désamorçage','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (56,'Équilibre','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (57,'Évasion','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (58,'Maitrise des cordes','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (59,'Vol à la tire','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (60,'Lecture sur les lèvres','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (61,'Langage secret','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (62,'Sens de la nature','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (63,'Ride','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (64,'Heal','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (65,'Religion','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (66,'Appraise','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (67,'Balance','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (68,'Decipher script','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (69,'Escape artist','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (70,'Gather information','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (71,'Jump','FOR',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (72,'Move silently','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (73,'Open lock','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (74,'Pick pocket','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (75,'Use magic device','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (76,'Use rope','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (77,'Knowledge arcana','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (78,'Utilisation d''objets magiques','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (79,'Grimper','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (80,'Sauter','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (81,'Ecouter','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (82,'Déplacement sans bruit','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (83,'Nager','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (84,'Craft - Serrurier','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (85,'Connaissane religion','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (86,'Prédiction','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (87,'Hide','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (88,'Tumble','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (89,'Listen (écoute)','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (90,'Search (fouille)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (91,'Spot (détection)','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (92,'Heal (2 pv x jour x niv.)','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (93,'Knowledge (religion)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (94,'Spellcraft (connaissance sorts)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (95,'Scry (scrutation)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (96,'Sens de l''orientation','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (97,'Connaissance Nature','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (98,'Dressage','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (99,'Connaissance Sorts','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (100,'Empathie Animaux','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (101,'Craft (arrows)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (102,'Acrobatie','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (103,'Profession (jardinière)','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (104,'Knowledge Monsters','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (105,'Knowledge Planes','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (106,'Scry','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (107,'Spellflash','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (108,'Profession (pottery)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (109,'Connaissance sort','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (110,'Désamorsage/sabotage','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (111,'Estimation','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (112,'Lang secret','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (113,'Maitrise corde','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (114,'Utilisation objet magique','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (115,'Jeux','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (116,'Orientation','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (117,'Don artistique','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (118,'Connaissance de la nature','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (119,'Percetion auditive','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (120,'Emphatie avec les animaux','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (121,'Knowledge Underground','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (122,'connaissance des femmes','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (123,'artisanat fabrication flèche','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (124,'Sens orientation','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (125,'Connaissance du commerce','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (126,'Knowledge Religion','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (127,'OpenLock','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (128,'Wilderness Lore','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (129,'Connaissance des sorts (spellcraft)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (130,'Connaissances des monstres','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (131,'Connaissance langues anciennes','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (132,'Connaissance astronomie','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (133,'Profession apothicaire','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (134,'Profession danseur','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (135,'Knowledge (Arcana)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (136,'Healing','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (137,'Knowledge (Radiance)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (138,'Intimidate','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (139,'Utilisation d''obj. magique','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (140,'Knowledge (History)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (141,'Diplomacy','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (142,'Climb','FOR',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (143,'Handle Animal','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (144,'Knomwledge Arcana','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (145,'Forgery','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (146,'Sense motive','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (147,'Perform oratory','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (148,'Craft','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (149,'Apparaise','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (150,'Knowledge (local Blackmoor)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (151,'Knowledge (nobility)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (152,'Perform (dance)','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (153,'Animal Empathy','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (154,'Intuit Direction','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (155,'Knowledge (Nature)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (156,'Swim','FOR',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (157,'Écoute','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (158,'Knowledge Nature','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (159,'Profession Herbalist','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (160,'Dissimulation','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (161,'Monter à cheval','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (162,'Connaissance des monstres','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (163,'Aura magique','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (164,'Conn des sorts','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (165,'Psychologie','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (166,'Empathie avec les animaux','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (167,'Musique (flute)','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (168,'Métier charpentier','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (169,'Premier soins animaux','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (170,'Désamorçage-sabotage','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (171,'Connaissance mystère','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (172,'connaissance religion','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (173,'connaissance monstre','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (174,'profession','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (175,'intimidation','CHA',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (176,'désamorçage/sabotage','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (177,'Artisanat/tissage','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (178,'Stabilité','FOR',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (179,'Fouille (search)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (180,'Détection (spot)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (181,'Connaissance des religions','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (182,'Premiers soins (2 pv x jour x niv.)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (183,'Ingénierie magique','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (184,'Déplacements silencieux','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (185,'Equitation','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (186,'Artisanat (tissage)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (187,'Artisant (piège)','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (188,'Fabrication','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (189,'Monture','INT',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (190,'Artiste de l''évasion','DEX',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;
INSERT INTO skills (id,nom,caracteristique,formation_requise,description) VALUES (191,'Premiers secours','SAG',false,NULL) ON CONFLICT (id) DO UPDATE SET nom=EXCLUDED.nom, caracteristique=EXCLUDED.caracteristique;

-- 2. remettre chaque lien character_skills sur son skill d origine
UPDATE character_skills SET skill_id=30, rangs_investis=10, modif_divers=0 WHERE id=204;
UPDATE character_skills SET skill_id=31, rangs_investis=10, modif_divers=0 WHERE id=205;
UPDATE character_skills SET skill_id=32, rangs_investis=10, modif_divers=0 WHERE id=206;
UPDATE character_skills SET skill_id=9, rangs_investis=10, modif_divers=0 WHERE id=207;
UPDATE character_skills SET skill_id=16, rangs_investis=10, modif_divers=0 WHERE id=208;
UPDATE character_skills SET skill_id=33, rangs_investis=10, modif_divers=0 WHERE id=209;
UPDATE character_skills SET skill_id=15, rangs_investis=9, modif_divers=0 WHERE id=219;
UPDATE character_skills SET skill_id=10, rangs_investis=9, modif_divers=0 WHERE id=220;
UPDATE character_skills SET skill_id=12, rangs_investis=4, modif_divers=0 WHERE id=221;
UPDATE character_skills SET skill_id=11, rangs_investis=5, modif_divers=0 WHERE id=222;
UPDATE character_skills SET skill_id=14, rangs_investis=9, modif_divers=0 WHERE id=223;
UPDATE character_skills SET skill_id=13, rangs_investis=9, modif_divers=0 WHERE id=224;
UPDATE character_skills SET skill_id=16, rangs_investis=4, modif_divers=2 WHERE id=225;
UPDATE character_skills SET skill_id=6, rangs_investis=4, modif_divers=2 WHERE id=226;
UPDATE character_skills SET skill_id=7, rangs_investis=5, modif_divers=2 WHERE id=227;
UPDATE character_skills SET skill_id=35, rangs_investis=7, modif_divers=0 WHERE id=396;
UPDATE character_skills SET skill_id=36, rangs_investis=7, modif_divers=0 WHERE id=397;
UPDATE character_skills SET skill_id=37, rangs_investis=7, modif_divers=0 WHERE id=398;
UPDATE character_skills SET skill_id=31, rangs_investis=7, modif_divers=0 WHERE id=399;
UPDATE character_skills SET skill_id=34, rangs_investis=7, modif_divers=0 WHERE id=400;
UPDATE character_skills SET skill_id=32, rangs_investis=7, modif_divers=0 WHERE id=401;
UPDATE character_skills SET skill_id=38, rangs_investis=7, modif_divers=0 WHERE id=402;
UPDATE character_skills SET skill_id=16, rangs_investis=7, modif_divers=0 WHERE id=403;
UPDATE character_skills SET skill_id=33, rangs_investis=7, modif_divers=0 WHERE id=404;
UPDATE character_skills SET skill_id=39, rangs_investis=7, modif_divers=0 WHERE id=405;
UPDATE character_skills SET skill_id=15, rangs_investis=5, modif_divers=0 WHERE id=407;
UPDATE character_skills SET skill_id=40, rangs_investis=5, modif_divers=0 WHERE id=408;
UPDATE character_skills SET skill_id=6, rangs_investis=4, modif_divers=0 WHERE id=409;
UPDATE character_skills SET skill_id=41, rangs_investis=10, modif_divers=0 WHERE id=410;
UPDATE character_skills SET skill_id=42, rangs_investis=12, modif_divers=0 WHERE id=411;
UPDATE character_skills SET skill_id=15, rangs_investis=11, modif_divers=0 WHERE id=412;
UPDATE character_skills SET skill_id=43, rangs_investis=8, modif_divers=0 WHERE id=413;
UPDATE character_skills SET skill_id=44, rangs_investis=7, modif_divers=0 WHERE id=414;
UPDATE character_skills SET skill_id=45, rangs_investis=2, modif_divers=0 WHERE id=415;
UPDATE character_skills SET skill_id=46, rangs_investis=0, modif_divers=4 WHERE id=416;
UPDATE character_skills SET skill_id=47, rangs_investis=0, modif_divers=2 WHERE id=417;
UPDATE character_skills SET skill_id=48, rangs_investis=12, modif_divers=0 WHERE id=418;
UPDATE character_skills SET skill_id=49, rangs_investis=2, modif_divers=4 WHERE id=419;
UPDATE character_skills SET skill_id=37, rangs_investis=14, modif_divers=0 WHERE id=431;
UPDATE character_skills SET skill_id=35, rangs_investis=6, modif_divers=0 WHERE id=432;
UPDATE character_skills SET skill_id=51, rangs_investis=13, modif_divers=0 WHERE id=433;
UPDATE character_skills SET skill_id=52, rangs_investis=10, modif_divers=0 WHERE id=434;
UPDATE character_skills SET skill_id=39, rangs_investis=2, modif_divers=0 WHERE id=435;
UPDATE character_skills SET skill_id=53, rangs_investis=14, modif_divers=0 WHERE id=436;
UPDATE character_skills SET skill_id=54, rangs_investis=8, modif_divers=0 WHERE id=437;
UPDATE character_skills SET skill_id=33, rangs_investis=8, modif_divers=0 WHERE id=438;
UPDATE character_skills SET skill_id=55, rangs_investis=10, modif_divers=0 WHERE id=439;
UPDATE character_skills SET skill_id=2, rangs_investis=16, modif_divers=0 WHERE id=440;
UPDATE character_skills SET skill_id=31, rangs_investis=8, modif_divers=10 WHERE id=441;
UPDATE character_skills SET skill_id=56, rangs_investis=8, modif_divers=0 WHERE id=442;
UPDATE character_skills SET skill_id=57, rangs_investis=8, modif_divers=0 WHERE id=443;
UPDATE character_skills SET skill_id=34, rangs_investis=14, modif_divers=0 WHERE id=444;
UPDATE character_skills SET skill_id=58, rangs_investis=8, modif_divers=0 WHERE id=445;
UPDATE character_skills SET skill_id=59, rangs_investis=8, modif_divers=0 WHERE id=446;
UPDATE character_skills SET skill_id=60, rangs_investis=3, modif_divers=0 WHERE id=447;
UPDATE character_skills SET skill_id=6, rangs_investis=5, modif_divers=0 WHERE id=448;
UPDATE character_skills SET skill_id=15, rangs_investis=4, modif_divers=0 WHERE id=449;
UPDATE character_skills SET skill_id=5, rangs_investis=11, modif_divers=0 WHERE id=450;
UPDATE character_skills SET skill_id=61, rangs_investis=2, modif_divers=0 WHERE id=451;
UPDATE character_skills SET skill_id=62, rangs_investis=4, modif_divers=0 WHERE id=452;
UPDATE character_skills SET skill_id=63, rangs_investis=10, modif_divers=0 WHERE id=453;
UPDATE character_skills SET skill_id=64, rangs_investis=10, modif_divers=0 WHERE id=454;
UPDATE character_skills SET skill_id=15, rangs_investis=6, modif_divers=0 WHERE id=455;
UPDATE character_skills SET skill_id=46, rangs_investis=3, modif_divers=0 WHERE id=456;
UPDATE character_skills SET skill_id=49, rangs_investis=5, modif_divers=0 WHERE id=457;
UPDATE character_skills SET skill_id=47, rangs_investis=3, modif_divers=0 WHERE id=458;
UPDATE character_skills SET skill_id=15, rangs_investis=11, modif_divers=0 WHERE id=459;
UPDATE character_skills SET skill_id=64, rangs_investis=11, modif_divers=0 WHERE id=460;
UPDATE character_skills SET skill_id=15, rangs_investis=19, modif_divers=0 WHERE id=461;
UPDATE character_skills SET skill_id=46, rangs_investis=10, modif_divers=0 WHERE id=462;
UPDATE character_skills SET skill_id=49, rangs_investis=9, modif_divers=0 WHERE id=463;
UPDATE character_skills SET skill_id=64, rangs_investis=19, modif_divers=0 WHERE id=464;
UPDATE character_skills SET skill_id=65, rangs_investis=19, modif_divers=0 WHERE id=465;
UPDATE character_skills SET skill_id=66, rangs_investis=10, modif_divers=0 WHERE id=466;
UPDATE character_skills SET skill_id=67, rangs_investis=15, modif_divers=0 WHERE id=467;
UPDATE character_skills SET skill_id=37, rangs_investis=10, modif_divers=8 WHERE id=468;
UPDATE character_skills SET skill_id=68, rangs_investis=5, modif_divers=0 WHERE id=469;
UPDATE character_skills SET skill_id=69, rangs_investis=15, modif_divers=0 WHERE id=470;
UPDATE character_skills SET skill_id=70, rangs_investis=5, modif_divers=0 WHERE id=471;
UPDATE character_skills SET skill_id=71, rangs_investis=10, modif_divers=0 WHERE id=472;
UPDATE character_skills SET skill_id=46, rangs_investis=10, modif_divers=10 WHERE id=473;
UPDATE character_skills SET skill_id=72, rangs_investis=15, modif_divers=17 WHERE id=474;
UPDATE character_skills SET skill_id=73, rangs_investis=15, modif_divers=0 WHERE id=475;
UPDATE character_skills SET skill_id=74, rangs_investis=15, modif_divers=0 WHERE id=476;
UPDATE character_skills SET skill_id=47, rangs_investis=10, modif_divers=0 WHERE id=477;
UPDATE character_skills SET skill_id=49, rangs_investis=10, modif_divers=10 WHERE id=478;
UPDATE character_skills SET skill_id=75, rangs_investis=10, modif_divers=0 WHERE id=479;
UPDATE character_skills SET skill_id=76, rangs_investis=10, modif_divers=0 WHERE id=480;
UPDATE character_skills SET skill_id=72, rangs_investis=6, modif_divers=10 WHERE id=481;
UPDATE character_skills SET skill_id=15, rangs_investis=19, modif_divers=0 WHERE id=482;
UPDATE character_skills SET skill_id=42, rangs_investis=19, modif_divers=0 WHERE id=483;
UPDATE character_skills SET skill_id=77, rangs_investis=18, modif_divers=0 WHERE id=484;
UPDATE character_skills SET skill_id=47, rangs_investis=0, modif_divers=2 WHERE id=485;
UPDATE character_skills SET skill_id=46, rangs_investis=2, modif_divers=2 WHERE id=486;
UPDATE character_skills SET skill_id=49, rangs_investis=2, modif_divers=2 WHERE id=487;
UPDATE character_skills SET skill_id=78, rangs_investis=6, modif_divers=0 WHERE id=488;
UPDATE character_skills SET skill_id=79, rangs_investis=13, modif_divers=4 WHERE id=489;
UPDATE character_skills SET skill_id=69, rangs_investis=7, modif_divers=2 WHERE id=490;
UPDATE character_skills SET skill_id=80, rangs_investis=8, modif_divers=4 WHERE id=491;
UPDATE character_skills SET skill_id=81, rangs_investis=3, modif_divers=4 WHERE id=492;
UPDATE character_skills SET skill_id=82, rangs_investis=5, modif_divers=2 WHERE id=493;
UPDATE character_skills SET skill_id=83, rangs_investis=1, modif_divers=4 WHERE id=494;
UPDATE character_skills SET skill_id=84, rangs_investis=8, modif_divers=-1 WHERE id=495;
UPDATE character_skills SET skill_id=17, rangs_investis=10, modif_divers=0 WHERE id=496;
UPDATE character_skills SET skill_id=37, rangs_investis=7, modif_divers=0 WHERE id=497;
UPDATE character_skills SET skill_id=85, rangs_investis=10, modif_divers=0 WHERE id=498;
UPDATE character_skills SET skill_id=86, rangs_investis=10, modif_divers=0 WHERE id=499;
UPDATE character_skills SET skill_id=15, rangs_investis=14, modif_divers=0 WHERE id=500;
UPDATE character_skills SET skill_id=6, rangs_investis=0, modif_divers=2 WHERE id=501;
UPDATE character_skills SET skill_id=2, rangs_investis=0, modif_divers=2 WHERE id=502;
UPDATE character_skills SET skill_id=66, rangs_investis=6, modif_divers=0 WHERE id=503;
UPDATE character_skills SET skill_id=37, rangs_investis=8, modif_divers=0 WHERE id=504;
UPDATE character_skills SET skill_id=68, rangs_investis=10, modif_divers=0 WHERE id=505;
UPDATE character_skills SET skill_id=69, rangs_investis=10, modif_divers=0 WHERE id=506;
UPDATE character_skills SET skill_id=70, rangs_investis=10, modif_divers=0 WHERE id=507;
UPDATE character_skills SET skill_id=87, rangs_investis=8, modif_divers=0 WHERE id=508;
UPDATE character_skills SET skill_id=46, rangs_investis=9, modif_divers=0 WHERE id=509;
UPDATE character_skills SET skill_id=72, rangs_investis=10, modif_divers=10 WHERE id=510;
UPDATE character_skills SET skill_id=73, rangs_investis=10, modif_divers=0 WHERE id=511;
UPDATE character_skills SET skill_id=74, rangs_investis=10, modif_divers=0 WHERE id=512;
UPDATE character_skills SET skill_id=47, rangs_investis=10, modif_divers=0 WHERE id=513;
UPDATE character_skills SET skill_id=49, rangs_investis=9, modif_divers=0 WHERE id=514;
UPDATE character_skills SET skill_id=88, rangs_investis=8, modif_divers=0 WHERE id=515;
UPDATE character_skills SET skill_id=75, rangs_investis=14, modif_divers=2 WHERE id=516;
UPDATE character_skills SET skill_id=76, rangs_investis=8, modif_divers=0 WHERE id=517;
UPDATE character_skills SET skill_id=89, rangs_investis=0, modif_divers=1 WHERE id=518;
UPDATE character_skills SET skill_id=90, rangs_investis=0, modif_divers=1 WHERE id=519;
UPDATE character_skills SET skill_id=91, rangs_investis=0, modif_divers=1 WHERE id=520;
UPDATE character_skills SET skill_id=15, rangs_investis=7, modif_divers=0 WHERE id=521;
UPDATE character_skills SET skill_id=92, rangs_investis=4, modif_divers=0 WHERE id=522;
UPDATE character_skills SET skill_id=93, rangs_investis=7, modif_divers=0 WHERE id=523;
UPDATE character_skills SET skill_id=94, rangs_investis=7, modif_divers=0 WHERE id=524;
UPDATE character_skills SET skill_id=95, rangs_investis=3, modif_divers=0 WHERE id=525;
UPDATE character_skills SET skill_id=2, rangs_investis=10, modif_divers=0 WHERE id=526;
UPDATE character_skills SET skill_id=31, rangs_investis=3, modif_divers=0 WHERE id=527;
UPDATE character_skills SET skill_id=4, rangs_investis=6, modif_divers=0 WHERE id=528;
UPDATE character_skills SET skill_id=34, rangs_investis=4, modif_divers=0 WHERE id=529;
UPDATE character_skills SET skill_id=62, rangs_investis=4, modif_divers=0 WHERE id=530;
UPDATE character_skills SET skill_id=96, rangs_investis=3, modif_divers=0 WHERE id=531;
UPDATE character_skills SET skill_id=101, rangs_investis=1, modif_divers=10 WHERE id=540;
UPDATE character_skills SET skill_id=72, rangs_investis=0, modif_divers=10 WHERE id=541;
UPDATE character_skills SET skill_id=102, rangs_investis=7, modif_divers=3 WHERE id=561;
UPDATE character_skills SET skill_id=17, rangs_investis=4, modif_divers=3 WHERE id=562;
UPDATE character_skills SET skill_id=37, rangs_investis=5, modif_divers=2 WHERE id=563;
UPDATE character_skills SET skill_id=109, rangs_investis=5, modif_divers=3 WHERE id=564;
UPDATE character_skills SET skill_id=39, rangs_investis=14, modif_divers=1 WHERE id=565;
UPDATE character_skills SET skill_id=53, rangs_investis=5, modif_divers=2 WHERE id=566;
UPDATE character_skills SET skill_id=33, rangs_investis=7, modif_divers=13 WHERE id=567;
UPDATE character_skills SET skill_id=110, rangs_investis=11, modif_divers=1 WHERE id=568;
UPDATE character_skills SET skill_id=2, rangs_investis=14, modif_divers=1 WHERE id=569;
UPDATE character_skills SET skill_id=31, rangs_investis=9, modif_divers=1 WHERE id=570;
UPDATE character_skills SET skill_id=56, rangs_investis=7, modif_divers=3 WHERE id=571;
UPDATE character_skills SET skill_id=5, rangs_investis=5, modif_divers=5 WHERE id=572;
UPDATE character_skills SET skill_id=111, rangs_investis=8, modif_divers=5 WHERE id=573;
UPDATE character_skills SET skill_id=57, rangs_investis=10, modif_divers=3 WHERE id=574;
UPDATE character_skills SET skill_id=34, rangs_investis=12, modif_divers=1 WHERE id=575;
UPDATE character_skills SET skill_id=112, rangs_investis=6, modif_divers=5 WHERE id=576;
UPDATE character_skills SET skill_id=113, rangs_investis=4, modif_divers=5 WHERE id=577;
UPDATE character_skills SET skill_id=6, rangs_investis=13, modif_divers=3 WHERE id=578;
UPDATE character_skills SET skill_id=114, rangs_investis=9, modif_divers=2 WHERE id=579;
UPDATE character_skills SET skill_id=59, rangs_investis=10, modif_divers=5 WHERE id=580;
UPDATE character_skills SET skill_id=122, rangs_investis=5, modif_divers=1 WHERE id=594;
UPDATE character_skills SET skill_id=54, rangs_investis=8, modif_divers=1 WHERE id=595;
UPDATE character_skills SET skill_id=123, rangs_investis=7, modif_divers=1 WHERE id=596;
UPDATE character_skills SET skill_id=124, rangs_investis=6, modif_divers=1 WHERE id=597;
UPDATE character_skills SET skill_id=125, rangs_investis=5, modif_divers=1 WHERE id=598;
UPDATE character_skills SET skill_id=64, rangs_investis=5, modif_divers=0 WHERE id=599;
UPDATE character_skills SET skill_id=126, rangs_investis=9, modif_divers=0 WHERE id=600;
UPDATE character_skills SET skill_id=127, rangs_investis=4, modif_divers=0 WHERE id=601;
UPDATE character_skills SET skill_id=63, rangs_investis=7, modif_divers=0 WHERE id=602;
UPDATE character_skills SET skill_id=128, rangs_investis=7, modif_divers=0 WHERE id=603;
UPDATE character_skills SET skill_id=15, rangs_investis=15, modif_divers=0 WHERE id=615;
UPDATE character_skills SET skill_id=48, rangs_investis=15, modif_divers=0 WHERE id=616;
UPDATE character_skills SET skill_id=135, rangs_investis=10, modif_divers=0 WHERE id=617;
UPDATE character_skills SET skill_id=136, rangs_investis=10, modif_divers=0 WHERE id=618;
UPDATE character_skills SET skill_id=137, rangs_investis=15, modif_divers=4 WHERE id=619;
UPDATE character_skills SET skill_id=15, rangs_investis=0, modif_divers=12 WHERE id=620;
UPDATE character_skills SET skill_id=87, rangs_investis=0, modif_divers=18 WHERE id=621;
UPDATE character_skills SET skill_id=138, rangs_investis=0, modif_divers=10 WHERE id=622;
UPDATE character_skills SET skill_id=140, rangs_investis=10, modif_divers=0 WHERE id=632;
UPDATE character_skills SET skill_id=42, rangs_investis=15, modif_divers=0 WHERE id=633;
UPDATE character_skills SET skill_id=106, rangs_investis=15, modif_divers=0 WHERE id=634;
UPDATE character_skills SET skill_id=107, rangs_investis=9, modif_divers=0 WHERE id=635;
UPDATE character_skills SET skill_id=93, rangs_investis=5, modif_divers=0 WHERE id=636;
UPDATE character_skills SET skill_id=141, rangs_investis=7, modif_divers=2 WHERE id=637;
UPDATE character_skills SET skill_id=77, rangs_investis=0, modif_divers=8 WHERE id=638;
UPDATE character_skills SET skill_id=48, rangs_investis=0, modif_divers=8 WHERE id=639;
UPDATE character_skills SET skill_id=75, rangs_investis=0, modif_divers=8 WHERE id=640;
UPDATE character_skills SET skill_id=142, rangs_investis=7, modif_divers=0 WHERE id=641;
UPDATE character_skills SET skill_id=143, rangs_investis=6, modif_divers=0 WHERE id=642;
UPDATE character_skills SET skill_id=144, rangs_investis=3, modif_divers=8 WHERE id=643;
UPDATE character_skills SET skill_id=48, rangs_investis=3, modif_divers=8 WHERE id=644;
UPDATE character_skills SET skill_id=75, rangs_investis=3, modif_divers=8 WHERE id=645;
UPDATE character_skills SET skill_id=67, rangs_investis=7, modif_divers=0 WHERE id=646;
UPDATE character_skills SET skill_id=141, rangs_investis=7, modif_divers=0 WHERE id=647;
UPDATE character_skills SET skill_id=145, rangs_investis=7, modif_divers=0 WHERE id=648;
UPDATE character_skills SET skill_id=87, rangs_investis=7, modif_divers=0 WHERE id=649;
UPDATE character_skills SET skill_id=77, rangs_investis=5, modif_divers=8 WHERE id=650;
UPDATE character_skills SET skill_id=46, rangs_investis=7, modif_divers=2 WHERE id=651;
UPDATE character_skills SET skill_id=146, rangs_investis=7, modif_divers=2 WHERE id=652;
UPDATE character_skills SET skill_id=74, rangs_investis=6, modif_divers=0 WHERE id=653;
UPDATE character_skills SET skill_id=48, rangs_investis=5, modif_divers=8 WHERE id=654;
UPDATE character_skills SET skill_id=49, rangs_investis=7, modif_divers=0 WHERE id=655;
UPDATE character_skills SET skill_id=88, rangs_investis=7, modif_divers=0 WHERE id=656;
UPDATE character_skills SET skill_id=75, rangs_investis=7, modif_divers=8 WHERE id=657;
UPDATE character_skills SET skill_id=71, rangs_investis=7, modif_divers=2 WHERE id=658;
UPDATE character_skills SET skill_id=142, rangs_investis=7, modif_divers=2 WHERE id=659;
UPDATE character_skills SET skill_id=72, rangs_investis=7, modif_divers=2 WHERE id=660;
UPDATE character_skills SET skill_id=147, rangs_investis=7, modif_divers=2 WHERE id=661;
UPDATE character_skills SET skill_id=66, rangs_investis=3, modif_divers=2 WHERE id=662;
UPDATE character_skills SET skill_id=148, rangs_investis=7, modif_divers=2 WHERE id=663;
UPDATE character_skills SET skill_id=49, rangs_investis=4, modif_divers=0 WHERE id=664;
UPDATE character_skills SET skill_id=47, rangs_investis=4, modif_divers=0 WHERE id=665;
UPDATE character_skills SET skill_id=46, rangs_investis=0, modif_divers=2 WHERE id=666;
UPDATE character_skills SET skill_id=47, rangs_investis=0, modif_divers=2 WHERE id=667;
UPDATE character_skills SET skill_id=49, rangs_investis=0, modif_divers=2 WHERE id=668;
UPDATE character_skills SET skill_id=72, rangs_investis=6, modif_divers=0 WHERE id=669;
UPDATE character_skills SET skill_id=87, rangs_investis=4, modif_divers=0 WHERE id=670;
UPDATE character_skills SET skill_id=46, rangs_investis=4, modif_divers=2 WHERE id=671;
UPDATE character_skills SET skill_id=49, rangs_investis=4, modif_divers=2 WHERE id=672;
UPDATE character_skills SET skill_id=149, rangs_investis=9, modif_divers=0 WHERE id=673;
UPDATE character_skills SET skill_id=37, rangs_investis=9, modif_divers=0 WHERE id=674;
UPDATE character_skills SET skill_id=141, rangs_investis=9, modif_divers=0 WHERE id=675;
UPDATE character_skills SET skill_id=70, rangs_investis=9, modif_divers=0 WHERE id=676;
UPDATE character_skills SET skill_id=140, rangs_investis=9, modif_divers=0 WHERE id=677;
UPDATE character_skills SET skill_id=150, rangs_investis=9, modif_divers=0 WHERE id=678;
UPDATE character_skills SET skill_id=151, rangs_investis=9, modif_divers=0 WHERE id=679;
UPDATE character_skills SET skill_id=46, rangs_investis=9, modif_divers=0 WHERE id=680;
UPDATE character_skills SET skill_id=152, rangs_investis=9, modif_divers=0 WHERE id=681;
UPDATE character_skills SET skill_id=47, rangs_investis=9, modif_divers=10 WHERE id=682;
UPDATE character_skills SET skill_id=146, rangs_investis=9, modif_divers=0 WHERE id=683;
UPDATE character_skills SET skill_id=49, rangs_investis=9, modif_divers=0 WHERE id=684;
UPDATE character_skills SET skill_id=87, rangs_investis=9, modif_divers=0 WHERE id=685;
UPDATE character_skills SET skill_id=128, rangs_investis=9, modif_divers=10 WHERE id=686;
UPDATE character_skills SET skill_id=46, rangs_investis=7, modif_divers=2 WHERE id=687;
UPDATE character_skills SET skill_id=49, rangs_investis=6, modif_divers=2 WHERE id=688;
UPDATE character_skills SET skill_id=47, rangs_investis=6, modif_divers=2 WHERE id=689;
UPDATE character_skills SET skill_id=153, rangs_investis=7, modif_divers=0 WHERE id=690;
UPDATE character_skills SET skill_id=142, rangs_investis=7, modif_divers=0 WHERE id=691;
UPDATE character_skills SET skill_id=15, rangs_investis=7, modif_divers=0 WHERE id=692;
UPDATE character_skills SET skill_id=143, rangs_investis=7, modif_divers=0 WHERE id=693;
UPDATE character_skills SET skill_id=64, rangs_investis=6, modif_divers=0 WHERE id=694;
UPDATE character_skills SET skill_id=87, rangs_investis=5, modif_divers=25 WHERE id=695;
UPDATE character_skills SET skill_id=154, rangs_investis=7, modif_divers=0 WHERE id=696;
UPDATE character_skills SET skill_id=71, rangs_investis=7, modif_divers=0 WHERE id=697;
UPDATE character_skills SET skill_id=155, rangs_investis=7, modif_divers=0 WHERE id=698;
UPDATE character_skills SET skill_id=72, rangs_investis=5, modif_divers=10 WHERE id=699;
UPDATE character_skills SET skill_id=63, rangs_investis=7, modif_divers=0 WHERE id=700;
UPDATE character_skills SET skill_id=156, rangs_investis=7, modif_divers=0 WHERE id=701;
UPDATE character_skills SET skill_id=76, rangs_investis=7, modif_divers=0 WHERE id=702;
UPDATE character_skills SET skill_id=128, rangs_investis=7, modif_divers=0 WHERE id=703;
UPDATE character_skills SET skill_id=15, rangs_investis=17, modif_divers=0 WHERE id=704;
UPDATE character_skills SET skill_id=21, rangs_investis=10, modif_divers=0 WHERE id=705;
UPDATE character_skills SET skill_id=157, rangs_investis=17, modif_divers=0 WHERE id=706;
UPDATE character_skills SET skill_id=33, rangs_investis=10, modif_divers=0 WHERE id=707;
UPDATE character_skills SET skill_id=34, rangs_investis=10, modif_divers=0 WHERE id=708;
UPDATE character_skills SET skill_id=20, rangs_investis=12, modif_divers=0 WHERE id=709;
UPDATE character_skills SET skill_id=42, rangs_investis=9, modif_divers=0 WHERE id=710;
UPDATE character_skills SET skill_id=141, rangs_investis=11, modif_divers=0 WHERE id=711;
UPDATE character_skills SET skill_id=158, rangs_investis=11, modif_divers=0 WHERE id=712;
UPDATE character_skills SET skill_id=46, rangs_investis=11, modif_divers=8 WHERE id=713;
UPDATE character_skills SET skill_id=159, rangs_investis=11, modif_divers=0 WHERE id=714;
UPDATE character_skills SET skill_id=47, rangs_investis=11, modif_divers=8 WHERE id=715;
UPDATE character_skills SET skill_id=146, rangs_investis=11, modif_divers=8 WHERE id=716;
UPDATE character_skills SET skill_id=48, rangs_investis=11, modif_divers=0 WHERE id=717;
UPDATE character_skills SET skill_id=49, rangs_investis=11, modif_divers=8 WHERE id=718;
UPDATE character_skills SET skill_id=128, rangs_investis=11, modif_divers=0 WHERE id=719;
UPDATE character_skills SET skill_id=20, rangs_investis=3, modif_divers=0 WHERE id=723;
UPDATE character_skills SET skill_id=15, rangs_investis=3, modif_divers=0 WHERE id=724;
UPDATE character_skills SET skill_id=3, rangs_investis=3, modif_divers=0 WHERE id=725;
UPDATE character_skills SET skill_id=160, rangs_investis=3, modif_divers=0 WHERE id=726;
UPDATE character_skills SET skill_id=33, rangs_investis=3, modif_divers=0 WHERE id=727;
UPDATE character_skills SET skill_id=22, rangs_investis=3, modif_divers=0 WHERE id=728;
UPDATE character_skills SET skill_id=79, rangs_investis=3, modif_divers=0 WHERE id=729;
UPDATE character_skills SET skill_id=80, rangs_investis=2, modif_divers=0 WHERE id=730;
UPDATE character_skills SET skill_id=161, rangs_investis=2, modif_divers=0 WHERE id=731;
UPDATE character_skills SET skill_id=25, rangs_investis=2, modif_divers=0 WHERE id=732;
UPDATE character_skills SET skill_id=157, rangs_investis=3, modif_divers=0 WHERE id=733;
UPDATE character_skills SET skill_id=34, rangs_investis=3, modif_divers=0 WHERE id=734;
UPDATE character_skills SET skill_id=2, rangs_investis=3, modif_divers=0 WHERE id=735;
UPDATE character_skills SET skill_id=15, rangs_investis=8, modif_divers=0 WHERE id=736;
UPDATE character_skills SET skill_id=20, rangs_investis=8, modif_divers=0 WHERE id=737;
UPDATE character_skills SET skill_id=162, rangs_investis=8, modif_divers=0 WHERE id=738;
UPDATE character_skills SET skill_id=22, rangs_investis=8, modif_divers=0 WHERE id=739;
UPDATE character_skills SET skill_id=17, rangs_investis=8, modif_divers=0 WHERE id=740;
UPDATE character_skills SET skill_id=157, rangs_investis=2, modif_divers=0 WHERE id=741;
UPDATE character_skills SET skill_id=2, rangs_investis=2, modif_divers=0 WHERE id=742;
UPDATE character_skills SET skill_id=15, rangs_investis=12, modif_divers=0 WHERE id=745;
UPDATE character_skills SET skill_id=164, rangs_investis=12, modif_divers=0 WHERE id=746;
UPDATE character_skills SET skill_id=3, rangs_investis=11, modif_divers=0 WHERE id=747;
UPDATE character_skills SET skill_id=6, rangs_investis=5, modif_divers=0 WHERE id=748;
UPDATE character_skills SET skill_id=27, rangs_investis=10, modif_divers=0 WHERE id=749;
UPDATE character_skills SET skill_id=165, rangs_investis=10, modif_divers=0 WHERE id=750;
UPDATE character_skills SET skill_id=166, rangs_investis=4, modif_divers=0 WHERE id=751;
UPDATE character_skills SET skill_id=167, rangs_investis=4, modif_divers=0 WHERE id=752;
UPDATE character_skills SET skill_id=62, rangs_investis=4, modif_divers=0 WHERE id=753;
UPDATE character_skills SET skill_id=25, rangs_investis=4, modif_divers=10 WHERE id=754;
UPDATE character_skills SET skill_id=168, rangs_investis=4, modif_divers=0 WHERE id=755;
UPDATE character_skills SET skill_id=169, rangs_investis=4, modif_divers=0 WHERE id=756;
UPDATE character_skills SET skill_id=59, rangs_investis=4, modif_divers=0 WHERE id=757;
UPDATE character_skills SET skill_id=39, rangs_investis=4, modif_divers=0 WHERE id=758;
UPDATE character_skills SET skill_id=5, rangs_investis=4, modif_divers=0 WHERE id=759;
UPDATE character_skills SET skill_id=170, rangs_investis=4, modif_divers=0 WHERE id=760;
UPDATE character_skills SET skill_id=34, rangs_investis=4, modif_divers=2 WHERE id=761;
UPDATE character_skills SET skill_id=6, rangs_investis=4, modif_divers=2 WHERE id=762;
UPDATE character_skills SET skill_id=31, rangs_investis=4, modif_divers=10 WHERE id=763;
UPDATE character_skills SET skill_id=61, rangs_investis=4, modif_divers=0 WHERE id=764;
UPDATE character_skills SET skill_id=25, rangs_investis=4, modif_divers=0 WHERE id=765;
UPDATE character_skills SET skill_id=2, rangs_investis=0, modif_divers=20 WHERE id=779;
UPDATE character_skills SET skill_id=6, rangs_investis=0, modif_divers=20 WHERE id=780;
UPDATE character_skills SET skill_id=175, rangs_investis=2, modif_divers=0 WHERE id=781;
UPDATE character_skills SET skill_id=102, rangs_investis=5, modif_divers=0 WHERE id=782;
UPDATE character_skills SET skill_id=39, rangs_investis=5, modif_divers=0 WHERE id=783;
UPDATE character_skills SET skill_id=2, rangs_investis=7, modif_divers=0 WHERE id=784;
UPDATE character_skills SET skill_id=37, rangs_investis=3, modif_divers=0 WHERE id=785;
UPDATE character_skills SET skill_id=176, rangs_investis=5, modif_divers=0 WHERE id=786;
UPDATE character_skills SET skill_id=53, rangs_investis=7, modif_divers=0 WHERE id=787;
UPDATE character_skills SET skill_id=54, rangs_investis=4, modif_divers=0 WHERE id=788;
UPDATE character_skills SET skill_id=33, rangs_investis=7, modif_divers=10 WHERE id=789;
UPDATE character_skills SET skill_id=31, rangs_investis=9, modif_divers=10 WHERE id=790;
UPDATE character_skills SET skill_id=56, rangs_investis=7, modif_divers=0 WHERE id=791;
UPDATE character_skills SET skill_id=5, rangs_investis=8, modif_divers=0 WHERE id=792;
UPDATE character_skills SET skill_id=8, rangs_investis=8, modif_divers=0 WHERE id=793;
UPDATE character_skills SET skill_id=27, rangs_investis=1, modif_divers=0 WHERE id=794;
UPDATE character_skills SET skill_id=177, rangs_investis=2, modif_divers=0 WHERE id=795;
UPDATE character_skills SET skill_id=53, rangs_investis=4, modif_divers=0 WHERE id=796;
UPDATE character_skills SET skill_id=4, rangs_investis=4, modif_divers=0 WHERE id=797;
UPDATE character_skills SET skill_id=37, rangs_investis=2, modif_divers=0 WHERE id=798;
UPDATE character_skills SET skill_id=60, rangs_investis=2, modif_divers=0 WHERE id=799;
UPDATE character_skills SET skill_id=4, rangs_investis=4, modif_divers=0 WHERE id=800;
UPDATE character_skills SET skill_id=34, rangs_investis=7, modif_divers=0 WHERE id=801;
UPDATE character_skills SET skill_id=178, rangs_investis=3, modif_divers=0 WHERE id=802;
UPDATE character_skills SET skill_id=111, rangs_investis=7, modif_divers=0 WHERE id=803;
UPDATE character_skills SET skill_id=34, rangs_investis=5, modif_divers=0 WHERE id=804;
UPDATE character_skills SET skill_id=20, rangs_investis=4, modif_divers=0 WHERE id=805;
UPDATE character_skills SET skill_id=179, rangs_investis=4, modif_divers=2 WHERE id=806;
UPDATE character_skills SET skill_id=180, rangs_investis=3, modif_divers=2 WHERE id=807;
UPDATE character_skills SET skill_id=15, rangs_investis=6, modif_divers=0 WHERE id=808;
UPDATE character_skills SET skill_id=162, rangs_investis=6, modif_divers=0 WHERE id=809;
UPDATE character_skills SET skill_id=181, rangs_investis=2, modif_divers=0 WHERE id=810;
UPDATE character_skills SET skill_id=15, rangs_investis=5, modif_divers=0 WHERE id=811;
UPDATE character_skills SET skill_id=2, rangs_investis=6, modif_divers=0 WHERE id=812;
UPDATE character_skills SET skill_id=182, rangs_investis=2, modif_divers=0 WHERE id=813;
UPDATE character_skills SET skill_id=183, rangs_investis=4, modif_divers=0 WHERE id=814;
UPDATE character_skills SET skill_id=183, rangs_investis=4, modif_divers=0 WHERE id=815;
UPDATE character_skills SET skill_id=8, rangs_investis=3, modif_divers=0 WHERE id=816;
UPDATE character_skills SET skill_id=160, rangs_investis=3, modif_divers=0 WHERE id=817;
UPDATE character_skills SET skill_id=6, rangs_investis=7, modif_divers=0 WHERE id=818;
UPDATE character_skills SET skill_id=6, rangs_investis=3, modif_divers=2 WHERE id=819;
UPDATE character_skills SET skill_id=160, rangs_investis=0, modif_divers=4 WHERE id=820;
UPDATE character_skills SET skill_id=79, rangs_investis=0, modif_divers=2 WHERE id=821;
UPDATE character_skills SET skill_id=80, rangs_investis=0, modif_divers=2 WHERE id=822;
UPDATE character_skills SET skill_id=184, rangs_investis=0, modif_divers=2 WHERE id=823;
UPDATE character_skills SET skill_id=6, rangs_investis=0, modif_divers=4 WHERE id=824;
UPDATE character_skills SET skill_id=2, rangs_investis=0, modif_divers=2 WHERE id=825;
UPDATE character_skills SET skill_id=8, rangs_investis=3, modif_divers=0 WHERE id=828;
UPDATE character_skills SET skill_id=185, rangs_investis=3, modif_divers=0 WHERE id=829;
UPDATE character_skills SET skill_id=25, rangs_investis=3, modif_divers=0 WHERE id=830;
UPDATE character_skills SET skill_id=186, rangs_investis=3, modif_divers=0 WHERE id=831;
UPDATE character_skills SET skill_id=187, rangs_investis=3, modif_divers=0 WHERE id=832;
UPDATE character_skills SET skill_id=22, rangs_investis=2, modif_divers=0 WHERE id=834;
UPDATE character_skills SET skill_id=20, rangs_investis=2, modif_divers=0 WHERE id=835;
UPDATE character_skills SET skill_id=162, rangs_investis=2, modif_divers=0 WHERE id=836;
UPDATE character_skills SET skill_id=6, rangs_investis=2, modif_divers=1 WHERE id=837;
UPDATE character_skills SET skill_id=2, rangs_investis=2, modif_divers=1 WHERE id=838;
UPDATE character_skills SET skill_id=34, rangs_investis=2, modif_divers=1 WHERE id=839;
UPDATE character_skills SET skill_id=15, rangs_investis=2, modif_divers=0 WHERE id=840;
UPDATE character_skills SET skill_id=111, rangs_investis=1, modif_divers=2 WHERE id=841;
UPDATE character_skills SET skill_id=188, rangs_investis=1, modif_divers=2 WHERE id=842;
UPDATE character_skills SET skill_id=5, rangs_investis=1, modif_divers=0 WHERE id=843;
UPDATE character_skills SET skill_id=189, rangs_investis=1, modif_divers=0 WHERE id=844;
UPDATE character_skills SET skill_id=25, rangs_investis=1, modif_divers=0 WHERE id=845;
UPDATE character_skills SET skill_id=8, rangs_investis=1, modif_divers=0 WHERE id=846;
UPDATE character_skills SET skill_id=6, rangs_investis=1, modif_divers=0 WHERE id=847;
UPDATE character_skills SET skill_id=34, rangs_investis=1, modif_divers=0 WHERE id=848;
UPDATE character_skills SET skill_id=2, rangs_investis=2, modif_divers=2 WHERE id=849;
UPDATE character_skills SET skill_id=56, rangs_investis=3, modif_divers=0 WHERE id=850;
UPDATE character_skills SET skill_id=5, rangs_investis=3, modif_divers=0 WHERE id=851;
UPDATE character_skills SET skill_id=190, rangs_investis=3, modif_divers=0 WHERE id=852;
UPDATE character_skills SET skill_id=160, rangs_investis=3, modif_divers=0 WHERE id=853;
UPDATE character_skills SET skill_id=8, rangs_investis=3, modif_divers=0 WHERE id=854;
UPDATE character_skills SET skill_id=6, rangs_investis=3, modif_divers=0 WHERE id=855;
UPDATE character_skills SET skill_id=33, rangs_investis=3, modif_divers=0 WHERE id=856;
UPDATE character_skills SET skill_id=102, rangs_investis=3, modif_divers=0 WHERE id=857;
UPDATE character_skills SET skill_id=191, rangs_investis=1, modif_divers=0 WHERE id=858;
UPDATE character_skills SET skill_id=96, rangs_investis=6, modif_divers=0 WHERE id=859;
UPDATE character_skills SET skill_id=177, rangs_investis=2, modif_divers=0 WHERE id=860;
UPDATE character_skills SET skill_id=2, rangs_investis=0, modif_divers=2 WHERE id=861;
UPDATE character_skills SET skill_id=34, rangs_investis=1, modif_divers=2 WHERE id=862;
UPDATE character_skills SET skill_id=6, rangs_investis=2, modif_divers=2 WHERE id=863;
UPDATE character_skills SET skill_id=2, rangs_investis=0, modif_divers=2 WHERE id=864;
UPDATE character_skills SET skill_id=34, rangs_investis=0, modif_divers=2 WHERE id=865;
UPDATE character_skills SET skill_id=6, rangs_investis=0, modif_divers=2 WHERE id=866;
UPDATE character_skills SET skill_id=2, rangs_investis=0, modif_divers=2 WHERE id=867;
UPDATE character_skills SET skill_id=5, rangs_investis=3, modif_divers=0 WHERE id=868;
UPDATE character_skills SET skill_id=3, rangs_investis=5, modif_divers=0 WHERE id=869;
UPDATE character_skills SET skill_id=41, rangs_investis=2, modif_divers=0 WHERE id=870;
UPDATE character_skills SET skill_id=181, rangs_investis=2, modif_divers=0 WHERE id=871;
UPDATE character_skills SET skill_id=15, rangs_investis=1, modif_divers=0 WHERE id=872;
UPDATE character_skills SET skill_id=15, rangs_investis=11, modif_divers=0 WHERE id=901;
UPDATE character_skills SET skill_id=5, rangs_investis=3, modif_divers=0 WHERE id=902;
UPDATE character_skills SET skill_id=25, rangs_investis=3, modif_divers=0 WHERE id=903;
UPDATE character_skills SET skill_id=17, rangs_investis=11, modif_divers=0 WHERE id=904;
UPDATE character_skills SET skill_id=18, rangs_investis=11, modif_divers=0 WHERE id=905;
UPDATE character_skills SET skill_id=97, rangs_investis=11, modif_divers=0 WHERE id=906;
UPDATE character_skills SET skill_id=22, rangs_investis=17, modif_divers=0 WHERE id=907;
UPDATE character_skills SET skill_id=171, rangs_investis=11, modif_divers=0 WHERE id=908;
UPDATE character_skills SET skill_id=27, rangs_investis=11, modif_divers=0 WHERE id=909;
UPDATE character_skills SET skill_id=59, rangs_investis=2, modif_divers=0 WHERE id=910;
UPDATE character_skills SET skill_id=173, rangs_investis=11, modif_divers=0 WHERE id=911;
UPDATE character_skills SET skill_id=172, rangs_investis=11, modif_divers=0 WHERE id=912;
UPDATE character_skills SET skill_id=174, rangs_investis=11, modif_divers=0 WHERE id=913;
UPDATE character_skills SET skill_id=31, rangs_investis=8, modif_divers=0 WHERE id=914;
UPDATE character_skills SET skill_id=34, rangs_investis=6, modif_divers=0 WHERE id=915;
UPDATE character_skills SET skill_id=8, rangs_investis=4, modif_divers=2 WHERE id=916;
UPDATE character_skills SET skill_id=33, rangs_investis=8, modif_divers=0 WHERE id=917;
UPDATE character_skills SET skill_id=102, rangs_investis=5, modif_divers=2 WHERE id=918;
UPDATE character_skills SET skill_id=118, rangs_investis=8, modif_divers=0 WHERE id=919;
UPDATE character_skills SET skill_id=117, rangs_investis=8, modif_divers=0 WHERE id=920;
UPDATE character_skills SET skill_id=2, rangs_investis=9, modif_divers=0 WHERE id=921;
UPDATE character_skills SET skill_id=120, rangs_investis=5, modif_divers=0 WHERE id=922;
UPDATE character_skills SET skill_id=115, rangs_investis=6, modif_divers=0 WHERE id=923;
UPDATE character_skills SET skill_id=116, rangs_investis=10, modif_divers=0 WHERE id=924;
UPDATE character_skills SET skill_id=119, rangs_investis=10, modif_divers=0 WHERE id=925;
UPDATE character_skills SET skill_id=41, rangs_investis=8, modif_divers=0 WHERE id=926;
UPDATE character_skills SET skill_id=96, rangs_investis=10, modif_divers=0 WHERE id=927;
UPDATE character_skills SET skill_id=35, rangs_investis=17, modif_divers=0 WHERE id=964;
UPDATE character_skills SET skill_id=31, rangs_investis=17, modif_divers=0 WHERE id=965;
UPDATE character_skills SET skill_id=111, rangs_investis=17, modif_divers=0 WHERE id=966;
UPDATE character_skills SET skill_id=34, rangs_investis=17, modif_divers=0 WHERE id=967;
UPDATE character_skills SET skill_id=33, rangs_investis=17, modif_divers=10 WHERE id=968;
UPDATE character_skills SET skill_id=2, rangs_investis=17, modif_divers=0 WHERE id=969;
UPDATE character_skills SET skill_id=6, rangs_investis=17, modif_divers=0 WHERE id=970;
UPDATE character_skills SET skill_id=139, rangs_investis=7, modif_divers=0 WHERE id=971;
UPDATE character_skills SET skill_id=59, rangs_investis=17, modif_divers=0 WHERE id=972;
UPDATE character_skills SET skill_id=15, rangs_investis=19, modif_divers=0 WHERE id=973;
UPDATE character_skills SET skill_id=42, rangs_investis=15, modif_divers=0 WHERE id=974;
UPDATE character_skills SET skill_id=87, rangs_investis=0, modif_divers=15 WHERE id=975;
UPDATE character_skills SET skill_id=104, rangs_investis=19, modif_divers=0 WHERE id=976;
UPDATE character_skills SET skill_id=105, rangs_investis=15, modif_divers=0 WHERE id=977;
UPDATE character_skills SET skill_id=121, rangs_investis=11, modif_divers=0 WHERE id=978;
UPDATE character_skills SET skill_id=77, rangs_investis=19, modif_divers=0 WHERE id=979;
UPDATE character_skills SET skill_id=46, rangs_investis=7, modif_divers=0 WHERE id=980;
UPDATE character_skills SET skill_id=72, rangs_investis=6, modif_divers=10 WHERE id=981;
UPDATE character_skills SET skill_id=108, rangs_investis=10, modif_divers=0 WHERE id=982;
UPDATE character_skills SET skill_id=106, rangs_investis=10, modif_divers=0 WHERE id=983;
UPDATE character_skills SET skill_id=47, rangs_investis=6, modif_divers=0 WHERE id=984;
UPDATE character_skills SET skill_id=48, rangs_investis=19, modif_divers=0 WHERE id=985;
UPDATE character_skills SET skill_id=107, rangs_investis=19, modif_divers=0 WHERE id=986;
UPDATE character_skills SET skill_id=49, rangs_investis=6, modif_divers=0 WHERE id=987;
UPDATE character_skills SET skill_id=15, rangs_investis=9, modif_divers=0 WHERE id=1074;
UPDATE character_skills SET skill_id=10, rangs_investis=9, modif_divers=0 WHERE id=1075;
UPDATE character_skills SET skill_id=12, rangs_investis=9, modif_divers=0 WHERE id=1076;
UPDATE character_skills SET skill_id=14, rangs_investis=9, modif_divers=0 WHERE id=1077;
UPDATE character_skills SET skill_id=13, rangs_investis=9, modif_divers=0 WHERE id=1078;
UPDATE character_skills SET skill_id=56, rangs_investis=11, modif_divers=0 WHERE id=1093;
UPDATE character_skills SET skill_id=57, rangs_investis=12, modif_divers=0 WHERE id=1094;
UPDATE character_skills SET skill_id=8, rangs_investis=7, modif_divers=0 WHERE id=1095;
UPDATE character_skills SET skill_id=33, rangs_investis=12, modif_divers=0 WHERE id=1096;
UPDATE character_skills SET skill_id=102, rangs_investis=11, modif_divers=0 WHERE id=1097;
UPDATE character_skills SET skill_id=6, rangs_investis=12, modif_divers=0 WHERE id=1098;
UPDATE character_skills SET skill_id=103, rangs_investis=4, modif_divers=0 WHERE id=1099;
UPDATE character_skills SET skill_id=98, rangs_investis=10, modif_divers=0 WHERE id=1100;
UPDATE character_skills SET skill_id=25, rangs_investis=5, modif_divers=0 WHERE id=1101;
UPDATE character_skills SET skill_id=97, rangs_investis=10, modif_divers=0 WHERE id=1102;
UPDATE character_skills SET skill_id=99, rangs_investis=5, modif_divers=0 WHERE id=1103;
UPDATE character_skills SET skill_id=100, rangs_investis=5, modif_divers=0 WHERE id=1104;
UPDATE character_skills SET skill_id=41, rangs_investis=5, modif_divers=0 WHERE id=1105;
UPDATE character_skills SET skill_id=96, rangs_investis=5, modif_divers=0 WHERE id=1106;
UPDATE character_skills SET skill_id=62, rangs_investis=10, modif_divers=0 WHERE id=1107;
UPDATE character_skills SET skill_id=3, rangs_investis=2, modif_divers=0 WHERE id=1144;
UPDATE character_skills SET skill_id=4, rangs_investis=4, modif_divers=0 WHERE id=1145;
UPDATE character_skills SET skill_id=5, rangs_investis=3, modif_divers=0 WHERE id=1146;
UPDATE character_skills SET skill_id=34, rangs_investis=4, modif_divers=0 WHERE id=1147;
UPDATE character_skills SET skill_id=8, rangs_investis=4, modif_divers=0 WHERE id=1148;
UPDATE character_skills SET skill_id=9, rangs_investis=3, modif_divers=0 WHERE id=1149;
UPDATE character_skills SET skill_id=1, rangs_investis=2, modif_divers=0 WHERE id=1150;
UPDATE character_skills SET skill_id=2, rangs_investis=6, modif_divers=2 WHERE id=1151;
UPDATE character_skills SET skill_id=6, rangs_investis=5, modif_divers=2 WHERE id=1152;
UPDATE character_skills SET skill_id=15, rangs_investis=9, modif_divers=0 WHERE id=1157;
UPDATE character_skills SET skill_id=10, rangs_investis=9, modif_divers=0 WHERE id=1158;
UPDATE character_skills SET skill_id=14, rangs_investis=9, modif_divers=0 WHERE id=1159;
UPDATE character_skills SET skill_id=13, rangs_investis=9, modif_divers=0 WHERE id=1160;
UPDATE character_skills SET skill_id=15, rangs_investis=16, modif_divers=1 WHERE id=1174;
UPDATE character_skills SET skill_id=25, rangs_investis=4, modif_divers=1 WHERE id=1175;
UPDATE character_skills SET skill_id=163, rangs_investis=5, modif_divers=0 WHERE id=1176;
UPDATE character_skills SET skill_id=97, rangs_investis=7, modif_divers=1 WHERE id=1177;
UPDATE character_skills SET skill_id=132, rangs_investis=9, modif_divers=1 WHERE id=1178;
UPDATE character_skills SET skill_id=20, rangs_investis=17, modif_divers=1 WHERE id=1179;
UPDATE character_skills SET skill_id=21, rangs_investis=4, modif_divers=1 WHERE id=1180;
UPDATE character_skills SET skill_id=129, rangs_investis=15, modif_divers=1 WHERE id=1181;
UPDATE character_skills SET skill_id=131, rangs_investis=8, modif_divers=1 WHERE id=1182;
UPDATE character_skills SET skill_id=130, rangs_investis=16, modif_divers=1 WHERE id=1183;
UPDATE character_skills SET skill_id=133, rangs_investis=12, modif_divers=1 WHERE id=1184;
UPDATE character_skills SET skill_id=134, rangs_investis=7, modif_divers=0 WHERE id=1185;
UPDATE character_skills SET skill_id=28, rangs_investis=5, modif_divers=0 WHERE id=1186;
UPDATE character_skills SET skill_id=15, rangs_investis=15, modif_divers=0 WHERE id=1215;
UPDATE character_skills SET skill_id=25, rangs_investis=5, modif_divers=0 WHERE id=1216;
UPDATE character_skills SET skill_id=17, rangs_investis=11, modif_divers=0 WHERE id=1217;
UPDATE character_skills SET skill_id=18, rangs_investis=4, modif_divers=0 WHERE id=1218;
UPDATE character_skills SET skill_id=19, rangs_investis=11, modif_divers=0 WHERE id=1219;
UPDATE character_skills SET skill_id=23, rangs_investis=11, modif_divers=0 WHERE id=1220;
UPDATE character_skills SET skill_id=20, rangs_investis=10, modif_divers=0 WHERE id=1221;
UPDATE character_skills SET skill_id=21, rangs_investis=11, modif_divers=0 WHERE id=1222;
UPDATE character_skills SET skill_id=22, rangs_investis=11, modif_divers=0 WHERE id=1223;
UPDATE character_skills SET skill_id=26, rangs_investis=11, modif_divers=0 WHERE id=1224;
UPDATE character_skills SET skill_id=27, rangs_investis=11, modif_divers=0 WHERE id=1225;
UPDATE character_skills SET skill_id=28, rangs_investis=5, modif_divers=0 WHERE id=1226;
UPDATE character_skills SET skill_id=29, rangs_investis=10, modif_divers=0 WHERE id=1227;
UPDATE character_skills SET skill_id=24, rangs_investis=11, modif_divers=0 WHERE id=1228;

-- 3. races
UPDATE races SET nom='Elfe', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=2, bonus_con=-2, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=true WHERE id=1;
UPDATE races SET nom='Humain', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=2;
UPDATE races SET nom='Demi-Elfe', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=true WHERE id=3;
UPDATE races SET nom='Nain', taille='Moyenne', deplacement_base=6, bonus_for=0, bonus_dex=0, bonus_con=2, bonus_int=0, bonus_sag=0, bonus_cha=-2, vision_nocturne=true WHERE id=4;
UPDATE races SET nom='Halfelin', taille='Petite', deplacement_base=6, bonus_for=-2, bonus_dex=2, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=5;
UPDATE races SET nom='Gnome', taille='Petite', deplacement_base=6, bonus_for=-2, bonus_dex=0, bonus_con=2, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=true WHERE id=6;
UPDATE races SET nom='Demi-Orque', taille='Moyenne', deplacement_base=9, bonus_for=2, bonus_dex=0, bonus_con=0, bonus_int=-2, bonus_sag=0, bonus_cha=-2, vision_nocturne=true WHERE id=7;
UPDATE races SET nom='Illithid', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=8;
UPDATE races SET nom='Petite-gens', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=11;
UPDATE races SET nom='Bariaure', taille='Moyenne', deplacement_base=9, bonus_for=0, bonus_dex=0, bonus_con=0, bonus_int=0, bonus_sag=0, bonus_cha=0, vision_nocturne=false WHERE id=12;

-- 4. racial_features : retirer ceux ajoutes a Petite-gens (id 11)
DELETE FROM racial_features WHERE race_id=11 AND id NOT IN (0);

-- etat d origine : 191 skills, 510 liens, 10 races, 40 traits raciaux