import type { FeatDef } from './feats'

// Dons issus des suppléments D&D 3.5 :
// [CD] Codex Divin · [CP] Codex Profane · [MN] Les Maîtres de la Nature · [RO] Les Royaumes Oubliés
// La source est indiquée à la fin de chaque description.

export const FEATS_SUPPLEMENTS: FeatDef[] = [
  // ── CODEX DIVIN — généraux ──
  { nom: 'Alignement renforcé', categorie: 'Général', description: '+1 au DD de sauvegarde des sorts du registre d\'alignement choisi (Bien, Chaos, Loi ou Mal). [Codex Divin]', prerequis: ['Alignement choisi'] },
  { nom: 'Amélioration de la magie curative', categorie: 'Général', description: 'Les sorts de guérison rendent +2 pv par niveau de sort. [Codex Divin]', prerequis: ['4 rangs Premiers secours'] },
  { nom: 'Blessure spontanée', categorie: 'Divin', description: 'Convertit spontanément un sort préparé en sort de blessure (mod SAG fois/jour). [Codex Divin]', prerequis: ['SAG13', '4 rangs Connaissances (religion)', 'alignement non bon'] },
  { nom: 'Convocation spontanée', categorie: 'Divin', description: 'Convertit spontanément un sort préparé en convocation d\'alliés naturels (mod SAG fois/jour). [Codex Divin]', prerequis: ['SAG13', '4 rangs Connaissances (nature)', 'alignement à composante neutre'] },
  { nom: 'Disciple profane', categorie: 'Magie', description: 'Ajoute les sorts d\'un domaine de son dieu à sa liste de sorts profanes (1 sort de domaine par niveau et par jour, DD basé sur la SAG). [Codex Divin]', prerequis: ['4 rangs Art de la magie', '4 rangs Connaissances (religion)', 'sorts profanes'] },
  { nom: 'Domaine de prédilection', categorie: 'Divin', description: '+1 au niveau de lanceur pour les sorts lancés en tant que sorts du domaine choisi. [Codex Divin]', prerequis: ['Accès au domaine choisi'] },
  { nom: 'Extension de renvoi', categorie: 'Divin', description: 'Le jet d\'efficacité de renvoi des morts-vivants est multiplié par 1,5. [Codex Divin]', prerequis: ['Renvoi ou intimidation des morts-vivants'] },
  { nom: 'Lanceur de sorts polyvalent', categorie: 'Magie', description: '+4 au niveau de lanceur de sorts (sans dépasser son niveau global). [Codex Divin / Codex Profane]', prerequis: ['4 rangs Art de la magie'] },
  { nom: 'Renvoi rapide', categorie: 'Divin', description: 'Renvoie ou intimide les morts-vivants par une action libre. [Codex Divin]', prerequis: ['Renvoi ou intimidation des morts-vivants'] },
  { nom: 'Science du châtiment', categorie: 'Divin', description: 'Le châtiment obtient un alignement (ignore la RD correspondante) et inflige +1d6 dégâts. [Codex Divin]', prerequis: ['CHA13', 'Pouvoir de châtiment'] },
  { nom: 'Soins spontanés', categorie: 'Divin', description: 'Convertit spontanément un sort préparé en sort de soins (mod SAG fois/jour). [Codex Divin]', prerequis: ['SAG13', '4 rangs Connaissances (religion)', 'alignement non mauvais'] },
  { nom: 'Vraie foi', categorie: 'Général', description: '+3 sur un jet de sauvegarde 1 fois/jour ; permet d\'utiliser les reliques divines. [Codex Divin]', prerequis: ['Vénérer une divinité (alignements à 1 cran max)'] },
  // ── CODEX DIVIN — divins ──
  { nom: 'Armes glorieuses', categorie: 'Divin', description: '1 renvoi dépensé : les armes de mêlée des alliés (18 m) deviennent bonnes ou mauvaises (ignorent la RD) 1 round. [Codex Divin]', prerequis: ['Renvoi ou intimidation des morts-vivants'] },
  { nom: 'Châtiment des élémentaires', categorie: 'Divin', description: '1 renvoi dépensé : une attaque de mêlée contre un élémentaire du sous-type affecté inflige + niveau de prêtre en dégâts. [Codex Divin]', prerequis: ['Renvoi d\'un type d\'élémentaires'] },
  { nom: 'Disciple du soleil', categorie: 'Divin', description: '2 renvois dépensés : les morts-vivants affectés sont détruits plutôt que repoussés. [Codex Divin]', prerequis: ['Renvoi des morts-vivants', 'alignement bon'] },
  { nom: 'Guérison des élémentaires', categorie: 'Divin', description: '1 renvoi dépensé : soigne les élémentaires du sous-type affecté. [Codex Divin]', prerequis: ['Intimidation d\'un type d\'élémentaires'] },
  { nom: 'Guérison sainte', categorie: 'Divin', description: '1 renvoi dépensé : confère guérison accélérée 3. [Codex Divin]', prerequis: ['8 rangs Premiers secours', 'Renvoi des morts-vivants'] },
  { nom: 'Métamagie divine', categorie: 'Divin', description: 'Dépense des renvois pour appliquer un don de métamagie sans hausser le niveau du sort. [Codex Divin]', prerequis: ['Renvoi ou intimidation des morts-vivants'] },
  { nom: 'Puissance magique divine', categorie: 'Divin', description: 'Dépense des renvois pour augmenter son niveau de lanceur de sorts. [Codex Divin]', prerequis: ['Renvoi ou intimidation', 'sorts divins de 1er niveau'] },
  { nom: 'Renforcement malfaisant', categorie: 'Divin', description: '1 renvoi : les sorts de blessure lancés à proximité sont maximisés 1 round. [Codex Divin]', prerequis: ['Intimidation des morts-vivants'] },
  { nom: 'Renforcement saint', categorie: 'Divin', description: '1 renvoi : les sorts de soins lancés à proximité sont maximisés 1 round. [Codex Divin]', prerequis: ['Renvoi des morts-vivants'] },
  { nom: 'Spontanéité de domaine', categorie: 'Divin', description: '1 renvoi dépensé : lance spontanément un sort du domaine choisi. [Codex Divin]', prerequis: ['Renvoi ou intimidation', 'accès au domaine choisi'] },
  // ── CODEX DIVIN — création et métamagie ──
  { nom: 'Sanctification de reliques', categorie: 'Magie', description: 'Permet de créer des reliques (objets magiques liés à une divinité). [Codex Divin]', prerequis: ['Un autre don de création d\'objets'] },
  { nom: 'Contact magique à distance', categorie: 'Métamagie', description: 'Un sort de contact devient un rayon de 9 m de portée (emplacement +2 niveaux). [Codex Divin]' },
  { nom: 'Incantation accélérée', categorie: 'Métamagie', description: 'Réduit les temps d\'incantation particulièrement longs. [Codex Divin]' },
  { nom: 'Sort consacré', categorie: 'Métamagie', description: 'Le sort obtient le registre du Bien. [Codex Divin]', prerequis: ['Alignement bon'] },
  { nom: 'Sort corrompu', categorie: 'Métamagie', description: 'Le sort obtient le registre du Mal. [Codex Divin]', prerequis: ['Alignement mauvais'] },
  { nom: 'Sort transdimensionnel', categorie: 'Métamagie', description: 'Le sort affecte aussi les créatures intangibles, éthérées ou d\'ombre. [Codex Divin / Codex Profane]' },
  // ── CODEX DIVIN — forme animale ──
  { nom: 'Ailes de l\'aigle', categorie: 'Général', description: '1 utilisation de forme animale : des ailes poussent 1 h (vol 18 m). [Codex Divin]', prerequis: ['Forme animale'] },
  { nom: 'Bond du lion', categorie: 'Général', description: '1 utilisation de forme animale : attaque à outrance à la fin d\'une charge. [Codex Divin]', prerequis: ['Forme animale'] },
  { nom: 'Course du guépard', categorie: 'Général', description: '1 utilisation : vitesse au sol 15 m pendant 1 h, un sprint ×10 en charge. [Codex Divin]', prerequis: ['Forme animale'] },
  { nom: 'Férocité du sanglier', categorie: 'Général', description: '1 utilisation : continue à se battre à 0 pv ou moins. [Codex Divin]', prerequis: ['Forme animale'] },
  { nom: 'Forme animale accélérée', categorie: 'Général', description: 'La transformation en forme animale devient une action de mouvement. [Codex Divin / Maîtres de la Nature]', prerequis: ['DEX13', 'Forme animale'] },
  { nom: 'Formes animales supplémentaires', categorie: 'Général', description: '+2 utilisations quotidiennes de forme animale. [Codex Divin / Maîtres de la Nature]', prerequis: ['Forme animale'] },
  { nom: 'Griffes du grizzly', categorie: 'Général', description: '1 utilisation : griffes pendant 1 h. [Codex Divin]', prerequis: ['Forme animale'] },
  { nom: 'Impassibilité du chêne', categorie: 'Général', description: '1 utilisation : immunités des plantes. [Codex Divin]', prerequis: ['Forme animale (plantes)'] },
  { nom: 'Nage du poisson', categorie: 'Général', description: '1 utilisation : branchies pendant 1 h. [Codex Divin]', prerequis: ['Forme animale'] },
  { nom: 'Rage du glouton', categorie: 'Général', description: 'Peut entrer en rage lorsqu\'il est blessé. [Codex Divin]', prerequis: ['Forme animale'] },
  { nom: 'Résilience de l\'éléphant', categorie: 'Général', description: '1 utilisation : armure naturelle +7 pendant 10 minutes. [Codex Divin]', prerequis: ['Forme animale (taille G)'] },
  { nom: 'Venin du serpent', categorie: 'Général', description: '1 utilisation : morsure venimeuse pendant 1 minute. [Codex Divin]', prerequis: ['Forme animale'] },

  // ── CODEX PROFANE — généraux ──
  { nom: 'Âme du nord', categorie: 'Magie', description: 'Contact glacial, rayon de givre et résistance 1×/jour (pouvoirs magiques innés). [Codex Profane]' },
  { nom: 'Communicateur', categorie: 'Magie', description: 'Compréhension des langages, message et signature magique 1×/jour. [Codex Profane]' },
  { nom: 'Coup de baguette', categorie: 'Magie', description: 'Attaque de contact avec une baguette : 1d6 dégâts et vise la cible avec un sort. [Codex Profane]', prerequis: ['4 rangs Utilisation d\'objets magiques'] },
  { nom: 'Emplacement de sort supplémentaire', categorie: 'Magie', description: 'Un emplacement de sort de niveau inférieur au maximum accessible. Cumulable. [Codex Profane]', prerequis: ['Niveau 4 de lanceur'] },
  { nom: 'Invocation supplémentaire', categorie: 'Magie', description: 'Apprend une invocation de sorcier supplémentaire. [Codex Profane]', prerequis: ['Invocations mineures'] },
  { nom: 'Lanceur de sorts de guerre', categorie: 'Magie', description: 'Porte une armure d\'une catégorie plus lourde sans risque d\'échec des sorts profanes. [Codex Profane]' },
  { nom: 'Main magique', categorie: 'Magie', description: 'Disque flottant de Tenser, manipulation à distance et ouverture/fermeture 1×/jour. [Codex Profane]' },
  { nom: 'Maîtrise de la magie profane', categorie: 'Magie', description: 'Permet de faire 10 aux tests de niveau de lanceur de sorts. [Codex Profane]' },
  { nom: 'Maniement de double baguette', categorie: 'Magie', description: 'Active une seconde baguette en dépensant 2 charges supplémentaires. [Codex Profane]', prerequis: ['Combat à deux armes', 'Création de baguettes'] },
  { nom: 'Manieur de baguettes intrépide', categorie: 'Magie', description: 'Augmente le niveau de lanceur d\'une baguette (1 charge de plus). [Codex Profane]', prerequis: ['1 rang Utilisation d\'objets magiques'] },
  { nom: 'Nécropolitain', categorie: 'Magie', description: 'Fatigue, frayeur et son imaginaire 1×/jour. [Codex Profane]', prerequis: ['4 rangs Connaissances (mystères)'] },
  { nom: 'Obtention de familier', categorie: 'Magie', description: 'Confère un familier comme un ensorceleur ou un magicien. [Codex Profane]', prerequis: ['Niveau 3 de lanceur profane'] },
  { nom: 'Perspicace', categorie: 'Magie', description: 'Détection de la magie, détection des passages secrets et lecture de la magie 1×/jour. [Codex Profane]' },
  { nom: 'Pouvoir magique amélioré', categorie: 'Magie', description: 'Utilise un pouvoir magique à un niveau supérieur (+2 niveaux de sort équivalent) 3×/jour. [Codex Profane]', prerequis: ['Pouvoir magique au niveau 6+'] },
  { nom: 'Protection profane', categorie: 'Magie', description: '+3 aux JS contre les sorts de l\'école choisie. [Codex Profane]', prerequis: ['École renforcée'] },
  { nom: 'Quintessence des pouvoirs magiques', categorie: 'Magie', description: 'Variables numériques d\'un pouvoir magique maximisées 3×/jour. [Codex Profane]', prerequis: ['Pouvoir magique au niveau 6+'] },
  { nom: 'Résistance à la protection magique', categorie: 'Combat', description: 'Une attaque de mêlée ignore et dissipe les bonus magiques à la CA (−4 niveau de lanceur). [Codex Profane]', prerequis: ['CON13', 'Tueur de mages'] },
  { nom: 'Résistance au camouflage magique', categorie: 'Combat', description: 'Ignore les chances de rater des sorts (flou, invisibilité, ténèbres…) (−4 niveau de lanceur). [Codex Profane]', prerequis: ['CON13', 'Combat en aveugle', 'Tueur de mages'] },
  { nom: 'Secret magique supplémentaire', categorie: 'Magie', description: 'Un sort connu est modifié à jamais par Extension de durée/portée, Incantation statique ou silencieuse. [Codex Profane]' },
  { nom: 'Sort inné', categorie: 'Métamagie', description: 'Lance un sort choisi comme un pouvoir magique 1×/round (emplacement +8 niveaux mobilisé à jamais). [Codex Profane / Royaumes Oubliés]', prerequis: ['Incantation rapide', 'Incantation silencieuse', 'Incantation statique'] },
  { nom: 'Spécialisation magique à distance', categorie: 'Magie', description: '+2 aux dégâts des sorts à distance. [Codex Profane]', prerequis: ['Arme de prédilection (sort à distance)', 'Niveau 4 de lanceur'] },
  { nom: 'Spécialisation magique de contact', categorie: 'Magie', description: '+2 aux dégâts des sorts de contact. [Codex Profane]', prerequis: ['Arme de prédilection (sort de contact)', 'Niveau 4 de lanceur'] },
  { nom: 'Spectre de la nuit', categorie: 'Magie', description: 'Lumières dansantes, prestidigitation et serviteur invisible 1×/jour. [Codex Profane]' },
  { nom: 'Tueur de mages', categorie: 'Combat', description: '+1 aux jets de Volonté ; les lanceurs adjacents ne peuvent pas lancer sur la défensive (−4 niveau de lanceur). [Codex Profane]', prerequis: ['2 rangs Art de la magie', 'BBA+3'] },
  { nom: 'Esprit gardien', categorie: 'Magie', description: 'Rejoue l\'initiative 2×/jour et un jet de sauvegarde 1×/jour. [Codex Profane]' },
  { nom: 'Magie affilée supérieure', categorie: 'Magie', description: '+1 en magie affilée, +1 par 4 niveaux de mage de bataille. [Codex Profane]' },
  { nom: 'Préparation profane', categorie: 'Magie', description: 'Un barde ou ensorceleur prépare à l\'avance des sorts avec métamagie sans allonger l\'incantation. [Codex Profane / Royaumes Oubliés]', prerequis: ['Sorts profanes sans préparation'] },
  { nom: 'Création de sorts de prévoyance', categorie: 'Magie', description: 'Fixe un sort et ses conditions de déclenchement à une créature. [Codex Profane]', prerequis: ['Niveau 11 de lanceur'] },
  { nom: 'Science du critique (sorts)', categorie: 'Magie', description: 'Zone de critique des sorts armés (contact ou distance) doublée. [Codex Profane]' },
  // ── CODEX PROFANE — draconiques ──
  { nom: 'Héritage draconique', categorie: 'Magie', description: 'Compétence de classe draconique + bonus aux JS contre paralysie et sommeil. [Codex Profane]', prerequis: ['Ensorceleur niveau 1'] },
  { nom: 'Griffes draconiques', categorie: 'Magie', description: 'Griffes + attaque de griffes rapide en lançant un sort. [Codex Profane]', prerequis: ['Héritage draconique'] },
  { nom: 'Legs draconique', categorie: 'Magie', description: 'Ajoute des sorts à sa liste de sorts connus. [Codex Profane]', prerequis: ['Quatre dons draconiques'] },
  { nom: 'Peau draconique', categorie: 'Magie', description: 'Armure naturelle +1. [Codex Profane]', prerequis: ['Héritage draconique'] },
  { nom: 'Présence draconique', categorie: 'Magie', description: 'Secoue les adversaires de moins de DV (3 m, Volonté annule) en jetant un sort. [Codex Profane]', prerequis: ['Héritage draconique'] },
  { nom: 'Puissance draconique', categorie: 'Magie', description: '+1 niveau de lanceur et DD des sorts du registre de l\'héritage. [Codex Profane]', prerequis: ['Héritage draconique'] },
  { nom: 'Résistance draconique', categorie: 'Magie', description: 'Résistance à l\'énergie de l\'héritage = 3 × nombre de dons draconiques. [Codex Profane]', prerequis: ['Héritage draconique'] },
  { nom: 'Souffle draconique', categorie: 'Magie', description: 'Convertit de l\'énergie magique en souffle de dragon. [Codex Profane]', prerequis: ['Héritage draconique'] },
  { nom: 'Vol draconique', categorie: 'Magie', description: 'Vole le reste du round après avoir lancé un sort. [Codex Profane]', prerequis: ['Héritage draconique'] },
  // ── CODEX PROFANE — métamagie ──
  { nom: 'Ajout d\'énergie destructive', categorie: 'Métamagie', description: 'Ajoute un second type d\'énergie en quantité égale (emplacement +4 niveaux). [Codex Profane]', prerequis: ['Substitution d\'énergie destructive'] },
  { nom: 'Altération de zone d\'effet', categorie: 'Métamagie', description: 'Change la forme de la zone du sort (+1 niveau). [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Connaissances occultes de Moil', categorie: 'Métamagie', description: 'Sorts de Nécromancie : +1d6 énergie négative par 2 niveaux de sort (os runique sacrifié). [Codex Profane]', prerequis: ['École renforcée (Nécromancie)', 'Niveau 7 de lanceur'] },
  { nom: 'Coordination de sort', categorie: 'Métamagie', description: 'Bonus au DD et aux tests de niveau des sorts lancés conjointement avec d\'autres lanceurs. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Dédoublement de rayon', categorie: 'Métamagie', description: 'Les sorts à rayon affectent une cible supplémentaire. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Démultiplication de sort', categorie: 'Métamagie', description: 'Redirige les sorts pour affecter des cibles secondaires. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Enfant des trois tonnerres', categorie: 'Métamagie', description: 'Les sorts d\'électricité ou de son infligent les deux types de dégâts. [Codex Profane]', prerequis: ['4 rangs Connaissances (nature)', 'Substitution d\'énergie destructive (électricité)'] },
  { nom: 'Extension d\'effet soudaine', categorie: 'Métamagie', description: '+50 % aux variables numériques sans préparation, 1×/jour. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Extension de durée soudaine', categorie: 'Métamagie', description: 'Double la durée d\'un sort sans préparation, 1×/jour. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Extension de zone d\'effet soudaine', categorie: 'Métamagie', description: '+50 % à la zone d\'effet sans préparation, 1×/jour. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Incantation rapide soudaine', categorie: 'Métamagie', description: 'Lance un sort en action rapide sans préparation, 1×/jour. [Codex Profane]', prerequis: ['Extensions soudaines', 'Incantations soudaines'] },
  { nom: 'Incantation silencieuse soudaine', categorie: 'Métamagie', description: 'Lance sans composantes verbales, sans préparation, 1×/jour. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Incantation statique soudaine', categorie: 'Métamagie', description: 'Lance sans composantes gestuelles, sans préparation, 1×/jour. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Quintessence des sorts soudaine', categorie: 'Métamagie', description: 'Variables d\'un sort maximisées sans préparation, 1×/jour. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Répétition de sort', categorie: 'Métamagie', description: 'Le sort est automatiquement relancé au round suivant (+3 niveaux). [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Retardement de sort', categorie: 'Métamagie', description: 'Les effets du sort sont retardés de 1 à 5 rounds (+3 niveaux). [Codex Profane / Royaumes Oubliés]', prerequis: ['Un don de métamagie'] },
  { nom: 'Seigneur du froid absolu', categorie: 'Métamagie', description: 'La moitié des dégâts de froid deviennent de l\'énergie négative. [Codex Profane]', prerequis: ['Substitution d\'énergie destructive (froid)', '9 rangs Connaissances (plans)'] },
  { nom: 'Sort en sanctuaire', categorie: 'Métamagie', description: 'Niveau effectif du sort augmenté en un lieu précis, diminué ailleurs. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Sort explosif', categorie: 'Métamagie', description: 'Les cibles sont repoussées à la limite de la zone d\'effet. [Codex Profane]', prerequis: ['Un don de métamagie'] },
  { nom: 'Sort jumeau', categorie: 'Métamagie', description: 'Lance simultanément un sort deux fois (+4 niveaux). [Codex Profane / Royaumes Oubliés]', prerequis: ['Un don de métamagie'] },
  { nom: 'Sort persistant', categorie: 'Métamagie', description: 'Un sort à portée fixe ou personnelle dure 24 heures (+4 niveaux). [Codex Profane / Royaumes Oubliés]', prerequis: ['Extension de durée'] },
  { nom: 'Sort robuste', categorie: 'Métamagie', description: 'Niveau de lanceur plus élevé pour vaincre la résistance à la magie. [Codex Profane]', prerequis: ['Un don de métamagie', '5 rangs Connaissances (mystères)'] },
  { nom: 'Substitution d\'énergie destructive', categorie: 'Métamagie', description: 'Les sorts infligent un type d\'énergie destructive différent. [Codex Profane]', prerequis: ['5 rangs Connaissances (mystères)', 'Un don de métamagie'] },
  { nom: 'Substitution non-létale', categorie: 'Métamagie', description: 'Les sorts d\'énergie infligent des dégâts non létaux. [Codex Profane]', prerequis: ['5 rangs Connaissances (mystères)', 'Un don de métamagie'] },

  // ── MAÎTRES DE LA NATURE ──
  { nom: 'Agilité du singe', categorie: 'Général', description: 'Se déplace d\'arbre en arbre à sa vitesse normale. [Maîtres de la Nature]', prerequis: ['6 rangs Escalade et Saut', 'FOR13'] },
  { nom: 'Attaque en vol (aérienne)', categorie: 'Combat', description: 'En vol : déplacement + action partielle à tout moment du mouvement. [Maîtres de la Nature]', prerequis: ['Faculté de vol'] },
  { nom: 'Attaques multiples', categorie: 'Combat', description: 'Attaques naturelles secondaires à −2 (au lieu de −5). [Maîtres de la Nature]', prerequis: ['3 armes naturelles ou plus'] },
  { nom: 'Capture', categorie: 'Combat', description: 'Engage une lutte automatiquement sur un coup de griffe ou de morsure ; peut serrer et rejeter la proie. [Maîtres de la Nature]', prerequis: ['Griffes ou morsure naturelles'] },
  { nom: 'Commandement des animaux', categorie: 'Général', description: 'Intimide/contrôle les animaux comme un prêtre mauvais les morts-vivants (3 + mod CHA/jour). [Maîtres de la Nature]', prerequis: ['Répulsion des animaux'] },
  { nom: 'Commandement des plantes', categorie: 'Général', description: 'Intimide/contrôle les créatures végétales (3 + mod CHA/jour). [Maîtres de la Nature]', prerequis: ['Répulsion des plantes'] },
  { nom: 'Communication sous forme animale', categorie: 'Général', description: 'Communique avec les animaux de la même famille sous forme animale. [Maîtres de la Nature]', prerequis: ['Forme animale', 'INT13'] },
  { nom: 'Création d\'infusion', categorie: 'Magie', description: 'Crée des infusions : herbes-réceptacles de sorts divins (prix = niveau × NLS × 50 po). [Maîtres de la Nature]', prerequis: ['4 rangs Sens de la nature', 'lanceur niveau 3'] },
  { nom: 'Critique ennemi', categorie: 'Combat', description: 'Zone de critique doublée contre l\'ennemi juré choisi. [Maîtres de la Nature]', prerequis: ['BBA+5', 'Un ennemi juré'] },
  { nom: 'Ennemi juré supplémentaire', categorie: 'Général', description: 'Un ennemi juré de plus. [Maîtres de la Nature]', prerequis: ['BBA+5', 'Un ennemi juré'] },
  { nom: 'Forme animale proportionnelle', categorie: 'Général', description: 'Prend une forme animale de sa propre catégorie de taille. [Maîtres de la Nature]', prerequis: ['Forme animale', 'taille autre que M ou P'] },
  { nom: 'Frappe surnaturelle', categorie: 'Combat', description: 'Contre l\'ennemi juré immunisé aux critiques : +1d6 par dé de critique et le bonus d\'ennemi juré s\'applique. [Maîtres de la Nature]', prerequis: ['BBA+7', 'Ennemi juré immunisé aux critiques'] },
  { nom: 'Grande vitalité', categorie: 'Général', description: 'La réduction des dégâts augmente de +1/—. [Maîtres de la Nature]', prerequis: ['Réduction des dégâts'] },
  { nom: 'Guérison rapide', categorie: 'Général', description: 'Récupère pv et caractéristiques affaiblies plus vite (jusqu\'à 4 pv/niveau/jour). [Maîtres de la Nature]', prerequis: ['Vigueur de base +5'] },
  { nom: 'Incantation animale', categorie: 'Magie', description: 'Effectue les composantes verbales et gestuelles sous forme animale. [Maîtres de la Nature]', prerequis: ['Forme animale', 'SAG13'] },
  { nom: 'Longue rage', categorie: 'Général', description: 'Chaque rage dure 5 rounds de plus. Cumulable. [Maîtres de la Nature]', prerequis: ['Rage de berserker'] },
  { nom: 'Lutteur habile', categorie: 'Combat', description: 'Bonus aux jets de lutte pour échapper aux créatures plus grandes (+2 à +8 selon la taille). [Maîtres de la Nature]', prerequis: ['Science du combat à mains nues', 'taille M ou P'] },
  { nom: 'Maîtrise du critique', categorie: 'Combat', needsWeapon: true, description: '1×/jour, déclare un critique possible avant le jet d\'attaque (à confirmer normalement). [Maîtres de la Nature]', prerequis: ['Science du critique', 'BBA+12'] },
  { nom: 'Multidextrie', categorie: 'Combat', description: 'Annule les malus des mains non directrices (créatures à 3+ bras). [Maîtres de la Nature]', prerequis: ['DEX15', '3 bras ou plus'] },
  { nom: 'Obstination', categorie: 'Général', description: 'Peut agir (action partielle) entre 0 et −10 pv. [Maîtres de la Nature]', prerequis: ['BBA+2', 'Endurance', 'Volonté de fer', 'Robustesse'] },
  { nom: 'Odorat', categorie: 'Général', description: 'Pouvoir d\'odorat permanent, quelle que soit la forme. [Maîtres de la Nature]', prerequis: ['Forme animale de loup', 'SAG11'] },
  { nom: 'Parade « main gauche »', categorie: 'Combat', description: 'Sacrifie les attaques secondaires pour +2 d\'esquive à la CA. [Maîtres de la Nature]', prerequis: ['Ambidextrie', 'DEX13', 'Combat à deux armes', 'BBA+3'] },
  { nom: 'Rage destructrice', categorie: 'Général', description: '+8 aux jets de Force pour briser objets et portes pendant la rage. [Maîtres de la Nature]', prerequis: ['Rage de berserker'] },
  { nom: 'Rage instantanée', categorie: 'Général', description: 'Entre en rage à tout moment, même hors de son tour ou surpris. [Maîtres de la Nature]', prerequis: ['Rage de berserker'] },
  { nom: 'Rage intimidante', categorie: 'Général', description: 'En rage, secoue un adversaire à 9 m (Volonté annule). [Maîtres de la Nature]', prerequis: ['Rage de berserker'] },
  { nom: 'Rages supplémentaires', categorie: 'Général', description: '+2 rages de berserker par jour. Cumulable. [Maîtres de la Nature]', prerequis: ['Rage de berserker'] },
  { nom: 'Répulsion des animaux', categorie: 'Général', description: 'Repousse les animaux comme un prêtre bon les morts-vivants (3 + mod CHA/jour). [Maîtres de la Nature]', prerequis: ['Lancer détection de la faune ou de la flore'] },
  { nom: 'Répulsion des plantes', categorie: 'Général', description: 'Repousse les créatures végétales (3 + mod CHA/jour). [Maîtres de la Nature]', prerequis: ['Lancer détection de la faune ou de la flore'] },
  { nom: 'Résistance à une énergie destructive', categorie: 'Général', description: 'Résistance 5 à un type d\'énergie choisi. Cumulable. [Maîtres de la Nature]', prerequis: ['Vigueur de base +8'] },
  { nom: 'Résistance au poison', categorie: 'Général', description: '+4 aux jets de Vigueur contre le poison. [Maîtres de la Nature / Royaumes Oubliés]' },
  { nom: 'Résistance aux maladies', categorie: 'Général', description: '+4 aux jets de Vigueur contre les maladies. [Maîtres de la Nature]' },
  { nom: 'Robustesse des nains', categorie: 'Général', description: '+6 points de vie. Cumulable. [Maîtres de la Nature]', prerequis: ['Vigueur de base +5'] },
  { nom: 'Robustesse des géants', categorie: 'Général', description: '+9 points de vie. Cumulable. [Maîtres de la Nature]', prerequis: ['Vigueur de base +8'] },
  { nom: 'Robustesse des dragons', categorie: 'Général', description: '+12 points de vie. Cumulable. [Maîtres de la Nature]', prerequis: ['Vigueur de base +11'] },
  { nom: 'Science de la filature', categorie: 'Général', description: '+2 aux jets de Détection et de Discrétion. [Maîtres de la Nature]' },
  { nom: 'Science de la nage', categorie: 'Général', description: 'Nage à la moitié de sa vitesse (action de mouvement) ou aux trois quarts (action complexe). [Maîtres de la Nature]', prerequis: ['6 rangs Natation'] },
  { nom: 'Science du vol', categorie: 'Général', description: 'La manœuvrabilité en vol augmente d\'un cran. [Maîtres de la Nature]', prerequis: ['Faculté de voler'] },
  { nom: 'Virage sur l\'aile', categorie: 'Général', description: '1×/round, virage supplémentaire jusqu\'à un demi-tour en vol. [Maîtres de la Nature]', prerequis: ['Faculté de voler'] },
  { nom: 'Vision aveugle', categorie: 'Général', description: 'Pouvoir de vision aveugle (sonar, 36 m), quelle que soit la forme. [Maîtres de la Nature]', prerequis: ['Forme animale de chauve-souris'] },

  // ── ROYAUMES OUBLIÉS — dons régionaux ──
  { nom: 'Adaptation diurne', categorie: 'Général', description: 'Annule les malus d\'aveuglement et d\'éblouissement à la lumière vive. Régions : drow, nain gris, orque. [Royaumes Oubliés]' },
  { nom: 'Arboricole', categorie: 'Général', description: 'Aisance dans les arbres (+2 Escalade, stable dans les branches). Régions : Aglarond, Bois de Chondal, elfe des bois… [Royaumes Oubliés]' },
  { nom: 'Artisan magique', categorie: 'Magie', description: 'Réduit de 25 % le coût (PX et matières) d\'un don de création d\'objets choisi. [Royaumes Oubliés]', prerequis: ['Un don de création d\'objets'] },
  { nom: 'Artiste', categorie: 'Général', description: '+2 en Représentation et dans un Artisanat artistique au choix. Régions : Chessenta, Eauprofonde, Éternelle-Rencontre, gnome des roches. [Royaumes Oubliés]' },
  { nom: 'Beau parleur', categorie: 'Général', description: '+2 en Diplomatie et Psychologie. Régions : Eauprofonde, halfelins, Luiren, Lunargent, nain d\'or, Thesk. [Royaumes Oubliés]' },
  { nom: 'Brute', categorie: 'Général', description: '+2 à l\'initiative et à l\'Intimidation. Régions : Bief de Vilhon, Calimshan, Côte des dragons, Eauprofonde… [Royaumes Oubliés]' },
  { nom: 'Cavalier émérite', categorie: 'Général', description: '+3 en Équitation. Régions : Contrées du Mitan Occidentales, Cormyr, Narfell, Nord, Terres de la Horde. [Royaumes Oubliés]' },
  { nom: 'Chance des héros', categorie: 'Général', description: '+1 de chance à tous les jets de sauvegarde. Régions : Aglarond, Téthyr, Vaste, Vaux. [Royaumes Oubliés]' },
  { nom: 'Contresort amélioré', categorie: 'Magie', description: 'Contre un sort avec tout sort de la même école d\'un niveau supérieur. [Royaumes Oubliés]' },
  { nom: 'Cosmopolite', categorie: 'Général', description: 'Une compétence au choix devient de classe avec +2. Régions : Amn, Eauprofonde. [Royaumes Oubliés]' },
  { nom: 'Création de portails', categorie: 'Magie', description: 'Permet de créer des portails permanents de téléportation. [Royaumes Oubliés]', prerequis: ['Création d\'objets merveilleux'] },
  { nom: 'Débrouillard', categorie: 'Général', description: '+2 en Bluff et Renseignements. Régions : Amn, Calimshan, Chessenta, Mer de lune, Unther. [Royaumes Oubliés]' },
  { nom: 'Discipline', categorie: 'Général', description: '+1 en Volonté, +2 en Concentration. Régions : Aglarond, Anauroch, Cormyr, elfe du soleil, Thay… [Royaumes Oubliés]' },
  { nom: 'Discret', categorie: 'Général', description: '+2 en Déplacement silencieux et Discrétion. Régions : demi-orque, drow, halfelins. [Royaumes Oubliés]' },
  { nom: 'École supérieure', categorie: 'Magie', description: '+4 au DD des sorts de l\'école choisie (remplace École renforcée). [Royaumes Oubliés]', prerequis: ['École renforcée'] },
  { nom: 'Éducation', categorie: 'Général', description: 'Toutes les Connaissances deviennent de classe ; +1 à deux Connaissances au choix. Niveau 1 seulement. [Royaumes Oubliés]' },
  { nom: 'Efficacité des sorts supérieure', categorie: 'Magie', description: '+4 aux tests contre la résistance à la magie (remplace Efficacité des sorts accrue). [Royaumes Oubliés]', prerequis: ['Efficacité des sorts accrue'] },
  { nom: 'Épées jumelles', categorie: 'Combat', description: '+2 d\'armure à la CA contre un adversaire désigné en combattant à deux épées. Régions : drow, Eauprofonde, Sembie. [Royaumes Oubliés]', prerequis: ['Combat à deux armes'] },
  { nom: 'Ethran', categorie: 'Général', description: 'Membre des Sorcières de Rashéménie : +2 Empathie animale et Sens de l\'orientation ; +2 aux compétences CHA avec les Rashémis. [Royaumes Oubliés]', prerequis: ['Femme', 'CHA11', 'Lanceur niveau 1'] },
  { nom: 'Familier supérieur', categorie: 'Magie', description: 'Accès à des familiers plus puissants (diablotin, pseudo-dragon, quasit, strige…). [Royaumes Oubliés]', prerequis: ['Capacité d\'appeler un familier'] },
  { nom: 'Fibre commerciale', categorie: 'Général', description: '+2 en Estimation et un Artisanat/Profession au choix. Régions : Impiltur, Lantan, Sembie, Thesk… [Royaumes Oubliés]' },
  { nom: 'Force d\'âme', categorie: 'Général', description: '+1 en Vigueur et Volonté ; +1 de plus contre l\'absorption d\'énergie et les effets de mort. Régions : elfes, gnomes, halfelins, Vaux… [Royaumes Oubliés]' },
  { nom: 'Forestier', categorie: 'Général', description: '+2 en Sens de la nature. Régions : Bois de Chondal, elfes, Grand-Val, Haute-Forêt, Vaux. [Royaumes Oubliés]' },
  { nom: 'Formation magique', categorie: 'Magie', description: 'Hébétement, lumières dansantes et manipulation à distance 1×/jour. Région : Halruaa. Niveau 1 seulement. [Royaumes Oubliés]', prerequis: ['INT10'] },
  { nom: 'Impétueux', categorie: 'Général', description: '+1 en Volonté, +2 en Intimidation. Régions : Damarie, îles Moonshae, nains, Rashéménie, Vaasie… [Royaumes Oubliés]' },
  { nom: 'Instruction profane', categorie: 'Général', description: 'Une classe de lanceur profane devient classe de prédilection supplémentaire. Régions : Chessenta, Halruaa, Lantan, Mulhorande, Unther. [Royaumes Oubliés]' },
  { nom: 'Inscription de runes', categorie: 'Magie', description: 'Inscrit un sort divin préparé dans une rune à déclenchement. [Royaumes Oubliés]', prerequis: ['INT13', 'Artisanat adéquat', 'Lanceur divin niveau 3'] },
  { nom: 'Jumeau tonnerre', categorie: 'Général', description: '+2 aux jets basés sur le Charisme ; sent la direction de son jumeau. Régions : nain d\'écu, nain d\'or. Niveau 1 seulement. [Royaumes Oubliés]' },
  { nom: 'Lignée de feu', categorie: 'Général', description: '+4 aux JS contre le feu ; +2 au DD des sorts d\'ensorceleur de feu. Région : Calimshan. Niveau 1 seulement. [Royaumes Oubliés]' },
  { nom: 'Magie de la Toile d\'Ombre', categorie: 'Magie', description: 'Sorts puisés dans la Toile d\'Ombre : +1 DD et +1 contre la RM (Enchantement, Illusion, Nécromancie, obscurité) ; −1 niveau en Évocation/Transmutation ; plus de sorts de lumière ; coût −2 SAG permanent. [Royaumes Oubliés]', prerequis: ['SAG13 ou Shar comme divinité'] },
  { nom: 'Magie insidieuse', categorie: 'Métamagie', description: 'Les divinations de la Toile doivent réussir un jet de niveau pour détecter vos sorts. [Royaumes Oubliés]', prerequis: ['Magie de la Toile d\'Ombre'] },
  { nom: 'Magie pernicieuse', categorie: 'Métamagie', description: 'Vos sorts résistent aux contresorts des utilisateurs de la Toile. [Royaumes Oubliés]', prerequis: ['Magie de la Toile d\'Ombre'] },
  { nom: 'Magie tenace', categorie: 'Métamagie', description: 'Vos sorts résistent à la dissipation (DD 15 + niveau de lanceur). [Royaumes Oubliés]', prerequis: ['Magie de la Toile d\'Ombre'] },
  { nom: 'Magocratie courtoise', categorie: 'Général', description: '+2 en Connaissance des sorts et Diplomatie. Régions : Éternelle-Rencontre, Halruaa. [Royaumes Oubliés]' },
  { nom: 'Milice', categorie: 'Combat', description: 'Dons Maniement des armes de guerre (arc long et pique ; arc court et épée courte au Luiren). Régions : halfelin vaillant, Impiltur, Luiren, Vaux. [Royaumes Oubliés]' },
  { nom: 'Négociateur-né', categorie: 'Général', description: '+2 en Bluff et Estimation. Régions : Amn, Grand-Val, Impiltur, Sembie, Thesk… [Royaumes Oubliés]' },
  { nom: 'Nomade monté', categorie: 'Combat', description: 'Maniement de l\'arc court composite + +2 en Équitation. Régions : Shaar, Terres de la Horde, Vaasie. [Royaumes Oubliés]' },
  { nom: 'Prodige magique', categorie: 'Magie', description: 'Caractéristique primaire de lanceur considérée +2 (sorts en bonus et DD). Niveau 1 seulement. [Royaumes Oubliés]' },
  { nom: 'Racé', categorie: 'Général', description: '+2 à l\'initiative et à la Détection. Régions : îles Nélanthères, Lunargent, Sembie, Téthyr, Vaasie, Vaux. [Royaumes Oubliés]' },
  { nom: 'Sang de serpent', categorie: 'Général', description: '+2 en Vigueur contre les poisons, +1 en Réflexes. Régions : Hlondeth, Chult, Tashalar. Niveau 1 seulement. [Royaumes Oubliés]' },
  { nom: 'Sort de signature', categorie: 'Magie', description: 'Convertit spontanément des sorts préparés en un sort maîtrisé choisi. [Royaumes Oubliés]', prerequis: ['Maîtrise des sorts'] },
  { nom: 'Suprématie spirituelle', categorie: 'Magie', description: 'Au niveau 1, INT au lieu de CON pour les pv ; +1 pv par don de métamagie appris. Régions : Calimshan, elfes, Thay. Niveau 1 seulement. [Royaumes Oubliés]' },
  { nom: 'Survivant', categorie: 'Général', description: '+1 en Vigueur, +2 en Sens de la nature. Régions : Anauroch, Nord, Rashéménie, Terres de la Horde… [Royaumes Oubliés]' },
  { nom: 'Tatouage focalisateur', categorie: 'Magie', description: '+1 au DD et +1 contre la RM pour les sorts de son école de prédilection. Région : Thay. [Royaumes Oubliés]', prerequis: ['Spécialisation dans une école'] },
  { nom: 'Traqueur', categorie: 'Combat', description: '+1 aux dégâts et Science du critique virtuelle contre l\'ennemi traditionnel de la région (gobelinoïdes, orques, gnolls ou yuan-tis selon la région). [Royaumes Oubliés]' },
]
