import type { ClasseInfo } from './classes'

// ─── Classes de prestige D&D 3.5 ─────────────────────────────────────────────
// Extraites des suppléments : Codex Divin (CD), Codex Profane (CP),
// Les Maîtres de la Nature (MN), Manuel des Joueurs de Faerûn (MJF).
// Une classe de prestige se superpose à une classe de base (multi-classes).
// La mention de source figure à la fin de chaque résumé.

export interface ClassePrestigeInfo extends ClasseInfo {
  prestige: true
  source: string        // livre d'origine (mini note)
  conditions: string    // conditions d'accès résumées
  niveauxMax: number    // nombre de niveaux de la classe (5 ou 10 en général)
  // Progression de lancement de sorts : la classe ajoute ses niveaux au niveau
  // de lanceur d'une classe de base existante (« +1 niveau de lanceur »)
  // 'complete' = chaque niveau ; 'demi' = un niveau sur deux ; 'partielle' = selon niveauxAvecSorts
  progressionSorts?: 'complete' | 'demi' | 'partielle'
  niveauxAvecSorts?: number[]  // pour 'partielle' : niveaux de classe qui accordent +1 niveau de lanceur
  typeLanceur?: 'arcane' | 'divin' | 'les-deux'
  resume: string        // pouvoirs clés de la classe
}

export const CLASSES_ARCANES = ['Magicien', 'Ensorceleur', 'Barde']
export const CLASSES_DIVINES = ['Prêtre', 'Druide', 'Paladin', 'Rôdeur']

export const PRESTIGE_CLASSES: ClassePrestigeInfo[] = [
  // ─── Guide du Maître (p.176-198) ───────────────────────────────────────────
  { nom: 'Archer-mage', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur', 'reflexes'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Elfe ou demi-elfe ; BBA +6 ; dons Arme de prédilection (arc court ou long), Tir à bout portant, Tir de précision ; sorts profanes de 1er niveau.',
    resume: 'Archer elfe imprégné de magie : flèches enchantées (+1 à +5), flèche emprisonnante, pluie de flèches, flèche de mort (GM p.177).' },
  { nom: 'Archimage', prestige: true, source: 'Guide du Maître', niveauxMax: 5,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'arcane',
    conditions: 'Art de la magie 15, Connaissances (mystères) 15 ; dons Talent (Art de la magie) et École renforcée dans deux écoles ; sorts profanes de 7e niveau et connaissance de sorts de 5e niveau de cinq écoles.',
    resume: 'Sommet de la magie profane : hauts faits de magie (feu profane, maîtrise des formes, contresort maître, portée doublée…) achetés en sacrifiant des emplacements (GM p.178).' },
  { nom: 'Arpenteur d\'horizon', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Connaissances (géographie) 8 ; don Endurance.',
    resume: 'Explorateur infatigable : maîtrises de terrains successives (désert, forêt, montagne… puis terrains planaires), déplacement dimensionnel final (GM p.180).' },
  { nom: 'Assassin', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['reflexes'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Mauvais ; Déplacement silencieux 8, Discrétion 8, Déguisement 4 ; avoir tué une personne dans le seul but de rejoindre les assassins.',
    resume: 'Tueur d\'élite : attaque mortelle (paralysie ou mort après 3 rounds d\'observation), attaque sournoise +1d6/2 niveaux, maître du poison, sorts profanes propres du 1er au 4e niveau (table GM p.182) (GM p.181).' },
  { nom: 'Chevalier noir', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Mauvais ; BBA +6 ; Connaissances (religion) 2, Discrétion 5 ; dons Attaque en puissance et Enchaînement ; contact avec un Extérieur mauvais (GM p.184).',
    resume: 'Anti-paladin : châtiment du Bien, aura maléfique, imposition des mains inversée, serviteur fiélon, sorts divins propres du 1er au 4e niveau ; règles spéciales pour les paladins déchus (GM p.183).' },
  { nom: 'Disciple draconien', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 12, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Sorts profanes spontanés (sans grimoire, ex. Ensorceleur) ; Connaissances (mystères) 8 ; parler le draconien.',
    resume: 'Héritier du sang de dragon : armure naturelle croissante, bonus de FOR/CON/INT/CHA, souffle, ailes — devient demi-dragon au niveau 10 (GM p.186).' },
  { nom: 'Duelliste', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['reflexes'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'BBA +6 ; Acrobaties 3, Représentation 5 ; dons Attaque en finesse, Esquive, Souplesse du serpent.',
    resume: 'Escrimeur virtuose : défense astucieuse (INT à la CA), grande souplesse, charge acrobatique, parade élaborée, botte précise (GM p.187).' },
  { nom: 'Gardien du savoir', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 4, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'les-deux',
    conditions: 'Connaissances 10 dans deux spécialités ; trois dons de métamagie ou de création d\'objets plus Talent (Connaissances) ; faculté de lancer sept sorts de Divination dont un de 3e niveau ou plus.',
    resume: 'Érudit ultime : secrets (petits pouvoirs au choix à chaque niveau impair), savoir légendaire, mémoire parfaite, vrai savoir (GM p.188).' },
  { nom: 'Hiérophante', prestige: true, source: 'Guide du Maître', niveauxMax: 5,
    de: 8, bab: 'faible', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Connaissances (religion) 15 ; au moins un don de métamagie ; sorts divins de 7e niveau.',
    resume: 'Sommet de la magie divine : PAS de progression de sorts, mais un pouvoir sacré au choix par niveau (sort à distance, renvoi maître, pouvoir magique, canalisation…) (GM p.189).' },
  { nom: 'Magicien Rouge', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'arcane',
    conditions: 'Humain de Thay ; non bon ; Art de la magie 8 ; dons Tatouage focaliseur et trois dons de métamagie ou de création d\'objets ; sorts profanes de 3e niveau.',
    resume: 'Mage spécialiste de Thay : spécialisation renforcée (écoles interdites supplémentaires), pouvoir de cercle amplifié par ses pairs, tatouages magiques (GM p.190).' },
  { nom: 'Maître des ombres', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['reflexes'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Déplacement silencieux 8, Discrétion 10, Représentation (danse) 5 ; dons Attaques réflexes, Esquive, Souplesse du serpent.',
    resume: 'Danseur entre les ombres : se cacher en pleine vue, compagnon d\'ombre, pas de l\'ombre (téléportation d\'ombre en ombre), vision dans le noir, esquive totale (GM p.192).' },
  { nom: 'Mystificateur profane', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['reflexes', 'volonte'], competencesParNiveau: 4, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'arcane',
    conditions: 'Non loyal ; Décryptage 7, Désamorçage/sabotage 7, Évasion 7, Connaissances (mystères) 4 ; attaque sournoise +2d6 ; faculté de lancer manipulation à distance et un sort profane de 3e niveau ou plus.',
    resume: 'Roublard-magicien : larcin à distance (crochetage/escamotage par magie), attaque sournoise +1d6/2 niveaux, sort sournois impromptu (GM p.193).' },
  { nom: 'Protecteur nain', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 12, bab: 'elevee', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Nain ; loyal ; BBA +7 ; dons Endurance, Esquive et Robustesse.',
    resume: 'Rempart vivant des cités naines : position défensive (+FOR/CON/CA, immobile), sens des pièges, esquive instinctive, réduction des dégâts (GM p.194).' },
  { nom: 'Thaumaturge', prestige: true, source: 'Guide du Maître', niveauxMax: 5,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'divin',
    conditions: 'Don École renforcée (Invocation) ; faculté de lancer allié d\'outreplan.',
    resume: 'Invocateur divin : convocations prolongées et améliorées, allié planaire attitré, contrat d\'outreplan (GM p.196).' },
  { nom: 'Théurge mystique', prestige: true, source: 'Guide du Maître', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'les-deux',
    conditions: 'Connaissances (mystères) 6, Connaissances (religion) 6 ; faculté de lancer des sorts profanes de 2e niveau ET des sorts divins de 2e niveau.',
    resume: 'Double lanceur : chaque niveau fait progresser À LA FOIS la classe profane et la classe divine (+1 niveau de lanceur des deux côtés) (GM p.197).' },

  // ─── Codex Divin (p.19-76) ─────────────────────────────────────────────────
  { nom: 'Chevalier hospitalier', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [4, 5, 6, 7, 8, 9, 10], typeLanceur: 'divin',
    conditions: 'Non chaotique ; BBA +5 ; Dressage 5, Équitation 5 ; dons Attaque au galop et Combat monté ; sorts divins de 1er niveau.',
    resume: 'Chevalier voué à la protection des pèlerins : dons supplémentaires, imposition des mains, guérison des maladies (CD p.21).' },
  { nom: 'Croisé divin', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Alignement identique à la divinité tutélaire ; BBA +7 ; Connaissances (religion) 2 ; Arme de prédilection (arme de la divinité).',
    resume: 'Champion d\'un dieu : sorts propres tirés d\'UN domaine de la divinité (1er au 9e niveau, table CD p.24), aura de foi, châtiment (CD p.23).' },
  { nom: 'Disciple du Vide', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 6, 7, 8, 10], typeLanceur: 'les-deux',
    conditions: 'Composante neutre ; Art de la magie 10 ; dons Augmentation d\'intensité et Efficacité des sorts accrue ; sorts profanes ou divins de 3e niveau.',
    resume: 'Mystique du néant : perception du Vide, annulation de la magie, désintégration (CD p.25).' },
  { nom: 'Entropomancien', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 6, 7, 8, 10], typeLanceur: 'divin',
    conditions: 'Non bon ; Concentration 5, Connaissances (mystères) 5 ; sorts divins de 4e niveau.',
    resume: 'Canalise l\'entropie : sphère du chaos, absorption d\'énergie, toucher entropique (CD p.28).' },
  { nom: 'Évangéliste errant', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['volonte'], competencesParNiveau: 6, lanceurSorts: false,
    conditions: 'Alignement compatible avec la divinité ; Bluff 8, Connaissances (religion) 5, Psychologie 5, Renseignements 5, Représentation (déclamation) 6 ; don Négociation ou Persuasion.',
    resume: 'Prêcheur itinérant : sermon fascinant, conversion des foules, éloquence sacrée — pas de progression de sorts (CD p.30).' },
  { nom: 'Exorciste consacré', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'les-deux',
    conditions: 'Bon ; Connaissances (plans) 10, Connaissances (religion) 7 ; faculté de lancer renvoi ou rejet du Mal ; ordination par une Église.',
    resume: 'Chasseur de démons ordonné : exorcisme, renvoi des morts-vivants, châtiment du Mal, résistance aux possessions (CD p.33).' },
  { nom: 'Fanatique de la Flamme noire', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['reflexes', 'volonte'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Non bon ; Connaissances (religion) 8, Déplacement silencieux 8, Discrétion 8 ; Maniement d\'une arme de guerre ; rite d\'initiation.',
    resume: 'Assassin sacré du feu noir : attaque sournoise, coup mortel, fanatisme sans peur — pas de progression de sorts (CD p.35).' },
  { nom: 'Géomancien', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'les-deux',
    conditions: 'Connaissances (mystères) 6, Connaissances (nature) 6 ; faculté de lancer des sorts divins ET profanes de 2e niveau.',
    resume: 'Fusionne magie profane et divine : dérive géomantique, incantation mixte sans restriction d\'armure (CD p.37).' },
  { nom: 'Inquisiteur de la Foi', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'divin',
    conditions: 'Loyal bon ou loyal neutre ; Volonté +3 ; Art de la magie 4, Connaissances (mystères) 4, Connaissances (religion) 4.',
    resume: 'Traqueur d\'hérésies : détection du mensonge et du Mal, immunité aux charmes, inquisition sacrée (CD p.41).' },
  { nom: 'Lame étincelante d\'Héronéus', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'demi', typeLanceur: 'divin',
    conditions: 'Loyal bon ; BBA +7 ; Volonté +3 ; Connaissances (religion) 7 ; sorts divins de 1er niveau ; Héronéus divinité tutélaire.',
    resume: 'Escrimeur sacré : lame d\'énergie électrique, charge foudroyante, défense éclatante (CD p.44).' },
  { nom: 'Libérateur sacré', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'demi', typeLanceur: 'divin',
    conditions: 'Chaotique bon ; BBA +5 ; Diplomatie 5, Psychologie 5 ; don Volonté de fer.',
    resume: 'Paladin de la liberté : aura de résolution, cercle magique contre le Mal, châtiment du Mal, destrier céleste (CD p.46).' },
  { nom: 'Maître contemplatif', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'divin',
    conditions: 'Connaissances (religion) 13 ; sorts divins de 1er niveau ; contact direct avec sa divinité ou un de ses serviteurs.',
    resume: 'Illuminé touché par le divin : domaine supplémentaire, corps béni, santé divine, éternelle jeunesse (CD p.49).' },
  { nom: 'Oracle divin', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['reflexes', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'divin',
    conditions: 'Connaissances (religion) 8 ; don Talent (Connaissances (religion)) ; faculté de lancer au moins deux sorts de Divination.',
    resume: 'Prophète : domaine des Oracles, transe prophétique, esquive instinctive, immunité à la surprise (CD p.51).' },
  { nom: 'Pilleur de temple d\'Olidammara', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['reflexes'], competencesParNiveau: 6, lanceurSorts: false,
    conditions: 'Chaotique ; BBA +5 ; Connaissances (religion) 1, Crochetage 4, Désamorçage/sabotage 4, Fouille 8 ; vénérer Olidammara et être coopté.',
    resume: 'Voleur sacré : attaque sournoise, sorts divins propres de faible niveau (table CD p.54), détection des pièges bénie (CD p.53).' },
  { nom: 'Poing sacré', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'reflexes', 'volonte'], competencesParNiveau: 4, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 5, 6, 7, 9, 10], typeLanceur: 'divin',
    conditions: 'BBA +4 ; Connaissances (religion) 8 ; dons Attaques réflexes, Coup étourdissant, Magie de guerre, Science du combat à mains nues ; sorts divins de 1er niveau.',
    resume: 'Moine sacré : combat à mains nues amélioré, CA de sagesse, poings enflammés, incantation en mêlée (CD p.56).' },
  { nom: 'Prêtre de guerre', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'demi', typeLanceur: 'divin',
    conditions: 'BBA +5 ; Diplomatie 8, Psychologie 5 ; don Magie de guerre ; accès à un sort des domaines Destruction, Force, Guerre ou Protection ; renvoi des morts-vivants.',
    resume: 'Meneur des armées divines : cri de ralliement, bénédiction de bataille, aura de moral, incantation en armure (CD p.58).' },
  { nom: 'Prêtre déicide', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Mauvais ; Vigueur +3, Volonté +3 ; Art de la magie 8, Bluff 6, Connaissances (mystères 5, plans 5, religion 8) ; dons Alignement renforcé (Mal) et Volonté de fer ; incapable de lancer des sorts divins ; formation par un autre prêtre déicide.',
    resume: 'Vole la magie des dieux sans en vénérer aucun : sorts divins propres du 1er au 9e niveau en 10 niveaux (table CD p.61), renvoi des morts-vivants (CD p.60).' },
  { nom: 'Quêteur de l\'île des Brumes', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 4, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'divin',
    conditions: 'Elfe ou demi-elfe ; Connaissances (religion) 4, Survie 8 ; dévotion à Corellon Larethian.',
    resume: 'Pèlerin elfe en quête de l\'île perdue : pistage béni, vision des brumes, faveur de Corellon (CD p.62).' },
  { nom: 'Saccageur tellurique', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Non bon ; BBA +4 ; ancien druide capable de lancer des sorts de druide de 3e niveau (pouvoirs de druide perdus).',
    resume: 'Druide déchu voué à la destruction de la nature : sorts divins propres corrompus (table CD p.65), flétrissement, compagnon mort-vivant (CD p.64).' },
  { nom: 'Seigneur des tempêtes', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'demi', typeLanceur: 'divin',
    conditions: 'Vigueur +4 ; dons Arme de prédilection (épieu, javeline, lance ou pique), Endurance et Vigueur surhumaine ; dévotion à un dieu des tempêtes.',
    resume: 'Élu de la foudre : javelines d\'éclairs, résistance à l\'électricité, bouclier d\'orage, vol des tempêtes (CD p.66).' },
  { nom: 'Serviteur arc-en-ciel', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 5, 6, 7, 9, 10], typeLanceur: 'arcane',
    conditions: 'Ni mauvais ni chaotique ; Connaissances (mystères) 4 ; sorts profanes de 3e niveau ; découvrir les temples secrets des couatls.',
    resume: 'Initié des couatls : ailes arc-en-ciel, détection du Mal, ajoute des sorts de prêtre à sa liste profane (CD p.69).' },
  { nom: 'Serviteur radieux de Pélor', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'divin',
    conditions: 'Neutre bon ; Volonté +5 ; Connaissances (religion) 9, Premiers secours 5 ; don Emprise sur les morts-vivants ; sorts divins de 1er niveau et domaine du Soleil ; Pélor divinité tutélaire.',
    resume: 'Prêtre du soleil : renvoi amélioré et destruction des morts-vivants, guérison amplifiée, lumière rayonnante (CD p.71).' },
  { nom: 'Templier consacré', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'demi', typeLanceur: 'divin',
    conditions: 'BBA +5 ; Connaissances (religion) 4 ; dons Arme de prédilection (arme de la divinité) et Vraie foi (CD chap. 3).',
    resume: 'Défenseur du temple : résistance mentale, châtiment, dons de combat supplémentaires (CD p.73).' },
  { nom: 'Traqueur consacré', prestige: true, source: 'Codex Divin', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Loyal ; BBA +5 ; Déguisement 5, Renseignements 5 ; don Pistage ; accepter une mission de traque de son Église.',
    resume: 'Chasseur mandaté par l\'Église : ennemi juré désigné, pistage béni, châtiment de l\'infidèle — pas de progression de sorts (CD p.75).' },

  // ─── Codex Profane (p.17-70) ───────────────────────────────────────────────
  { nom: 'Accord sublime', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Art de la magie 6, Connaissances (mystères) 13, Profession (astrologue) 6, Représentation 10 ; sorts profanes de 3e niveau ; musique de barde.',
    resume: 'Chante la musique des sphères : sorts profanes propres du 4e au 9e niveau fondés sur le Charisme (table CP p.21), musique céleste (CP p.20).' },
  { nom: 'Acolyte de la peau', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 6, 7, 8, 9, 10], typeLanceur: 'arcane',
    conditions: 'Non bon ; Connaissances (plans) 6 ; niveau 5 de lanceur de sorts ; contact pacifique avec un Extérieur mauvais ; Rituel du Lien.',
    resume: 'Porte la peau d\'un fiélon liée à la sienne : vision dans le noir, griffes du démon, résistance au feu, immolation (CP p.23).' },
  { nom: 'Adepte de l\'étoile verdoyante', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 5, 6, 8, 9], typeLanceur: 'arcane',
    conditions: 'BBA +4 ; Connaissances (architecture 2, géographie 2, histoire 2, mystères 8) ; sorts profanes de 3e niveau ; ingérer de la poussière de métal stellaire.',
    resume: 'Se transforme peu à peu en créature de métal stellaire : corps cristallin, immunités croissantes, forme parfaite (CP p.25).' },
  { nom: 'Aliéniste', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'arcane',
    conditions: 'Non loyal ; Connaissances (plans) 8 ; don Amélioration des créatures convoquées ; un sort de convocation de 3e niveau ; contact avec une créature pseudo-naturelle.',
    resume: 'Invocateur des horreurs d\'outre-réalité : convocations pseudo-naturelles, folie grandissante, transcendance (CP p.28).' },
  { nom: 'Arcanamach suellois', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'BBA +6 ; Acrobaties 4, Art de la magie 5, Concentration 4, Saut 4 ; dons Magie de guerre et Volonté de fer ; langue vieux sulois ; maniement de quatre armes de guerre ou exotiques.',
    resume: 'Guerrier-mage de l\'ancien empire suellois : sorts profanes propres lancés en armure (table CP p.32), dissipation d\'un coup d\'épée (CP p.31).' },
  { nom: 'Géomètre', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'arcane',
    conditions: 'Connaissances (mystères) 9, Décryptage 9, Désamorçage/sabotage 4, Fouille 4 ; don Écriture de parchemins ; sorts profanes préparés de 3e niveau.',
    resume: 'Réduit toute magie à un glyphe parfait : grimoire runique, sorts glyphiques, signature magique cachée (CP p.33).' },
  { nom: 'Guide-voyageur', prestige: true, source: 'Codex Profane', niveauxMax: 5,
    de: 6, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 5], typeLanceur: 'arcane',
    conditions: 'Connaissances (géographie) 10, Connaissances (mystères) 10 ; faculté de lancer téléportation ; rejoindre l\'Union des guides-voyageurs.',
    resume: 'Maître des téléportations : téléportation améliorée et de groupe, arrivée précise, transport planaire (CP p.35).' },
  { nom: 'Initié du voile septuple', prestige: true, source: 'Codex Profane', niveauxMax: 7,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 5, 6], typeLanceur: 'arcane',
    conditions: 'Art de la magie 12 ; École renforcée (Abjuration) ; faculté de lancer sept sorts d\'abjuration dont un de 5e niveau ou plus.',
    resume: 'Maître des voiles prismatiques : murs de couleur aux sept pouvoirs, abjurations surpuissantes, robe prismatique (CP p.38).' },
  { nom: 'Mage de l\'ordre profane', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'arcane',
    conditions: 'Connaissances (mystères) 8 ; dons Coordination de sort et un don de métamagie ; sorts profanes préparés de 2e niveau ; droit d\'admission de 750 po.',
    resume: 'Membre de la guilde des mages : réserve commune de sorts (spellpool), missions de guilde, sorts coopératifs (CP p.42).' },
  { nom: 'Mage du sang', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 5, 7, 8, 9, 10], typeLanceur: 'arcane',
    conditions: 'Tous alignements sauf loyal bon ; Concentration 4 ; dons Robustesse et Vigueur surhumaine ; niveau 5 de lanceur profane ; avoir été tué puis ramené à la vie.',
    resume: 'Sa magie coule dans ses veines : composantes de sang, marche de sang (téléportation par les êtres vivants), semi-vie (CP p.45).' },
  { nom: 'Mage sauvage', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'arcane',
    conditions: 'Chaotique ; Art de la magie 8, Connaissances (plans) 4, Utilisation d\'objets magiques 4 ; dons Affinité magique et un don de métamagie ; niveau 1 de lanceur profane.',
    resume: 'Embrasse le chaos magique : niveau de lanceur aléatoire (1d6−2 à +2), déchaînements sauvages, chance capricieuse (CP p.49).' },
  { nom: 'Maître de l\'esprit', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 5, 6, 7, 8, 9, 10], typeLanceur: 'arcane',
    conditions: 'Non bon ; Bluff 4, Diplomatie 4, Intimidation 4, Psychologie 4 ; faculté de lancer charme-personne ou domination.',
    resume: 'Dominateur des esprits : contact mental, domination permanente, aura de servitude, lecture des pensées (CP p.51).' },
  { nom: 'Maître des effigies', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 6, 7, 8, 10], typeLanceur: 'arcane',
    conditions: 'Art de la magie 5, Artisanat 10, Connaissances (mystères) 5, Utilisation d\'objets magiques 2 ; don Création d\'objets merveilleux ; simulacre sur sa liste de sorts.',
    resume: 'Créateur de doubles artificiels : effigies de créatures, simulacres améliorés, golem personnel (CP p.54).' },
  { nom: 'Maître du destin', prestige: true, source: 'Codex Profane', niveauxMax: 5,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 4, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 5], typeLanceur: 'arcane',
    conditions: 'Connaissances (mystères) 10, Profession (joueur) 5 ; sorts profanes de 4e niveau dont un sort de Divination de 1er niveau.',
    resume: 'Joue avec les fils du destin : réserve de chance (spin fate), imposer un nouveau jet, sceller le sort d\'une cible (CP p.56).' },
  { nom: 'Maître transmogriffiste', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 6, 7, 8, 10], typeLanceur: 'arcane',
    conditions: 'Non loyal ; Bluff 2, Déguisement 5 ; faculté de lancer trois sorts de Transmutation de changement de forme dont métamorphose.',
    resume: 'Change de forme comme de chemise : formes favorites améliorées, métamorphose rapide, forme extraordinaire (CP p.58).' },
  { nom: 'Poing illuminé', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['reflexes', 'volonte'], competencesParNiveau: 4, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 6, 7, 8, 10], typeLanceur: 'arcane',
    conditions: 'Art de la magie 5, Concentration 8, Connaissances (mystères) 5 ; dons Coup étourdissant, Magie de guerre, Science du combat à mains nues ; niveau 3 de lanceur profane.',
    resume: 'Unit arts martiaux et magie profane : sorts canalisés par les poings, frappe arcanique, poings de l\'énergie (CP p.62).' },
  { nom: 'Quêteur de chant', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'reflexes'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Connaissances (mystères) 13, Représentation 13 ; don Talent (Représentation) ; musique de barde ; avoir entendu la musique primale.',
    resume: 'Cherche la musique originelle : chants de pouvoir (feu, guérison, vol…) remplaçant les sorts — pas de progression de sorts (CP p.64).' },
  { nom: 'Savant d\'argent', prestige: true, source: 'Codex Profane', niveauxMax: 5,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 5], typeLanceur: 'arcane',
    conditions: 'Art de la magie 12, Connaissances (mystères) 6 ; faculté de lancer cinq sorts du registre de la force dont un de 5e niveau ou plus.',
    resume: 'Spécialiste des effets de force : armures et murs de force renforcés, sorts de force pénétrants, forme de force (CP p.67).' },
  { nom: 'Savant élémentaire', prestige: true, source: 'Codex Profane', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'arcane',
    conditions: 'Connaissances (mystères) 8, Connaissances (plans) 4 ; don Substitution d\'énergie destructive ; trois sorts d\'un même registre d\'énergie dont un de 3e niveau ; contact avec un élémentaire.',
    resume: 'Se fond dans son élément : sorts d\'énergie transcendés, résistance puis immunité à son énergie, corps élémentaire (CP p.69).' },

  // ─── Les Maîtres de la Nature (p.43-81, règles 3.0) ────────────────────────
  { nom: 'Archer sylvain', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['reflexes'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'BBA +5 ; Déplacement silencieux 4, Détection 4, Discrétion 4 ; dons Arme de prédilection (arc ou arbalète), Tir à bout portant, Tir de loin.',
    resume: 'Tireur d\'élite des forêts : portée accrue, critiques améliorés (multiplicateur +1), flèche assurée, tir plongeant (MN p.44).' },
  { nom: 'Berserker frénétique', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Non loyal ; BBA +6 ; dons Attaque en puissance, Enchaînement, Rage destructrice, Rage intimidante.',
    resume: 'Fureur incarnée : frénésie (attaque supplémentaire, +6 en Force), attaque en puissance suprême, refuse de mourir sous 0 pv (MN p.46).' },
  { nom: 'Cavalier des vents', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'BBA +5 ; Connaissances (nature) 6, Dressage 8, Équitation 8 ; don Combat monté ; posséder une monture.',
    resume: 'Chevaucheur céleste : monture volante liée par télépathie, sorts propres de cavalerie (table MN p.48), charge aérienne (MN p.47).' },
  { nom: 'Change-forme', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'reflexes'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Dons Endurance et Vigilance ; sorts de 3e niveau ; connaître métamorphose ou posséder un pouvoir de changement de forme.',
    resume: 'Métamorphe accompli : formes plus nombreuses et durables, tailles extrêmes, forme parfaite sans limite quotidienne (MN p.50).' },
  { nom: 'Chasseur d\'ennemis', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'BBA +7 ; dons Arme de prédilection et Pistage ; parler la langue de l\'ennemi juré ; avoir choisi un ennemi mortel (définit la classe : chasseur de gobelins, etc.).',
    resume: 'Némésis d\'une race : dégâts de haine croissants, perce la résistance à la magie de l\'ennemi, critiques implacables contre lui (MN p.51).' },
  { nom: 'Dompteur de monstres', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [3, 6, 9], typeLanceur: 'divin',
    conditions: 'Empathie avec les animaux 10 ; don Talent (Empathie avec les animaux) ; faculté de lancer amitié avec les animaux.',
    resume: 'Meneur de créatures : compagnons monstrueux de plus en plus puissants (jusqu\'à 2× son niveau en DV), lien empathique renforcé (MN p.52).' },
  { nom: 'Fléau des infidèles', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'divin',
    conditions: 'Chef d\'une tribu xénophobe pratiquant le sacrifice ; sorts de druide (voir conditions détaillées MN p.54).',
    resume: 'Druide-chef fanatique : énergumènes enragés parmi ses suivants, bûcher funéraire, sacrifices qui renforcent ses sorts (MN p.54).' },
  { nom: 'Investigateur', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['reflexes', 'volonte'], competencesParNiveau: 6, lanceurSorts: false,
    conditions: 'Non mauvais ; Connaissances (au choix) 4 ; adhérer à la règle de la preuve (MN p.58).',
    resume: 'Détective du guet : sens du détail, interrogatoire expert, réseau d\'indicateurs, flair infaillible (MN p.58).' },
  { nom: 'Limier', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'BBA +4 ; Déplacement silencieux 4, Renseignements 4, Sens de la nature 4 ; dons Course et Pistage ; réussir l\'épreuve d\'admission de l\'organisation.',
    resume: 'Traqueur professionnel : proie désignée (bonus contre elle), traque infatigable, coup assommant, ne perd jamais la piste (MN p.60).' },
  { nom: 'Maître d\'armes exotiques', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'BBA +6 ; don Maniement des armes exotiques (trois armes au choix) ; faculté d\'entrer en rage de berserker.',
    resume: 'Virtuose des armes rares : bottes exotiques uniques (fléau double, arbalète de poing…), maîtrise totale en rage (MN p.62).' },
  { nom: 'Maître des vases', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'demi', typeLanceur: 'les-deux',
    conditions: 'Alchimie 4, Natation 4 ; don Vigueur surhumaine ; sorts divins ou profanes de 3e niveau.',
    resume: 'Symbiose gluante : toucher de vase (acide, paralysie…), immunités croissantes, forme de vase (MN p.64).' },
  { nom: 'Mauvais œil', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'divin',
    conditions: 'Humanoïde monstrueux, géant, gobelinoïde ou humanoïde primitif (orque, gnoll…) ; non bon ; Connaissances (mystères) 10, Connaissance des sorts 8, Sens de la nature 10 ; faculté de lancer éclair.',
    resume: 'Sorcier tribal au regard maudit : mauvais œil (malédictions du regard à volonté), autorité sur la tribu (MN p.66).' },
  { nom: 'Œil de Gruumsh', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 12, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Orque ou demi-orque ; chaotique mauvais, chaotique neutre ou neutre mauvais ; BBA +6 ; dons Arme de prédilection et Maniement des armes exotiques (hache double d\'orque) ; s\'arracher l\'œil droit en silence.',
    resume: 'Élu borgne du dieu orque : rage aveugle, vision borgne compensée, commandement des orques, férocité sacrée (MN p.68).' },
  { nom: 'Renonciateur', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 12, bab: 'elevee', bonsSauvegardes: ['vigueur', 'reflexes', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Dons Réflexes surhumains, Vigueur surhumaine et Volonté de fer ; avoir failli mourir de la magie ; renoncer à tout objet magique, sort et pouvoir magique.',
    resume: 'Rejette toute magie : résistance à la magie croissante, +1 à une caractéristique par niveau, guérison accélérée, doit détruire des objets magiques (MN p.69).' },
  { nom: 'Roi de la nature', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Vigueur +4 ; Discrétion 4, Sens de l\'orientation 4, Sens de la nature 8, compétence du terrain choisi 4 ; dons Endurance et Pistage ; choisir un milieu naturel (roi du désert, de la forêt…).',
    resume: 'Souverain d\'un terrain : domination de son milieu naturel, sorts propres liés au terrain (table MN p.72), convocation d\'alliés naturels (MN p.71).' },
  { nom: 'Seigneur des animaux', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['reflexes', 'volonte'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Alignement à composante neutre ; Empathie avec les animaux 6, Sens de la nature 8, compétence du groupe animal choisi 2 (seigneur des chats, des loups, des ours…).',
    resume: 'Frère d\'un groupe animal : lien et communication avec ses animaux, sorts propres (table MN p.76), convocation des frères, forme animale du groupe (MN p.75).' },
  { nom: 'Seigneur verdoyant', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Non mauvais ; Profession (herboriste) 8, Sens de la nature 8 ; dons Commandement des plantes et Répulsion des plantes ; faculté de lancer contrôle des plantes.',
    resume: 'Champion du monde végétal : maîtrise des plantes, peau d\'écorce permanente, corps végétal — progression de sorts : voir table MN p.78 (MN p.77).' },
  { nom: 'Tempête', prestige: true, source: 'Maîtres de la Nature', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['reflexes'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'BBA +9 ; dons Ambidextrie, Arme de prédilection ou Botte secrète, Attaque éclair, Combat à deux armes, Esquive, Souplesse du serpent.',
    resume: 'Tourbillon d\'acier à deux armes : pénalités réduites, CA améliorée en combat à deux armes, attaque tourbillonnante suprême (MN p.80).' },

  // ─── Manuel des Joueurs de Faerûn (p.50-79) ────────────────────────────────
  { nom: 'Agent ménestrel', prestige: true, source: 'MJ de Faerûn', niveauxMax: 5,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['reflexes', 'volonte'], competencesParNiveau: 6, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 5], typeLanceur: 'les-deux',
    conditions: 'Non mauvais ; Connaissances (folklore local) 4, Diplomatie 8, Psychologie 2, Survie 2 ; don Négociation ; parrainage par un Ménestrel.',
    resume: 'Agent secret des Ménestrels : savoir ménestrel, chance de Tymora, immunité aux charmes, sorts des Ménestrels (MF p.51).' },
  { nom: 'Champion divin', prestige: true, source: 'MJ de Faerûn', niveauxMax: 5,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'BBA +7 ; Connaissances (religion) 3 ; don Arme de prédilection (arme du dieu) ; divinité tutélaire dont on est le champion.',
    resume: 'Bras armé de sa divinité : imposition des mains, défense sacrée, dons supplémentaires, châtiment de l\'infidèle (MF p.52).' },
  { nom: 'Chasseur shaaryen', prestige: true, source: 'MJ de Faerûn', niveauxMax: 10,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur', 'reflexes'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Région : le Shaar ; BBA +5 ; Dressage 4, Équitation 8, Survie 8 ; dons Combat monté, Fraternité animale, Pistage, Tir monté.',
    resume: 'Cavalier des grandes plaines : monture liée, tir monté mortel, traque des proies des steppes (MF p.54). Épique (MF p.128) : niveaux 11-20 — bonus d\'Équitation +2 tous les 3 niveaux, don épique tous les 3 niveaux.' },
  { nom: 'Chevalier dragon pourpre', prestige: true, source: 'MJ de Faerûn', niveauxMax: 5,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Ni mauvais ni chaotique ; Cormyr pour région natale ou Connaissances (Cormyr) 8 ; BBA +4 ; Détection 2, Intimidation 1 (voir MF p.55).',
    resume: 'Officier d\'élite du Cormyr : cri de ralliement, courage héroïque, coordination d\'équipe, moral inébranlable (MF p.55).' },
  { nom: 'Dévot profane', prestige: true, source: 'MJ de Faerûn', niveauxMax: 5,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'arcane',
    conditions: 'Art de la magie 8, Connaissances (religion) 8 ; sorts profanes de 4e niveau ; divinité tutélaire (détail MF p.56).',
    resume: 'Lanceur profane au service d\'un dieu : sorts alignés renforcés, faveur enchantée, appel à la divinité (MF p.56).' },
  { nom: 'Disciple divin', prestige: true, source: 'MJ de Faerûn', niveauxMax: 5,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'divin',
    conditions: 'Connaissances (religion) 8, Diplomatie 5 ; sorts divins de 4e niveau ; divinité tutélaire.',
    resume: 'Voix de son dieu : domaine supplémentaire, guérison divine, transcendance finale (devient Extérieur) (MF p.57).' },
  { nom: 'Espion du Zhentarim', prestige: true, source: 'MJ de Faerûn', niveauxMax: 10,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['reflexes', 'volonte'], competencesParNiveau: 6, lanceurSorts: false,
    conditions: 'Mauvais ; Bluff, Contrefaçon, Déguisement et Renseignements (rangs requis MF p.59) ; don Fourberie ; membre du Réseau noir.',
    resume: 'Agent du Réseau noir : identité de couverture, attaque sournoise, contacts zhents, usage du poison (MF p.59).' },
  { nom: 'Gardesort de Lunargent', prestige: true, source: 'MJ de Faerûn', niveauxMax: 5,
    de: 6, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 5], typeLanceur: 'arcane',
    conditions: 'Non mauvais ; Art de la magie 8, Concentration 8 ; dons Magie de guerre et un don de métamagie ; sorts profanes de 4e niveau ; accepté au sein de la Gardesort.',
    resume: 'Protecteur magique de Lunargent : marque de la Gardesort, contresorts experts, sorts défensifs de la cité (MF p.61).' },
  { nom: 'Gardien funéraire évereskan', prestige: true, source: 'MJ de Faerûn', niveauxMax: 5,
    de: 8, bab: 'elevee', bonsSauvegardes: ['vigueur', 'reflexes'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Elfe ; région : Evereska (conditions détaillées MF p.62).',
    resume: 'Sentinelle des cryptes elfiques : bottes contre les morts-vivants, vigilance éternelle, discrétion sacrée (MF p.62).' },
  { nom: 'Hathran', prestige: true, source: 'MJ de Faerûn', niveauxMax: 10,
    de: 6, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'complete', typeLanceur: 'les-deux',
    conditions: 'Loyale bonne, loyale neutre ou neutre bonne ; femme ; région : Rashéménie ; Connaissances 4 ; dons Ethran et Prestige ; sorts divins ou profanes de 4e niveau ; Chauntéa, Mailikki ou Mystra.',
    resume: 'Sorcière dirigeante de Rashéménie (wychlaran) : autorité sur les Rashémis, effroi, incantation en cercle, sorts des sœurs (MF p.64). Épique (MF p.128) : niveaux 11-20 — magie des esprits universelle +1 utilisation/jour tous les 3 niveaux, don épique tous les 2 niveaux ; NLS +1/niveau mais quota de sorts figé au niveau 10.' },
  { nom: 'Incantatrixe', prestige: true, source: 'MJ de Faerûn', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: ['volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 5, 6, 7, 8, 9, 10], typeLanceur: 'arcane',
    conditions: 'Art de la magie 8, Concentration 4, Connaissances (mystères) 8 ; dons Volonté de fer et un don de métamagie ; sorts profanes de 3e niveau.',
    resume: 'Spécialiste de la métamagie : applique la métamagie aux sorts d\'autrui, vol de sorts en cours, immunité métamagique (MF p.66). Épique (MF p.129) : niveaux 11-20 — métamagie instantanée +1 utilisation/jour tous les 2 niveaux, don épique tous les 3 niveaux ; NLS +1/niveau mais quota de sorts figé au niveau 10.' },
  { nom: 'Justiciar de Tyr', prestige: true, source: 'MJ de Faerûn', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'demi', typeLanceur: 'divin',
    conditions: 'Loyal bon ; BBA +4 ; Connaissances (folklore local) 4, Connaissances (religion) 6, Diplomatie (voir MF p.69) ; sorts divins ; Tyr divinité tutélaire.',
    resume: 'Juge-bourreau du dieu de la justice : jugement du coupable, zone de vérité, châtiment du parjure (MF p.69). Épique (MF p.129) : niveaux 11-20 — châtiment de l\'anarchie +1 utilisation/jour tous les 5 niveaux, don épique tous les 3 niveaux ; NLS +1/niveau mais quota de sorts figé au niveau 10.' },
  { nom: 'Lanceur de runes', prestige: true, source: 'MJ de Faerûn', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'partielle', niveauxAvecSorts: [2, 3, 4, 6, 7, 8, 10], typeLanceur: 'divin',
    conditions: 'Art de la magie 8, Artisanat (calligraphie, ferronnerie, taille de pierres ou travail du bois) 8 ; sorts divins de 3e niveau.',
    resume: 'Graveur de magie : inscrit ses sorts en runes durables déclenchées au contact, puissance et permanence runiques (MF p.70). Épique (MF p.130) : niveaux 11-20 — pouvoir runique (DD) et artisanat runique +1 tous les 3 niveaux, don épique tous les 3 niveaux ; le don Inscription de runes épiques est requis pour les runes de 10e niveau ou de NLS supérieur à 20 ; NLS +1/niveau mais quota de sorts figé au niveau 10.' },
  { nom: 'Marteau de Moradin', prestige: true, source: 'MJ de Faerûn', niveauxMax: 10,
    de: 10, bab: 'elevee', bonsSauvegardes: ['vigueur'], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Nain ; région : Épine dorsale du Monde ; BBA +7 ; Artisanat (fabrication d\'armes) 10 ; dons Arme de prédilection (marteau de guerre) et Volonté de fer ; sorts divins de 1er niveau ; Moradin ; membre des marteaux de Moradin.',
    resume: 'Élite guerrière naine : marteau béni, frappe tellurique, ennemis jurés des orques et géants — progression de sorts : voir MF p.72 (MF p.71). Épique (MF p.130) : niveaux 11-20 — don épique tous les 2 niveaux.' },
  { nom: 'Moine de la mort longue', prestige: true, source: 'MJ de Faerûn', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'reflexes', 'volonte'], competencesParNiveau: 4, lanceurSorts: false,
    conditions: 'Non bon ; Artisanat (alchimie), Artisanat (fabrication de poison) 7, Connaissances (mystères) 8, Premiers secours 3 ; intronisation par la cérémonie secrète.',
    resume: 'Étudiant de la mort : toucher de la mort longue, immunité aux poisons et maladies, secrets mortels croissants (MF p.73). Épique (MF p.131) : niveaux 11-20 — DD de l\'attaque mortelle et sauvegarde contre la mort +1 tous les 2 niveaux, don épique tous les 4 niveaux.' },
  { nom: 'Quêteur divin', prestige: true, source: 'MJ de Faerûn', niveauxMax: 5,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['reflexes'], competencesParNiveau: 6, lanceurSorts: false,
    conditions: 'Connaissances (religion) 3, Déplacement silencieux 8, Détection 4, Discrétion 8 ; don Discret ; divinité tutélaire dont on est le quêteur.',
    resume: 'Infiltrateur sacré : récupère les reliques de son Église, chance divine, esquive totale, localisation bénie (MF p.76).' },
  { nom: 'Seigneur de l\'aube de Lathandre', prestige: true, source: 'MJ de Faerûn', niveauxMax: 10,
    de: 8, bab: 'moyenne', bonsSauvegardes: ['vigueur', 'volonte'], competencesParNiveau: 2, lanceurSorts: false,
    progressionSorts: 'demi', typeLanceur: 'divin',
    conditions: 'Bon ; Artisanat 4, Connaissances (religion) 8, Diplomatie 7, Représentation 2 ; don Science du renvoi ; sorts divins de 3e niveau ; Lathandre divinité tutélaire.',
    resume: 'Prêtre de l\'aurore : lumière de l\'aube, renvoi radieux des morts-vivants, aube vivifiante (MF p.77). Épique (MF p.132) : niveaux 11-20 — renvoi suprême +1 utilisation/jour tous les 4 niveaux, don épique tous les 3 niveaux ; NLS +1/niveau mais quota de sorts figé au niveau 10.' },
  { nom: 'Voleur de l\'ombre d\'Amn', prestige: true, source: 'MJ de Faerûn', niveauxMax: 5,
    de: 6, bab: 'moyenne', bonsSauvegardes: ['reflexes'], competencesParNiveau: 8, lanceurSorts: false,
    conditions: 'Bluff 3, Déplacement silencieux 3, Discrétion 8, Intimidation 3, Renseignements 3 ; don Persuasion ; membre de la guilde des Voleurs de l\'ombre.',
    resume: 'Criminel de la plus puissante guilde de Faerûn : attaque sournoise, réputation redoutée, contacts de guilde (MF p.79).' },

  // ─── Manuel des Joueurs de Faerûn — classes de prestige ÉPIQUES (p.133-135) ──
  // Réservées aux personnages de niveau 21 ou plus. Règle épique : la table de
  // classe n'accorde ni BAB ni sauvegardes ; le personnage gagne à la place le
  // bonus épique (+1 à l'attaque et aux sauvegardes tous les 2 niveaux au-delà
  // du 20e) — la progression « faible » ci-dessous en est l'approximation.
  { nom: 'Arcaniste nétherisse', prestige: true, source: 'MJ de Faerûn (épique)', niveauxMax: 5,
    de: 4, bab: 'faible', bonsSauvegardes: [], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Classe ÉPIQUE (niveau 21+) ; humain (y compris mort-vivant) ou reflet ; Art de la magie 25, Connaissances (mystères) 25 ; don Science de l\'emplacement de sort ; faculté de lancer des sorts profanes de 13e niveau ; accès aux traditions magiques de Nétheril (liche ou reflet de l\'empire de Pénombre, ou vieux secrets exhumés).',
    resume: 'Héritier des archimages de Nétheril, pionnier de la magie épique : don Magie épique offert, spécialité parmi trois domaines nétherisses (invention, esprit, fluctuation — le troisième devient inaccessible, DD de développement réduit dans sa spécialité), École renforcée puis supérieure épiques (+2 cumulé au DD des sorts épiques), résistance au contrecoup (5), développement des sorts épiques à 7 000 po par point de DD au lieu de 9 000 (MF p.133).' },
  { nom: 'Hiérophante magefeu', prestige: true, source: 'MJ de Faerûn (épique)', niveauxMax: 10,
    de: 4, bab: 'faible', bonsSauvegardes: [], competencesParNiveau: 2, lanceurSorts: false,
    conditions: 'Classe ÉPIQUE (niveau 21+) ; Art de la magie 12, Concentration 24, Connaissances (mystères) 12 ; dons Arme de prédilection (magefeu), Porteur du magefeu et Porteur du magefeu épique.',
    resume: 'Maître de l\'énergie brute de la Toile : absorbe les charges des objets magiques — même permanents — en énergie magefeu (Volonté annule), guérison à distance, rapidité 1 à 3×/jour, réserve de magefeu indétectable, dons épiques aux niveaux 4 et 8, rayonnement de magefeu final (explosion de 1,50 m, Réflexes ½) (MF p.134).' },
]

export function getPrestigeInfo(nom: string): ClassePrestigeInfo | undefined {
  return PRESTIGE_CLASSES.find(c => c.nom === nom)
}

// Niveau de lanceur effectif d'une classe de base, en comptant les classes de
// prestige à progression de sorts (« +1 niveau de lanceur existant »).
// Le bonus s'applique à la classe de base la plus élevée du type correspondant.
export function getNiveauLanceurEffectif(
  nomClasse: string,
  classesDuPerso: { classe: string; niveau: number }[]
): number {
  const propre = classesDuPerso.find(c => c.classe === nomClasse)?.niveau ?? 0
  if (propre === 0) return 0
  const type = CLASSES_ARCANES.includes(nomClasse) ? 'arcane'
    : CLASSES_DIVINES.includes(nomClasse) ? 'divin' : null
  if (!type) return propre
  const listeType = type === 'arcane' ? CLASSES_ARCANES : CLASSES_DIVINES
  const memesType = classesDuPerso.filter(c => listeType.includes(c.classe))
  const plusHaute = memesType.reduce((best, c) => c.niveau > best.niveau ? c : best, memesType[0])
  if (!plusHaute || plusHaute.classe !== nomClasse) return propre
  let bonus = 0
  for (const c of classesDuPerso) {
    const p = getPrestigeInfo(c.classe)
    if (!p?.progressionSorts) continue
    if (p.typeLanceur === 'les-deux' || p.typeLanceur === type) {
      bonus += p.progressionSorts === 'complete' ? c.niveau
        : p.progressionSorts === 'partielle' ? (p.niveauxAvecSorts ?? []).filter(n => n <= c.niveau).length
        : Math.floor(c.niveau / 2)
    }
  }
  return propre + bonus
}
