export type ClasseSortKey = 'Magicien' | 'Ensorceleur' | 'Prêtre' | 'Druide' | 'Barde' | 'Paladin' | 'Rôdeur'

export interface SortDnD {
  nom: string
  ecole: string
  niveaux: Partial<Record<ClasseSortKey, number>>
  composantes: string
  portee: string
  duree: string
  description: string
}

export const SORTS_DND35: SortDnD[] = [
  // ─── NIVEAU 0 ───
  { nom: 'Détection de la magie',    ecole: 'Divination',    niveaux: { Magicien: 0, Ensorceleur: 0, Prêtre: 0, Druide: 0, Barde: 0 },           composantes: 'V, S',    portee: '18 m (cône)',  duree: 'Concentration (max 1 min/niv)', description: 'Détecte les sorts et objets magiques dans la zone.' },
  { nom: 'Lumière',                  ecole: 'Évocation',     niveaux: { Magicien: 0, Ensorceleur: 0, Prêtre: 0, Barde: 0 },                       composantes: 'V, M/DF', portee: 'Contact',      duree: '10 min/niveau',                description: 'Objet brillant comme une torche.' },
  { nom: 'Résistance',               ecole: 'Abjuration',    niveaux: { Magicien: 0, Ensorceleur: 0, Prêtre: 0, Druide: 0, Barde: 0 },            composantes: 'V, S, M', portee: 'Contact',      duree: '1 minute',                     description: '+1 aux jets de sauvegarde.' },
  { nom: 'Réparation',               ecole: 'Transmutation', niveaux: { Magicien: 0, Ensorceleur: 0, Prêtre: 0, Druide: 0, Barde: 0 },            composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Répare de petits dommages sur un objet.' },
  { nom: 'Manipulation à distance',  ecole: 'Transmutation', niveaux: { Magicien: 0, Ensorceleur: 0, Barde: 0 },                                  composantes: 'V, S',    portee: '9 m',          duree: 'Concentration',                description: 'Soulève ou déplace un objet de 2,5 kg à distance.' },
  { nom: 'Lecture de la magie',      ecole: 'Divination',    niveaux: { Magicien: 0, Ensorceleur: 0, Druide: 0, Barde: 0 },                       composantes: 'V, S, F', portee: 'Personnel',    duree: 'Concentration',                description: 'Lit les inscriptions magiques et les parchemins.' },
  { nom: 'Prestidigitation',         ecole: 'Universel',     niveaux: { Magicien: 0, Ensorceleur: 0, Barde: 0 },                                  composantes: 'V, S',    portee: '3 m',              duree: '1 heure',                      description: 'Effets mineurs : colorier, nettoyer, chauffer, etc.' },
  { nom: 'Message',                  ecole: 'Transmutation', niveaux: { Magicien: 0, Ensorceleur: 0, Barde: 0 },                                  composantes: 'V, S, F', portee: 'Moyen',        duree: '10 min/niveau',                description: 'Chuchote un message à une cible distante.' },
  { nom: 'Son imaginaire',           ecole: 'Illusion',      niveaux: { Magicien: 0, Ensorceleur: 0, Barde: 0 },                                  composantes: 'V, S, M', portee: 'Long',         duree: 'Concentration',                description: 'Crée une illusion sonore.' },
  { nom: 'Stupeur',                  ecole: 'Enchantement',  niveaux: { Magicien: 0, Ensorceleur: 0, Barde: 0 },                                  composantes: 'V, S, M', portee: '9 m',          duree: '1 round',                      description: 'Étourdit une créature avec 4 DV ou moins.' },
  { nom: 'Illumination',             ecole: 'Évocation',     niveaux: { Magicien: 0, Ensorceleur: 0, Barde: 0 },                                  composantes: 'V, M',    portee: 'Long',         duree: '1 min/niveau (D)',             description: 'Crée jusqu\'à 4 lumières dansantes.' },
  { nom: 'Vertu',                    ecole: 'Transmutation', niveaux: { Prêtre: 0 },                                                               composantes: 'V, S, DF', portee: 'Contact',     duree: '1 minute',                     description: 'Accorde 1 point de vie temporaire.' },
  { nom: 'Soins mineurs',            ecole: 'Invocation',    niveaux: { Prêtre: 0 },                                                               composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Soigne 1 point de vie.' },
  { nom: 'Création d\'eau',          ecole: 'Invocation',    niveaux: { Prêtre: 0, Druide: 0 },                                                   composantes: 'V, S',    portee: 'Courte',       duree: 'Instantané',                   description: 'Crée 3,5 litres d\'eau par niveau.' },
  { nom: 'Détection du poison',      ecole: 'Divination',    niveaux: { Prêtre: 0, Druide: 0, Rôdeur: 1 },                                        composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Détecte le poison sur une créature ou un objet.' },
  { nom: 'Guidage',                  ecole: 'Divination',    niveaux: { Prêtre: 0, Druide: 0 },                                                   composantes: 'V, S',    portee: 'Contact',      duree: '1 minute',                     description: '+1 à un test de compétence ou jet d\'attaque.' },
  { nom: 'Sauvegarde contre le feu', ecole: 'Abjuration',    niveaux: { Druide: 0 },                                                              composantes: 'V, S, DF', portee: 'Contact',     duree: '10 min/niveau',                description: 'Réduit les dégâts de feu non magique.' },

  // ─── NIVEAU 1 ───
  { nom: 'Missile magique',          ecole: 'Évocation',     niveaux: { Magicien: 1, Ensorceleur: 1 },                                            composantes: 'V, S',    portee: 'Moyen',        duree: 'Instantané',                   description: '1d4+1 points de dégâts (force). +1 missile par tranche de 2 niveaux au-delà du 1er (max 5).' },
  { nom: 'Bouclier',                 ecole: 'Abjuration',    niveaux: { Magicien: 1, Ensorceleur: 1 },                                            composantes: 'V, S',    portee: 'Personnel',    duree: '1 min/niveau (D)',             description: 'Bouclier invisible ; +4 bouclier à la CA, immunité aux missiles magiques.' },
  { nom: 'Armure de mage',           ecole: 'Invocation',    niveaux: { Magicien: 1, Ensorceleur: 1 },                                            composantes: 'V, S, F', portee: 'Contact',      duree: '1 h/niveau (D)',               description: '+4 armure (force) à la CA.' },
  { nom: 'Sommeil',                  ecole: 'Enchantement',  niveaux: { Magicien: 1, Ensorceleur: 1, Barde: 1 },                                  composantes: 'V, S, M', portee: 'Moyen',        duree: '1 min/niveau',                 description: 'Endort 2d4 DV de créatures dans un rayon de 3 m.' },
  { nom: 'Charme-personne',          ecole: 'Enchantement',  niveaux: { Magicien: 1, Ensorceleur: 1, Barde: 1 },                                  composantes: 'V, S',    portee: 'Courte',       duree: '1 h/niveau',                   description: 'La cible vous considère comme un ami (JS Volonté annule).' },
  { nom: 'Mains brûlantes',          ecole: 'Évocation',     niveaux: { Magicien: 1, Ensorceleur: 1 },                                            composantes: 'V, S',    portee: 'Personnelle (cône 4,5 m)', duree: 'Instantané',  description: '1d4 dégâts de feu/niveau (max 5d4). JS Réflexes pour 1/2.' },
  { nom: 'Rayon de givre',           ecole: 'Évocation',     niveaux: { Magicien: 0, Ensorceleur: 0 },                                            composantes: 'V, S',    portee: 'Courte',       duree: 'Instantané',                   description: 'Jet d\'attaque de contact à distance : 1d3 dégâts de froid.' },
  { nom: 'Image silencieuse',        ecole: 'Illusion',      niveaux: { Magicien: 1, Ensorceleur: 1, Barde: 1 },                                  composantes: 'V, S, F', portee: 'Long',         duree: 'Concentration',                description: 'Crée une illusion visuelle sans son.' },
  { nom: 'Alarme',                   ecole: 'Abjuration',    niveaux: { Magicien: 1, Ensorceleur: 1, Rôdeur: 1 },                                 composantes: 'V, S, F', portee: 'Courte',       duree: '2 h/niveau (D)',               description: 'Alerte mentale ou sonore si une créature entre dans la zone.' },
  { nom: 'Identification',           ecole: 'Divination',    niveaux: { Magicien: 1, Ensorceleur: 1, Barde: 1 },                                  composantes: 'V, S, M', portee: 'Contact',      duree: 'Instantané',                   description: 'Identifie les propriétés d\'un objet magique.' },
  { nom: 'Feuille morte',            ecole: 'Transmutation', niveaux: { Magicien: 1, Ensorceleur: 1, Druide: 1 },                                 composantes: 'V',       portee: 'Courte',       duree: 'Jusqu\'à l\'atterrissage',     description: 'Annule la chute de plusieurs créatures.' },
  { nom: 'Repli expéditif',          ecole: 'Transmutation', niveaux: { Magicien: 1, Ensorceleur: 1, Barde: 1 },                                  composantes: 'V, S',    portee: 'Personnel',    duree: '1 min/niveau (D)',             description: 'Augmente votre déplacement de 9 m.' },
  { nom: 'Nappe de brouillard',      ecole: 'Invocation',    niveaux: { Magicien: 1, Ensorceleur: 1, Druide: 1, Prêtre: 1 },                      composantes: 'V, S',    portee: 'Courte',       duree: '1 min/niveau',                 description: 'Brouillard qui bloque la vue (4,5 m de rayon).' },
  { nom: 'Rayon affaiblissant',      ecole: 'Nécromancie',   niveaux: { Magicien: 1, Ensorceleur: 1 },                                            composantes: 'V, S',    portee: 'Courte',       duree: '1 round/niveau',               description: 'Réduit la Force de 1d6 points + 1/2 niveau.' },
  { nom: 'Couleurs dansantes',       ecole: 'Illusion',      niveaux: { Magicien: 1, Ensorceleur: 1 },                                            composantes: 'V, S, M', portee: '3 m (cône)',   duree: 'Concentration + 2 rounds',     description: 'Aveugle et étourdit les créatures ayant peu de DV.' },
  { nom: 'Hypnotisme',               ecole: 'Enchantement',  niveaux: { Magicien: 1, Ensorceleur: 1, Barde: 1 },                                  composantes: 'V, S',    portee: 'Courte',       duree: '2d4 rounds (D)',               description: 'Fascine 2d4 DV de créatures.' },
  { nom: 'Frayeur',                  ecole: 'Nécromancie',   niveaux: { Magicien: 1, Ensorceleur: 1, Barde: 1 },                                  composantes: 'V, S, M', portee: 'Courte',       duree: '1 round/niveau',               description: 'Une seule cible est apeurée (JS Volonté annule).' },
  { nom: 'Compréhension des langages', ecole: 'Divination', niveaux: { Magicien: 1, Ensorceleur: 1, Barde: 1, Prêtre: 1 },                       composantes: 'V, S, M/DF', portee: 'Personnel', duree: '10 min/niveau',                description: 'Comprend toutes les langues écrites et parlées.' },
  { nom: 'Ventriloquie',             ecole: 'Illusion',      niveaux: { Magicien: 1, Ensorceleur: 1, Barde: 1 },                                  composantes: 'V, F',    portee: 'Courte',       duree: '1 min/niveau (D)',             description: 'Fait paraître votre voix venir d\'ailleurs.' },
  { nom: 'Soins légers',             ecole: 'Invocation',    niveaux: { Prêtre: 1, Druide: 1, Barde: 1, Paladin: 1, Rôdeur: 1 },                  composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Soigne 1d8 + modificateur de sagesse (max 1/niv) PV.' },
  { nom: 'Bénédiction',              ecole: 'Enchantement',  niveaux: { Prêtre: 1, Paladin: 1 },                                                  composantes: 'V, S, DF', portee: '15 m',        duree: '1 min/niveau',                 description: '+1 aux jets d\'attaque et aux jets de sauvegarde contre la peur pour vos alliés.' },
  { nom: 'Malédiction',              ecole: 'Enchantement',  niveaux: { Prêtre: 1 },                                                              composantes: 'V, S, DF', portee: '15 m',        duree: '1 min/niveau',                 description: '-1 aux jets d\'attaque et aux jets de sauvegarde des ennemis.' },
  { nom: 'Commandement',             ecole: 'Enchantement',  niveaux: { Prêtre: 1 },                                                              composantes: 'V',       portee: 'Courte',       duree: '1 round',                      description: 'Ordonne à une créature d\'approcher, lâcher, fuir, tomber ou s\'arrêter.' },
  { nom: 'Bouclier de la foi',       ecole: 'Abjuration',    niveaux: { Prêtre: 1 },                                                              composantes: 'V, S, M', portee: 'Contact',      duree: '1 min/niveau',                 description: 'Bonus de déviation de +2 à la CA (améliore aux niveaux supérieurs).' },
  { nom: 'Protection contre le Mal', ecole: 'Abjuration',    niveaux: { Prêtre: 1, Paladin: 1, Magicien: 1, Ensorceleur: 1 },                     composantes: 'V, S, M/DF', portee: 'Contact',  duree: '1 min/niveau (D)',             description: '+2 CA et jets de sauvegarde contre le Mal ; protège des créatures Mauvaises.' },
  { nom: 'Sanctuaire',               ecole: 'Abjuration',    niveaux: { Prêtre: 1 },                                                              composantes: 'V, S, DF', portee: 'Contact',     duree: '1 round/niveau',               description: 'Les adversaires doivent réussir un JS Volonté pour vous attaquer.' },
  { nom: 'Mort imminente',           ecole: 'Nécromancie',   niveaux: { Prêtre: 1 },                                                              composantes: 'V, S, DF', portee: 'Moyen',       duree: '1 min/niveau',                 description: 'Une cible est terrifiée (-2 jets d\'attaque/de sauvegarde/aux tests).' },
  { nom: 'Faveur divine',            ecole: 'Évocation',     niveaux: { Prêtre: 1, Paladin: 1 },                                                  composantes: 'V, S, DF', portee: 'Personnel',   duree: '1 minute',                     description: '+1 aux jets d\'attaque et aux dégâts par tranche de 3 niveaux (max +3).' },
  { nom: 'Enchevêtrement',           ecole: 'Transmutation', niveaux: { Druide: 1, Rôdeur: 1 },                                                   composantes: 'V, S, DF', portee: 'Long',        duree: '1 min/niveau (D)',             description: 'Plantes qui immobilisent les créatures (JS Force ou immobilisé).' },
  { nom: 'Soin des animaux',         ecole: 'Invocation',    niveaux: { Druide: 1, Rôdeur: 1 },                                                   composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Soigne 1d8+1/niv (max +5) PV à un animal.' },
  { nom: 'Appel d\'armes',           ecole: 'Évocation',     niveaux: { Paladin: 1 },                                                             composantes: 'V, S',    portee: 'Contact',      duree: '1 min/niveau',                 description: 'Arme consacrée qui brûle les morts-vivants (+2d6 dégâts).' },
  { nom: 'Détection du Mal',         ecole: 'Divination',    niveaux: { Prêtre: 1, Paladin: 1 },                                                  composantes: 'V, S, DF', portee: '18 m (cône)', duree: 'Concentration (max 10 min/niv)', description: 'Détecte les créatures, sorts et objets mauvais.' },
  { nom: 'Grâce du félin',           ecole: 'Transmutation', niveaux: { Druide: 1, Barde: 2, Rôdeur: 1 },                                         composantes: 'V, S, M', portee: 'Contact',      duree: '1 min/niveau',                 description: '+4 à la Dextérité.' },
  { nom: 'Dissonance de chuchoteurs', ecole: 'Évocation',    niveaux: { Barde: 0 },                                                               composantes: 'V',       portee: 'Courte',       duree: '1 round/niveau',               description: 'Cloche douloureuse autour d\'une cible (JS Vigueur ou -1 aux jets).' },

  // ─── NIVEAU 2 ───
  { nom: 'Invisibilité',             ecole: 'Illusion',      niveaux: { Magicien: 2, Ensorceleur: 2, Barde: 2 },                                  composantes: 'V, S, M/DF', portee: 'Personnel ou contact', duree: '1 min/niveau (D)', description: 'La cible devient invisible jusqu\'à ce qu\'elle attaque.' },
  { nom: 'Image miroir',             ecole: 'Illusion',      niveaux: { Magicien: 2, Ensorceleur: 2, Barde: 2 },                                  composantes: 'V, S',    portee: 'Personnel',    duree: '1 min/niveau',                 description: '1d4+1 doubles illusoires. Chaque attaque ratée détruit un double.' },
  { nom: 'Toile d\'araignée',        ecole: 'Invocation',    niveaux: { Magicien: 2, Ensorceleur: 2 },                                            composantes: 'V, S, M', portee: 'Moyen',        duree: '10 min/niveau (D)',            description: 'Toiles collantes qui gênent le déplacement (FOR 20 pour se libérer).' },
  { nom: 'Force de taureau',         ecole: 'Transmutation', niveaux: { Magicien: 2, Ensorceleur: 2, Prêtre: 2, Druide: 2, Paladin: 2, Rôdeur: 2 }, composantes: 'V, S, M/DF', portee: 'Contact', duree: '1 min/niveau',              description: '+4 à la Force.' },
  { nom: 'Grâce du chat',            ecole: 'Transmutation', niveaux: { Magicien: 2, Ensorceleur: 2, Prêtre: 2, Druide: 2, Rôdeur: 2 },           composantes: 'V, S, M/DF', portee: 'Contact', duree: '1 min/niveau',                description: '+4 à la Dextérité.' },
  { nom: 'Rayon ardent',             ecole: 'Évocation',     niveaux: { Magicien: 2, Ensorceleur: 2 },                                            composantes: 'V, S',    portee: 'Courte',       duree: 'Instantané',                   description: '1 rayon d\'énergie ardente (4d6) par tranche de 4 niveaux (max 3).' },
  { nom: 'Flèche acide de Melf',     ecole: 'Invocation',    niveaux: { Magicien: 2, Ensorceleur: 2 },                                            composantes: 'V, S, M, F', portee: 'Long',     duree: 'Voir description',             description: 'Flèche magique : 2d4 dégâts d\'acide + 2d4 par round pendant 1 round/3 niveaux.' },
  { nom: 'Verrou de mage',           ecole: 'Abjuration',    niveaux: { Magicien: 2, Ensorceleur: 2 },                                            composantes: 'V, S, GP', portee: 'Contact',     duree: 'Permanent',                    description: 'Ferme et verrouille magiquement une porte ou coffre.' },
  { nom: 'Détection des pensées',    ecole: 'Divination',    niveaux: { Magicien: 2, Ensorceleur: 2, Barde: 2, Prêtre: 3 },                       composantes: 'V, S, F/DF', portee: '27 m',     duree: 'Concentration (max 1 min/niv)', description: 'Lit les pensées de surface des créatures à portée.' },
  { nom: 'Résistance aux énergies',  ecole: 'Abjuration',    niveaux: { Magicien: 2, Ensorceleur: 2, Prêtre: 2, Druide: 2, Paladin: 2, Rôdeur: 1 }, composantes: 'V, S, M', portee: 'Contact',   duree: '10 min/niveau',               description: 'Résistance 10 à un type d\'énergie (améliorée aux niv. 7 et 11).' },
  { nom: 'Endurance de l\'ours',     ecole: 'Transmutation', niveaux: { Magicien: 2, Ensorceleur: 2, Prêtre: 2, Druide: 2, Paladin: 2, Rôdeur: 2 }, composantes: 'V, S, M/DF', portee: 'Contact', duree: '1 min/niveau',             description: '+4 à la Constitution.' },
  { nom: 'Fracassement',             ecole: 'Évocation',     niveaux: { Magicien: 2, Ensorceleur: 2, Barde: 2, Prêtre: 2 },                       composantes: 'V, S, M', portee: 'Courte',       duree: 'Instantané',                   description: 'Détruit ou endommage les objets et constructions (2d6 + 1/niv, max 10d6).' },
  { nom: 'Sphère d\'obscurité',      ecole: 'Évocation',     niveaux: { Magicien: 2, Ensorceleur: 2, Prêtre: 2 },                                 composantes: 'V, M/DF', portee: 'Contact',      duree: '1 min/niveau (D)',             description: 'Ténèbres magiques dans un rayon de 6 m (supplante la lumière naturelle).' },
  { nom: 'Vision dans le noir',      ecole: 'Transmutation', niveaux: { Magicien: 2, Ensorceleur: 2, Rôdeur: 3, Druide: 3 },                      composantes: 'V, S, M', portee: 'Contact',      duree: '1 h/niveau',                   description: 'Vision dans le noir jusqu\'à 18 m.' },
  { nom: 'Réduction de personne',    ecole: 'Transmutation', niveaux: { Magicien: 2, Ensorceleur: 2 },                                            composantes: 'V, S, M', portee: 'Courte',       duree: '1 min/niveau (D)',             description: 'Réduit la taille d\'une créature humanoïde (malus FOR, bonus DEX, taille P).' },
  { nom: 'Pyrotechnie',              ecole: 'Transmutation', niveaux: { Magicien: 2, Ensorceleur: 2, Druide: 2 },                                  composantes: 'V, S, M', portee: 'Long',         duree: 'Instantané',                   description: 'Feux d\'artifice ou nuage de fumée à partir d\'un feu existant.' },
  { nom: 'Soins modérés',            ecole: 'Invocation',    niveaux: { Prêtre: 2, Druide: 3, Barde: 3, Paladin: 3, Rôdeur: 3 },                  composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Soigne 2d8 + 1/niv (max +10) PV.' },
  { nom: 'Immobilisation de personne', ecole: 'Enchantement', niveaux: { Magicien: 3, Ensorceleur: 3, Prêtre: 2, Barde: 2 },                      composantes: 'V, S, M/DF', portee: 'Moyen',   duree: '1 round/niveau (D)',            description: 'Paralyse un humanoïde (JS Volonté annule).' },
  { nom: 'Aide',                     ecole: 'Enchantement',  niveaux: { Prêtre: 2 },                                                              composantes: 'V, S, DF', portee: 'Contact',     duree: '1 min/niveau',                 description: '+1 aux jets d\'attaque et de sauvegarde contre la peur, +1d8 PV temp.' },
  { nom: 'Lame de feu',              ecole: 'Évocation',     niveaux: { Druide: 2 },                                                              composantes: 'V, S, DF', portee: '0 m',         duree: '1 min/niveau (D)',             description: 'Lame enflammée dans la main qui inflige 1d8+1/2 niv dégâts de feu.' },
  { nom: 'Sens de la nature',        ecole: 'Divination',    niveaux: { Druide: 2, Rôdeur: 2 },                                                   composantes: 'V, S',    portee: 'Personnel',    duree: '1 min/niveau',                 description: 'Perception des animaux et plantes à 9 m. +4 aux tests d\'Initiative.' },
  { nom: 'Invisibilité totale',      ecole: 'Illusion',      niveaux: { Barde: 3, Magicien: 4, Ensorceleur: 4 },                                  composantes: 'V, S, M/DF', portee: 'Personnel ou contact', duree: '1 min/niveau (D)', description: 'Invisible même lors des attaques.' },
  { nom: 'Suggestion',               ecole: 'Enchantement',  niveaux: { Magicien: 3, Ensorceleur: 3, Barde: 2 },                                  composantes: 'V, M',    portee: 'Courte',       duree: '1 heure/niveau',               description: 'Implante une suggestion raisonnée (JS Volonté annule).' },

  // ─── NIVEAU 3 ───
  { nom: 'Boule de feu',             ecole: 'Évocation',     niveaux: { Magicien: 3, Ensorceleur: 3 },                                            composantes: 'V, S, M', portee: 'Long',         duree: 'Instantané',                   description: '1d6/niveau dégâts de feu (max 10d6) dans un rayon de 6 m. JS Réflexes pour 1/2.' },
  { nom: 'Éclair',                   ecole: 'Évocation',     niveaux: { Magicien: 3, Ensorceleur: 3 },                                            composantes: 'V, S, M', portee: 'Moyen (30 m ligne)', duree: 'Instantané',          description: '1d6/niveau dégâts d\'électricité (max 10d6). JS Réflexes pour 1/2.' },
  { nom: 'Hâte',                     ecole: 'Transmutation', niveaux: { Magicien: 3, Ensorceleur: 3, Barde: 3 },                                  composantes: 'V, S, M', portee: 'Courte',       duree: '1 round/niveau',               description: 'Un sujet/niv : +1 att, +1 CA, +1 jets de réflexes, +9 m déplacement, attaque supplémentaire.' },
  { nom: 'Ralentissement',           ecole: 'Transmutation', niveaux: { Magicien: 3, Ensorceleur: 3, Barde: 3 },                                  composantes: 'V, S, M', portee: 'Courte',       duree: '1 round/niveau',               description: '1 sujet/niv : −1 att et CA, −1 réflexes, demi-action seulement.' },
  { nom: 'Vol',                      ecole: 'Transmutation', niveaux: { Magicien: 3, Ensorceleur: 3 },                                            composantes: 'V, S, F', portee: 'Contact',      duree: '1 min/niveau (D)',             description: 'Vole à 18 m/round (bonne manoeuvrabilité).' },
  { nom: 'Dissipation de la magie',  ecole: 'Abjuration',    niveaux: { Magicien: 3, Ensorceleur: 3, Prêtre: 3, Druide: 4, Barde: 4 },            composantes: 'V, S',    portee: 'Moyen',        duree: 'Instantané',                   description: 'Tente de dissiper un effet magique (test de dissipation).' },
  { nom: 'Protection contre les énergies', ecole: 'Abjuration', niveaux: { Magicien: 3, Ensorceleur: 3, Prêtre: 3, Druide: 3, Rôdeur: 2 },       composantes: 'V, S, DF', portee: 'Contact',     duree: '10 min/niveau',                description: 'Absorbe jusqu\'à 12 points de dégâts/niv (max 120) d\'un type d\'énergie.' },
  { nom: 'Forme gazeuse',            ecole: 'Transmutation', niveaux: { Magicien: 3, Ensorceleur: 3, Barde: 3 },                                  composantes: 'S, M/DF', portee: 'Contact',      duree: '2 min/niveau (D)',             description: 'Cible devient gazeuse (immunité à la plupart des attaques, déplacement 3 m).' },
  { nom: 'Clairvoyance/Clairaudience', ecole: 'Divination',  niveaux: { Magicien: 3, Ensorceleur: 3, Barde: 3, Prêtre: 4 },                      composantes: 'V, S, F/DF', portee: 'Long',     duree: '1 min/niveau (D)',             description: 'Vision ou audition dans un lieu connu à longue distance.' },
  { nom: 'Respiration aquatique',    ecole: 'Transmutation', niveaux: { Magicien: 3, Ensorceleur: 3, Druide: 3, Prêtre: 3, Rôdeur: 3 },           composantes: 'V, S, M', portee: 'Contact',      duree: '2 h/niveau',                   description: 'Respirer sous l\'eau comme à l\'air libre.' },
  { nom: 'Vision magique',           ecole: 'Divination',    niveaux: { Magicien: 3, Ensorceleur: 3 },                                            composantes: 'V, S, M', portee: 'Personnel',    duree: '1 min/niveau (D)',             description: 'Voit les auras magiques, leurs écoles et leurs intensités.' },
  { nom: 'Image immatérielle',       ecole: 'Illusion',      niveaux: { Magicien: 3, Ensorceleur: 3, Barde: 3 },                                  composantes: 'V, S, F', portee: 'Long',         duree: 'Concentration + 3 rounds',     description: 'Illusion visuelle, sonore, olfactive ou thermique.' },
  { nom: 'Soins importants',         ecole: 'Invocation',    niveaux: { Prêtre: 3, Druide: 4, Paladin: 4 },                                       composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Soigne 3d8 + 1/niv (max +15) PV.' },
  { nom: 'Appel des foudres',        ecole: 'Évocation',     niveaux: { Druide: 3 },                                                              composantes: 'V, S',    portee: 'Moyen',        duree: '1 min/niveau',                 description: '3d6 dégâts d\'électricité par round (JS Réflexes pour 1/2).' },
  { nom: 'Brume de corrosion',       ecole: 'Invocation',    niveaux: { Druide: 3 },                                                              composantes: 'V, S',    portee: 'Courte',       duree: '1 round/niveau',               description: 'Brouillard corrosif qui inflige 2d6 acide/round à ceux à l\'intérieur.' },
  { nom: 'Délivrance des malédictions', ecole: 'Abjuration', niveaux: { Prêtre: 3, Paladin: 3 },                                                  composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Supprime toutes les malédictions sur la cible.' },
  { nom: 'Prière',                   ecole: 'Enchantement',  niveaux: { Prêtre: 3, Paladin: 3 },                                                  composantes: 'V, S, DF', portee: '9 m',         duree: '1 round/niveau',               description: '+1 jets d\'att, dégâts, comp. et saves pour alliés ; −1 pour ennemis.' },

  // ─── NIVEAU 4 ───
  { nom: 'Dimension porte',          ecole: 'Invocation',    niveaux: { Magicien: 4, Ensorceleur: 4, Barde: 4 },                                  composantes: 'V',       portee: 'Long',         duree: 'Instantané',                   description: 'Téléporte jusqu\'à 2 créatures à un emplacement connu à portée.' },
  { nom: 'Peau de pierre',           ecole: 'Abjuration',    niveaux: { Magicien: 4, Ensorceleur: 4, Druide: 6 },                                 composantes: 'V, S, M', portee: 'Contact',      duree: '10 min/niveau',                description: 'Réduction de dégâts 10/adamantine (max 150 points absorbés).' },
  { nom: 'Bouclier de feu',          ecole: 'Évocation',     niveaux: { Magicien: 4, Ensorceleur: 4 },                                            composantes: 'V, S, M', portee: 'Personnel',    duree: '1 round/niveau (D)',           description: 'Flammes protectrices : qui vous frappe au corps à corps subit 1d6+1/niv dégâts. Version chaude (résistance au froid, dégâts de feu) ou froide (résistance au feu, dégâts de froid).' },
  { nom: 'Confusion',                ecole: 'Enchantement',  niveaux: { Magicien: 4, Ensorceleur: 4, Barde: 3, Prêtre: 4 },                       composantes: 'V, S, M/DF', portee: 'Moyen',   duree: '1 round/niveau',               description: 'Confond les créatures dans un rayon de 4,5 m (comportement aléatoire).' },
  { nom: 'Globe d\'invulnérabilité mineur', ecole: 'Abjuration', niveaux: { Magicien: 4, Ensorceleur: 4 },                                       composantes: 'V, S, M', portee: 'Personnel',    duree: '1 round/niveau (D)',           description: 'Protège contre les sorts de niveau 1-3 (les sorts plus puissants passent).' },
  { nom: 'Peur',                     ecole: 'Nécromancie',   niveaux: { Magicien: 4, Ensorceleur: 4, Barde: 3 },                                  composantes: 'V, S, M', portee: '9 m (cône)',   duree: '1 round/niveau',               description: 'Toutes les créatures dans le cône fuient (JS Volonté annule).' },
  { nom: 'Charme-monstre',           ecole: 'Enchantement',  niveaux: { Magicien: 4, Ensorceleur: 4, Barde: 3 },                                  composantes: 'V, S',    portee: 'Courte',       duree: '1 jour/niveau',                description: 'Comme Charme-personne mais sur n\'importe quelle créature.' },
  { nom: 'Scrutation',               ecole: 'Divination',    niveaux: { Magicien: 4, Ensorceleur: 4, Barde: 3, Prêtre: 5, Druide: 4, Rôdeur: 4 }, composantes: 'V, S, M/F', portee: 'Voir desc.', duree: '1 min/niveau',                description: 'Observe une créature ou un lieu à travers une surface magique.' },
  { nom: 'Œil du mage',              ecole: 'Divination',    niveaux: { Magicien: 4, Ensorceleur: 4 },                                            composantes: 'V, S, M', portee: 'Illimitée',    duree: '1 min/niveau (D)',             description: 'Œil invisible qui se déplace à 9 m/round et envoie des perceptions.' },
  { nom: 'Métamorphose',             ecole: 'Transmutation', niveaux: { Magicien: 4, Ensorceleur: 4, Druide: 4 },                                 composantes: 'V, S, M', portee: 'Contact',      duree: '1 min/niveau (D)',             description: 'Transforme la cible en une autre créature (peut acquérir pouvoirs et FOR, DEX, CON).' },
  { nom: 'Mur de feu',               ecole: 'Évocation',     niveaux: { Magicien: 4, Ensorceleur: 4, Druide: 5 },                                 composantes: 'V, S, M/DF', portee: 'Moyen',   duree: 'Concentration + 1 round/niv',  description: 'Mur de feu : 2d4 feu au passage (côté choisi) ou 1d4 (autre côté).' },
  { nom: 'Soins critiques',          ecole: 'Invocation',    niveaux: { Prêtre: 4, Druide: 5 },                                                   composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Soigne 4d8 + 1/niv (max +20) PV.' },
  { nom: 'Immunité aux énergies',    ecole: 'Abjuration',    niveaux: { Prêtre: 4, Druide: 4 },                                                   composantes: 'V, S, DF', portee: 'Contact',     duree: '24 heures',                    description: 'Immunité totale à un type d\'énergie (froid, feu, acide, électricité, son).' },
  { nom: 'Liberté de mouvement',     ecole: 'Abjuration',    niveaux: { Prêtre: 4, Druide: 4, Barde: 4, Rôdeur: 4 },                              composantes: 'V, S, M, DF', portee: 'Contact', duree: '10 min/niveau',                description: 'Libre de se déplacer normalement malgré la magie ou les difficultés naturelles.' },

  // ─── NIVEAU 5 ───
  { nom: 'Téléportation',            ecole: 'Invocation',    niveaux: { Magicien: 5, Ensorceleur: 5 },                                            composantes: 'V',       portee: 'Contact',      duree: 'Instantané',                   description: 'Téléporte jusqu\'à 3 créatures vers un lieu connu (risque d\'erreur).' },
  { nom: 'Cône de froid',            ecole: 'Évocation',     niveaux: { Magicien: 5, Ensorceleur: 5 },                                            composantes: 'V, S, M/F', portee: '12 m (cône)', duree: 'Instantané',                 description: '1d6/niv dégâts de froid (max 15d6). JS Réflexes pour 1/2.' },
  { nom: 'Domination de personne',   ecole: 'Enchantement',  niveaux: { Magicien: 5, Ensorceleur: 5, Barde: 4 },                                  composantes: 'V, S',    portee: 'Courte',       duree: '1 jour/niveau',                description: 'Contrôle mentalement un humanoïde (JS Volonté annule).' },
  { nom: 'Mur de force',             ecole: 'Évocation',     niveaux: { Magicien: 5, Ensorceleur: 5 },                                            composantes: 'V, S, M', portee: 'Courte',       duree: '1 round/niveau (D)',           description: 'Paroi de force invisible. Résistance 30 dégâts. Impassable.' },
  { nom: 'Nuage mortel',             ecole: 'Invocation',    niveaux: { Magicien: 5, Ensorceleur: 5 },                                            composantes: 'V, S',    portee: 'Moyen',        duree: '1 min/niveau',                 description: 'Brouillard dense : 1d10 poison/round. Déplace avec le vent.' },
  { nom: 'Télékinésie',              ecole: 'Transmutation', niveaux: { Magicien: 5, Ensorceleur: 5 },                                            composantes: 'V, S',    portee: 'Long',         duree: 'Concentration + 1 round/niv',  description: 'Soulève et déplace des objets ou créatures à distance (For +11).' },
  { nom: 'Aura mortelle',            ecole: 'Nécromancie',   niveaux: { Prêtre: 5 },                                                              composantes: 'V, S, DF', portee: 'Personnel',   duree: '1 round/niveau (D)',           description: '1d6/niv dégâts (max 10d6) aux créatures vivantes à 9 m (JS Vigueur pour 1/2).' },
  { nom: 'Résurrection partielle',   ecole: 'Invocation',    niveaux: { Prêtre: 5 },                                                              composantes: 'V, S, M, DF', portee: 'Contact', duree: 'Instantané',                   description: 'Ramène à la vie une créature morte (perd un niveau).' },
  { nom: 'Fléau des insectes',       ecole: 'Invocation',    niveaux: { Druide: 5, Prêtre: 5 },                                                   composantes: 'V, S, DF', portee: 'Long',        duree: '1 min/niveau',                 description: 'Nuage d\'insectes : 1 dégât/round + aveugle toute créature à l\'intérieur.' },
  { nom: 'Transmutation de boue',    ecole: 'Transmutation', niveaux: { Magicien: 5, Ensorceleur: 5, Druide: 4 },                                 composantes: 'V, S, M/DF', portee: 'Moyen',   duree: 'Permanent',                    description: 'Transforme un volume de 3×3 m de roche en boue ou vice-versa.' },
  { nom: 'Guérison',                 ecole: 'Invocation',    niveaux: { Prêtre: 6, Druide: 7 },                                                   composantes: 'V, S',    portee: 'Contact',      duree: 'Instantané',                   description: 'Soigne 10 points de vie/niveau (max 150). Élimine maladies et affaiblissements.' },
  { nom: 'Barrière de lames',        ecole: 'Évocation',     niveaux: { Prêtre: 6 },                                                              composantes: 'V, S, DF', portee: 'Moyen',       duree: '1 round/niveau (D)',           description: 'Mur de lames tournoyantes : 7d8 dégâts (JS Réflexes pour 1/2).' },

  // ─── Sorts divins manquants — niveaux 2-5 ───
  { nom: 'Agonie',                   ecole: 'Nécromancie',   niveaux: { Prêtre: 2 },                                                               composantes: 'V, S, DF', portee: 'Contact',      duree: 'Instantané',                   description: 'Tue une créature mourante et vous donne +2d6 PV temporaires et +1 att/dégâts pour 10 min.' },
  { nom: 'Lumière du jour',          ecole: 'Évocation',     niveaux: { Prêtre: 3, Druide: 3 },                                                    composantes: 'V, S',    portee: 'Contact',      duree: '10 min/niveau (D)',            description: 'Lumière aussi brillante que le plein jour dans un rayon de 18 m.' },
  { nom: 'Malédiction',              ecole: 'Nécromancie',   niveaux: { Prêtre: 3, Magicien: 4, Ensorceleur: 4 },                                  composantes: 'V, S, DF', portee: 'Contact',      duree: 'Permanent',                    description: 'Inflige une malédiction : −6 à une caractéristique, ou −4 aux attaques/sauvegardes/tests (JS Volonté annule).' },
  { nom: 'Neutralisation du poison', ecole: 'Invocation',    niveaux: { Prêtre: 4, Druide: 3, Paladin: 4, Rôdeur: 3 },                            composantes: 'V, S, DF', portee: 'Contact',      duree: 'Instantané',                   description: 'Neutralise le poison dans le corps d\'une créature ou sur un objet.' },
  { nom: 'Colonne de flammes',       ecole: 'Évocation',     niveaux: { Prêtre: 5, Druide: 4 },                                                    composantes: 'V, S, DF', portee: 'Moyen',        duree: 'Instantané',                   description: 'Colonne de feu divine : 1d6/niv dégâts (max 15d6), la moitié feu/la moitié divin. JS Réflexes pour 1/2.' },
  { nom: 'Communion',                ecole: 'Divination',    niveaux: { Prêtre: 5 },                                                               composantes: 'V, S, M', portee: 'Personnel',    duree: '1 min',                        description: 'Pose 1 question oui/non par niveau à votre divinité (max 15 questions). Réponse garantie.' },
  { nom: 'Soins légers de groupe',   ecole: 'Invocation',    niveaux: { Prêtre: 5, Druide: 6 },                                                    composantes: 'V, S',    portee: 'Courte',       duree: 'Instantané',                   description: 'Soigne 1d8 + 1/niv (max +25) à toutes les créatures alliées dans un rayon de 9 m.' },
  { nom: 'Châtiment',                ecole: 'Nécromancie',   niveaux: { Prêtre: 6 },                                                               composantes: 'V, S, DF', portee: 'Contact',      duree: 'Instantané',                   description: 'Inflige 10 points de dégâts/niveau (max 150) et −1d4 à toutes les caractéristiques (JS Vigueur pour dégâts seulement).' },
  { nom: 'Festin des héros',         ecole: 'Invocation',    niveaux: { Prêtre: 6 },                                                               composantes: 'V, S, DF', portee: 'Courte',       duree: '1 heure puis 12 heures',       description: 'Repas pour 1 créature/niv : immunité peur et poison, +1 morale att/saves, +2d8 PV temporaires (effets pendant 12 h).' },
  { nom: 'Parole de rappel',         ecole: 'Invocation',    niveaux: { Prêtre: 6, Druide: 8 },                                                    composantes: 'V',       portee: 'Illimitée',    duree: 'Instantané',                   description: 'Téléporte le lanceur et jusqu\'à alliés consentants vers son sanctuaire désigné. Aucun risque d\'erreur.' },
  { nom: 'Injonction de groupe',     ecole: 'Enchantement',  niveaux: { Prêtre: 6 },                                                               composantes: 'V, S, DF', portee: 'Moyen',        duree: '1 round/niveau',               description: 'Comme Immobilisation de personne mais affecte 1 humanoïde/niv dans un rayon de 9 m (JS Volonté annule).' },
  { nom: 'Quête',                    ecole: 'Enchantement',  niveaux: { Prêtre: 6 },                                                               composantes: 'V',       portee: 'Courte',       duree: '1 jour/niv ou jusqu\'à libération', description: 'Oblige la cible à accomplir une mission sous peine de malédiction (JS Volonté annule, DD élevé).' },
  { nom: 'Trouver le chemin',        ecole: 'Divination',    niveaux: { Prêtre: 6, Druide: 6, Barde: 6 },                                         composantes: 'V, S, F', portee: 'Personnel ou contact', duree: '10 min/niveau',        description: 'Indique le chemin le plus court et direct vers un lieu connu.' },
  { nom: 'Concordance des éléments', ecole: 'Invocation',    niveaux: { Prêtre: 6, Druide: 4 },                                                    composantes: 'V, S, DF', portee: 'Courte',       duree: '1 round/niveau',               description: 'Invoque 1 élémentaire de taille G ou 1d3 moyens ou 1d4+1 petits pour combattre.' },
  { nom: 'Prière exaucée',           ecole: 'Invocation',    niveaux: { Prêtre: 6 },                                                               composantes: 'V, S, DF', portee: 'Contact',      duree: '1 min/niveau',                 description: 'Contacte un être planaire allié de votre foi pour obtenir un service (jusqu\'à 6 DV/niv).' },
  { nom: 'Régénération',             ecole: 'Invocation',    niveaux: { Prêtre: 7, Druide: 7 },                                                    composantes: 'V, S, DF', portee: 'Contact',      duree: '1 min/niveau',                 description: 'Régénère 1 PV/round, repousse les membres coupés en 2d10 rounds, immunité saignement et mort par dégâts.' },
  { nom: 'Résurrection',             ecole: 'Invocation',    niveaux: { Prêtre: 7 },                                                               composantes: 'V, S, M, DF', portee: 'Contact',  duree: 'Instantané',                   description: 'Ramène à la vie une créature morte depuis ≤ 10 ans/niv. Perd un niveau de personnage.' },
  { nom: 'Contrôle météorologique',  ecole: 'Transmutation', niveaux: { Prêtre: 7, Druide: 7 },                                                    composantes: 'V, S',    portee: 'Extérieur 4,5 km de rayon', duree: '4d12 heures',  description: 'Modifie la météo locale : précipitations, vent, température, nuages (effets après 10 min).' },
  { nom: 'Tremblement de terre',     ecole: 'Évocation',     niveaux: { Prêtre: 8, Druide: 8 },                                                    composantes: 'V, S, DF', portee: 'Long',         duree: '1 round',                      description: 'Violent séisme sur 24 m de rayon : fissures, chutes, structures endommagées. Concentration brisée.' },
  { nom: 'Soins critiques de groupe', ecole: 'Invocation',   niveaux: { Prêtre: 8 },                                                               composantes: 'V, S',    portee: 'Courte',       duree: 'Instantané',                   description: 'Soigne 4d8 + 1/niv (max +40) à toutes les créatures alliées dans un rayon de 9 m.' },
  { nom: 'Résurrection véritable',   ecole: 'Invocation',    niveaux: { Prêtre: 9 },                                                               composantes: 'V, S, M, DF', portee: 'Contact',  duree: 'Instantané',                   description: 'Ramène à la vie sans perte de niveau, même depuis des cendres ou après une destruction totale. Aucune limite de temps.' },

  // ─── NIVEAU 6 ───
  { nom: 'Désintégration',           ecole: 'Transmutation', niveaux: { Magicien: 6, Ensorceleur: 6 },                                            composantes: 'V, S, M/F', portee: 'Moyen',     duree: 'Instantané',                   description: '2d6/niv dégâts de force (max 40d6, JS Vigueur pour 5d6). Désintègre complètement si tués.' },
  { nom: 'Globe d\'invulnérabilité', ecole: 'Abjuration',    niveaux: { Magicien: 6, Ensorceleur: 6 },                                            composantes: 'V, S, M', portee: '1,5 m',        duree: '1 round/niveau (D)',           description: 'Protège contre les sorts de niveau 1-4.' },
  { nom: 'Métamorphose des autres',  ecole: 'Transmutation', niveaux: { Magicien: 6, Ensorceleur: 6 },                                            composantes: 'V, S, M', portee: 'Moyen',        duree: 'Permanent',                    description: 'Transforme la cible en pierre (JS Vigueur annule).' },
  { nom: 'Suggestion de groupe',     ecole: 'Enchantement',  niveaux: { Magicien: 6, Ensorceleur: 6, Barde: 5 },                                  composantes: 'V, M',    portee: 'Moyen',        duree: '1h/niv',                       description: 'Comme Suggestion mais affecte 1 sujet/niv.' },
  { nom: 'Image programmatique',     ecole: 'Illusion',      niveaux: { Magicien: 6, Ensorceleur: 6, Barde: 6 },                                  composantes: 'V, S, F', portee: 'Long',         duree: 'Permanent jusqu\'à activation', description: 'Illusion activée par conditions. Dure 1 round/niv une fois activée.' },
  { nom: 'Regard pétrifiant',        ecole: 'Nécromancie',   niveaux: { Magicien: 6, Ensorceleur: 6 },                                            composantes: 'V, S',    portee: '9 m (vue)',     duree: '1 round/niveau',               description: 'Aveugle, endort ou épuise la cible (JS Vigueur).' },
  { nom: 'Résurrection vraie',       ecole: 'Invocation',    niveaux: { Prêtre: 7 },                                                              composantes: 'V, S, M, DF', portee: 'Contact', duree: 'Instantané',                   description: 'Ramène à la vie sans perte de niveaux, même après une destruction totale.' },

  // ─── NIVEAU 7 ───
  { nom: 'Cage de force',            ecole: 'Évocation',     niveaux: { Magicien: 7, Ensorceleur: 7 },                                            composantes: 'V, S, M', portee: 'Courte',       duree: '2 h/niv (D)',                  description: 'Prison de barreaux ou cube de force indestructible.' },
  { nom: 'Doigt de mort',            ecole: 'Nécromancie',   niveaux: { Magicien: 7, Ensorceleur: 7, Druide: 8 },                                 composantes: 'V, S',    portee: 'Courte',       duree: 'Instantané',                   description: 'Tue instantanément si la cible rate son JS Vigueur (sinon 3d6+1/niv dégâts).' },
  { nom: 'Téléportation parfaite',   ecole: 'Invocation',    niveaux: { Magicien: 7, Ensorceleur: 7 },                                            composantes: 'V',       portee: 'Contact',      duree: 'Instantané',                   description: 'Téléportation sans risque d\'erreur vers tout lieu connu.' },
  { nom: 'Simulacre',                ecole: 'Illusion',      niveaux: { Magicien: 7, Ensorceleur: 7 },                                            composantes: 'V, S, M', portee: 'Contact',      duree: 'Permanent',                    description: 'Crée une illusion à moitié réelle d\'une créature (obéit à l\'incantateur).' },
  { nom: 'Paralysie de groupe',      ecole: 'Enchantement',  niveaux: { Magicien: 7, Ensorceleur: 7 },                                            composantes: 'V, S, M', portee: 'Moyen',        duree: '1 round/niveau (D)',           description: 'Paralyse tous les humanoïdes dans la zone.' },
  { nom: 'Grande téléportation',     ecole: 'Invocation',    niveaux: { Prêtre: 7 },                                                              composantes: 'V',       portee: 'Contact',      duree: 'Instantané',                   description: 'Téléportation parfaite (comme Magicien niv. 7).' },

  // ─── NIVEAU 8 ───
  { nom: 'Labyrinthe',               ecole: 'Invocation',    niveaux: { Magicien: 8, Ensorceleur: 8 },                                            composantes: 'V, S',    portee: 'Courte',       duree: 'Voir description',             description: 'Envoie la cible dans un labyrinthe extra-dimensionnel.' },
  { nom: 'Danse irrésistible',       ecole: 'Enchantement',  niveaux: { Magicien: 8, Ensorceleur: 8, Barde: 6 },                                  composantes: 'V',       portee: 'Contact',      duree: '1d4+1 rounds',                 description: 'La cible danse (−4 CA, ne peut rien faire d\'autre).' },
  { nom: 'Mot de pouvoir : Hébétement', ecole: 'Enchantement', niveaux: { Magicien: 8, Ensorceleur: 8 },                                          composantes: 'V',       portee: 'Courte',       duree: 'Voir description',             description: 'Hébète une créature selon ses PV actuels (pas de JS).' },
  { nom: 'Métamorphose universelle',  ecole: 'Transmutation', niveaux: { Magicien: 8, Ensorceleur: 8 },                                            composantes: 'V, S, M', portee: 'Courte',       duree: 'Permanent',                    description: 'Transforme un objet ou une créature en autre chose.' },
  { nom: 'Symbole de mort',          ecole: 'Nécromancie',   niveaux: { Magicien: 8, Ensorceleur: 8, Prêtre: 8 },                                 composantes: 'V, S, M', portee: '0 m',          duree: 'Voir description',             description: 'Tue 150 PV de créatures dans un rayon de 18 m (JS Vigueur annule).' },

  // ─── NIVEAU 9 ───
  { nom: 'Souhait',                  ecole: 'Universel',     niveaux: { Magicien: 9, Ensorceleur: 9 },                                            composantes: 'V, XP',   portee: 'Voir description', duree: 'Voir description',          description: 'Sort le plus puissant : peut dupliquer presque tout sort de niveau 8 ou moins.' },
  { nom: 'Arrêt du temps',           ecole: 'Transmutation', niveaux: { Magicien: 9, Ensorceleur: 9 },                                            composantes: 'V',       portee: 'Personnel',    duree: '1d4+1 rounds',                 description: 'Temps gelé pour tous sauf le lanceur (2-5 rounds d\'actions libres).' },
  { nom: 'Porte',                    ecole: 'Invocation',    niveaux: { Magicien: 9, Ensorceleur: 9, Prêtre: 9 },                                 composantes: 'V, S, XP', portee: 'Moyen',       duree: 'Voir description',             description: 'Ouvre un portail vers un autre plan ou convoque une créature planaire.' },
  { nom: 'Sphère prismatique',       ecole: 'Abjuration',    niveaux: { Magicien: 9, Ensorceleur: 9 },                                            composantes: 'V',       portee: '1,5 m',        duree: '10 min/niveau (D)',            description: 'Sphère de 7 couches colorées protégeant contre tout.' },
  { nom: 'Tempête de météores',      ecole: 'Évocation',     niveaux: { Magicien: 9, Ensorceleur: 9 },                                            composantes: 'V, S',    portee: 'Long',         duree: 'Instantané',                   description: '4 météores : chacun 6d6 impact + 6d6 feu (JS Réflexes pour 1/2).' },
  { nom: 'Mot de pouvoir : Mort',    ecole: 'Enchantement',  niveaux: { Magicien: 9, Ensorceleur: 9 },                                            composantes: 'V',       portee: 'Courte',       duree: 'Instantané',                   description: 'Tue instantanément une créature de 100 PV ou moins.' },
  { nom: 'Vision du futur',          ecole: 'Divination',    niveaux: { Magicien: 9, Ensorceleur: 9, Druide: 9 },                                 composantes: 'V, S',    portee: 'Personnel',    duree: '10 min/niveau',                description: 'Ne peut pas être surpris, +2 aux att, CA, saves. Perçoit les dangers immédiats.' },
  { nom: 'Miracle',                  ecole: 'Invocation',    niveaux: { Prêtre: 9 },                                                              composantes: 'V, S, XP', portee: 'Voir description', duree: 'Voir description',         description: 'Version divine du Souhait.' },
  { nom: 'Œuvre de la nature',       ecole: 'Transmutation', niveaux: { Druide: 9 },                                                              composantes: 'V, S, DF', portee: '180 m',       duree: '2d4 rounds',                   description: 'Appelle une catastrophe naturelle (tremblement de terre, etc.).' },

  // ─── SORTS DES ROYAUMES OUBLIÉS (Univers, chapitre 2, p.66-75) ───
  { nom: 'Analyse de portail',       ecole: 'Divination',    niveaux: { Barde: 3, Magicien: 3, Ensorceleur: 3 },                                  composantes: 'V, G, M/FD', portee: '18 m',      duree: 'Concentration (1 round/niv max)', description: 'Détecte les portails et révèle leurs propriétés (clef, destination, type). Aussi sort de domaine (Portails 2).' },
  { nom: 'Araignées de pierre',      ecole: 'Transmutation', niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Courte',      duree: '1 round/niveau (T)',           description: 'Sort de domaine (Araignées 7). Transforme 1d3 cailloux en araignées monstrueuses de pierre (réduction de dégâts 30/+1, armure naturelle +6).' },
  { nom: 'Armure des ténèbres',      ecole: 'Abjuration',    niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Contact',     duree: '10 min/niveau',                description: 'Sort de domaine (Obscurité 4). Voile d\'ombres : +3 CA +1 par 4 niveaux (max +8), +2 aux JS contre la lumière et le Bien ; morts-vivants +4 contre le renvoi.' },
  { nom: 'Création de tatouage magique', ecole: 'Invocation', niveaux: { Magicien: 2, Ensorceleur: 2 },                                           composantes: 'V, G, M, F', portee: 'Contact',   duree: '1 jour',                       description: 'Crée un tatouage magique (bonus selon le niveau : +2 résistance à un type de JS, +2 JS, +1 CA, +2 aptitude, +1 niveau de lanceur…). Max 3 tatouages par créature.' },
  { nom: 'Dépeçage',                 ecole: 'Évocation',     niveaux: { Magicien: 8, Ensorceleur: 8 },                                            composantes: 'V, G, M', portee: 'Courte',       duree: 'Jusqu\'à 4 rounds',            description: 'Dépèce une créature tangible : 1d6 dégâts + affaiblissement 1d6 CHA et CON par round (Vigueur annule l\'affaiblissement et réduit de moitié).' },
  { nom: 'Dérobade d\'Elminster',    ecole: 'Évocation',     niveaux: { Magicien: 9, Ensorceleur: 9 },                                            composantes: 'V, G, M, F, PX', portee: 'Personnelle', duree: 'Jusqu\'à utilisation',   description: 'Contingence puissante : téléporte automatiquement le lanceur (et 25 kg d\'objets) vers un lieu sûr quand il est en péril. Coût : 5 000 PX.' },
  { nom: 'Dispersion',               ecole: 'Transmutation', niveaux: { Magicien: 1, Ensorceleur: 1 },                                            composantes: 'V, G',    portee: 'Courte',       duree: 'Instantané',                   description: 'Disperse violemment jusqu\'à 5 petits objets (≤ 12,5 kg au total) dans un rayon de 3 m ; objets pointus : 1d8 dégâts (Réflexes annule).' },
  { nom: 'Éclair des ténèbres',      ecole: 'Évocation',     niveaux: {},                                                                         composantes: 'V, G',    portee: 'Moyenne',      duree: 'Instantané',                   description: 'Sort de domaine (Obscurité 5). Un éclair d\'ombres par 2 niveaux (max 7) : 2d8 dégâts et cible étourdie 1 round (Volonté annule l\'étourdissement).' },
  { nom: 'Éclat',                    ecole: 'Évocation',     niveaux: { Magicien: 3, Ensorceleur: 3 },                                            composantes: 'V, G, M/FD', portee: 'Longue',    duree: 'Instantané',                   description: 'Flash de lumière aveuglant (explosion de 6 m) : aveuglés 2d8 rounds (Volonté annule) ; à l\'extérieur de la zone, aveuglés 1 round.' },
  { nom: 'Feu de lune',              ecole: 'Évocation',     niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Courte',      duree: 'Instantané',                   description: 'Sort de domaine (Lune 9). Cône de lumière lunaire : 1d8 dégâts par 2 niveaux (max 10d8), doublés contre les morts-vivants ; les lycanthropes reprennent forme humaine ; révèle l\'invisible.' },
  { nom: 'Forme arachnide',          ecole: 'Transmutation', niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Personnelle', duree: '1 heure/niveau (T)',           description: 'Sort de domaine (Drows 5). Le lanceur se transforme en drider ou en araignée monstrueuse (TP à G).' },
  { nom: 'Foulée enflammée',         ecole: 'Transmutation', niveaux: { Magicien: 4, Ensorceleur: 4 },                                            composantes: 'V, G',    portee: 'Personnelle',  duree: '10 min/niveau ou jusqu\'à utilisation', description: 'Le lanceur entre dans un feu et se téléporte vers un autre foyer suffisamment grand situé à longue portée (120 m + 12 m/niveau).' },
  { nom: 'Gemme explosive',          ecole: 'Invocation',    niveaux: {},                                                                         composantes: 'V, G, M', portee: 'Contact',      duree: '10 min/niveau ou jusqu\'à utilisation', description: 'Sort de domaine (Commerce 2, Gnomes 2). Transforme jusqu\'à 5 gemmes (1 po min) en bombes : 1d8 de force par 2 niveaux (max 5d8), lancer à 30 m (Réflexes 1/2).' },
  { nom: 'Griffes d\'ombres',        ecole: 'Illusion',      niveaux: { Magicien: 2, Ensorceleur: 2 },                                            composantes: 'V, G',    portee: 'Personnelle',  duree: '1 round/niveau (T)',           description: 'Griffes d\'ombre (allonge 1,80 à 3 m) : attaques de contact, 1d4 dégâts de froid par griffe ; lutte avec bonus.' },
  { nom: 'Gris manteau de Grimwald', ecole: 'Nécromancie',   niveaux: { Magicien: 5, Ensorceleur: 5 },                                            composantes: 'V, G, M', portee: 'Moyenne',      duree: '1 round/niveau',               description: 'Lueur grise sur la cible : bloque toute guérison et régénération de points de vie pendant la durée (Vigueur annule).' },
  { nom: 'Hurlement assourdissant',  ecole: 'Évocation',     niveaux: { Barde: 6, Magicien: 8, Ensorceleur: 8 },                                  composantes: 'V, G, M', portee: 'Courte',       duree: 'Instantané',                   description: 'Ligne puis cône sonique : 20d6 aux objets de pierre/métal/cristal ; créatures 10d6, étourdies 1 round et assourdies 4d6 rounds (Vigueur réduit).' },
  { nom: 'Incinérateur d\'Aganazzar', ecole: 'Évocation',    niveaux: { Magicien: 2, Ensorceleur: 2 },                                            composantes: 'V, G, F', portee: 'Courte',       duree: 'Instantané',                   description: 'Jet de flammes en ligne (1,5 m de large) : 1d8 dégâts de feu par 2 niveaux (max 5d8), Réflexes 1/2. Focalisateur : écaille de dragon rouge.' },
  { nom: 'Lance tonnerre',           ecole: 'Évocation',     niveaux: { Magicien: 4, Ensorceleur: 4 },                                            composantes: 'V, G, M', portee: '0 m',          duree: '1 round/niveau (T)',           description: 'Lance de force lumineuse (dégâts d\'une pique TG, 2d6) maniable à une main ; taille ajustable, peut dissiper les effets de force adverses.' },
  { nom: 'Lueur noire',              ecole: 'Évocation',     niveaux: { Magicien: 3, Ensorceleur: 3 },                                            composantes: 'V, G, M', portee: 'Courte',       duree: '1 round/niveau (T)',           description: 'Cercle d\'obscurité totale de 6 m de rayon que seul le lanceur perce du regard (Volonté annule si lancé sur une créature). Aussi domaine Obscurité 3.' },
  { nom: 'Machine fantastique',      ecole: 'Illusion',      niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Moyenne',     duree: '1 minute/niveau (T)',          description: 'Sort de domaine (Artisanat 6, Gnomes 6). Machine illusoire de taille G (22 pv, CA 14) qui exécute des tâches physiques simples : creuse, porte, attaque (+5, 1d8+4).' },
  { nom: 'Machine fantastique améliorée', ecole: 'Illusion', niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Moyenne',     duree: '1 minute/niveau (T)',          description: 'Sort de domaine (Artisanat 9). Version supérieure : 16 DV, 88 pv, CA 20, Force 22, creuse et lance des pierres (2d6+9).' },
  { nom: 'Mâchoire de pierre',       ecole: 'Transmutation', niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Courte',      duree: '20 minutes/niveau (T)',        description: 'Sort de domaine (Cavernes 7). Anime une entrée de caverne (Force 30) qui mord les créatures désignées : attaque = niveau du prêtre + mod. de Sagesse + 7, morsure 2d6+10.' },
  { nom: 'Malédiction arachnide',    ecole: 'Transmutation', niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Moyenne',     duree: '1 jour/niveau',                description: 'Sort de domaine (Araignées 6). Transforme un humanoïde (taille M max) en serviteur mi-drider soumis aux ordres mentaux du lanceur (Volonté annule).' },
  { nom: 'Manteau de sombre puissance', ecole: 'Abjuration', niveaux: {},                                                                         composantes: 'V, G',    portee: 'Contact',      duree: '1 minute/niveau (T)',          description: 'Sort de domaine (Drows 1). Brume obscure protectrice : la cible est protégée des effets de la lumière du soleil (y compris l\'aveuglement des drows) et gagne +4 aux JS contre les sorts de lumière et d\'obscurité.' },
  { nom: 'Masque d\'ombres',         ecole: 'Illusion',      niveaux: { Magicien: 2, Ensorceleur: 2 },                                            composantes: 'V, G, M', portee: 'Personnelle',  duree: '10 minutes/niveau (T)',        description: 'Masque d\'ombres sur le visage : protège des sorts de lumière (+4 JS) et donne 50 % de chances d\'éviter les attaques de regard.' },
  { nom: 'Métamorphose arachnide',   ecole: 'Transmutation', niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Courte',      duree: '1 heure/niveau',               description: 'Sort de domaine (Araignées 9). Transforme une créature volontaire par niveau en araignée monstrueuse (TP à TG).' },
  { nom: 'Nuée de boules de neige de Snilloc', ecole: 'Évocation', niveaux: { Magicien: 2, Ensorceleur: 2 },                                      composantes: 'V, G, M', portee: 'Moyenne',      duree: 'Instantané',                   description: 'Rafale de boules de neige magiques (explosion 1,5 m) : 2d6 dégâts de froid, +1d6 par 2 niveaux au-delà du 3e (max 5d6 au niveau 9). Réflexes 1/2.' },
  { nom: 'Poussière d\'ombres',      ecole: 'Illusion',      niveaux: { Magicien: 2, Ensorceleur: 2 },                                            composantes: 'V, G, M', portee: 'Moyenne',      duree: '1 round/niveau',               description: 'Lambeaux d\'ombres explosifs (1,5 m de rayon) : affaiblissement de 2 en Force et malus de moral −2 aux JS contre la terreur pendant 1 round (Vigueur annule).' },
  { nom: 'Protection de fer mineure', ecole: 'Abjuration',   niveaux: { Magicien: 5, Ensorceleur: 5 },                                            composantes: 'V, G, M', portee: 'Contact',      duree: '1 round/niveau',               description: 'La cible devient immunisée au métal non magique, qui la traverse simplement (armes comprises) ; 1d6 dégâts si un objet en métal se trouve dans le corps quand le sort cesse.' },
  { nom: 'Rayon de lune',            ecole: 'Évocation',     niveaux: {},                                                                         composantes: 'V, G, M/FD', portee: 'Courte',    duree: '1 minute/niveau (T)',          description: 'Sort de domaine (Lune 2). Cône de lumière lunaire : les lycanthropes doivent réussir un jet de Volonté pour ne pas reprendre leur forme humanoïde.' },
  { nom: 'Sabre de lune',            ecole: 'Évocation',     niveaux: {},                                                                         composantes: 'V, G, M/FD', portee: '0 m',       duree: '1 minute/niveau (T)',          description: 'Sort de domaine (Lune 3). Épée de lumière lunaire (90 cm) : 1d8 +1 par 2 niveaux (max +15), morts-vivants +1 par niveau (max +30) ; perturbe la concentration des lanceurs touchés.' },
  { nom: 'Scellement de portail',    ecole: 'Abjuration',    niveaux: { Barde: 6, Druide: 6, Magicien: 6, Ensorceleur: 6, Prêtre: 6 },            composantes: 'V, G, M', portee: 'Courte',       duree: 'Permanente',                   description: 'Scelle définitivement un portail ou un sort de portail. Un carillon d\'ouverture le dissipe. Composante : lingot d\'argent de 50 po.' },
  { nom: 'Sort universel',           ecole: 'Transmutation', niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Personnelle', duree: 'Instantané',                   description: 'Sort de domaine (Sorts 3). Permet au prêtre de lire et préparer un sort de magie profane de niveau 2 maximum dans un de ses emplacements.' },
  { nom: 'Sort universel amélioré',  ecole: 'Transmutation', niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Personnelle', duree: 'Instantané',                   description: 'Sort de domaine (Sorts 6). Comme Sort universel, mais pour un sort profane de niveau 4 maximum.' },
  { nom: 'Splendeur de l\'aigle',    ecole: 'Transmutation', niveaux: { Barde: 2, Magicien: 2, Ensorceleur: 2 },                                  composantes: 'V, G, M/FD', portee: 'Contact',   duree: '1 min/niveau',                 description: '+4 au Charisme. Aussi sort de domaine (Commerce 3).' },
  { nom: 'Tourbillon',               ecole: 'Invocation',    niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Longue',      duree: '1 round/niveau',               description: 'Sort de domaine (Océan 8). Maelström de 36 m de large et 18 m de profondeur : aspire créatures et navires (3d8 dégâts par round, Réflexes annule).' },
  { nom: 'Trombe d\'eau',            ecole: 'Invocation',    niveaux: {},                                                                         composantes: 'V, G, FD', portee: 'Longue',      duree: '1 round/niveau',               description: 'Sort de domaine (Océans 7). Colonne d\'eau tourbillonnante (3 m de large, 24 m de haut) dirigeable : aspire les créatures (3d8 dégâts, Réflexes annule).' },
  { nom: 'Voie lunaire',             ecole: 'Évocation',     niveaux: {},                                                                         composantes: 'V, G, M/FD', portee: 'Moyenne',   duree: '1 minute/niveau (T)',          description: 'Sort de domaine (Lune 5). Pont/escalier de clair de lune (1,5 à 6 m de large, 4,7 m/niveau) ; les créatures désignées bénéficient d\'un effet de sanctuaire en l\'empruntant.' },
]

export function sortsByClasse(classe: ClasseSortKey): SortDnD[] {
  return SORTS_DND35.filter(s => classe in s.niveaux)
}

export function sortsByClasseEtNiveau(classe: ClasseSortKey, niveau: number): SortDnD[] {
  return SORTS_DND35.filter(s => s.niveaux[classe] === niveau)
}

export function niveauxMaxForClasse(classe: ClasseSortKey): number {
  const sorts = sortsByClasse(classe)
  if (sorts.length === 0) return 0
  return Math.max(...sorts.map(s => s.niveaux[classe] ?? 0))
}
